Repository ESMValGroup/ESMValTool, pull requests merged in 2018-11, with the labels that each got.

#631 add R diagnostic support
  .circleci/config.yml
  .gitignore
  README.md
  environment.yml
  esmvaltool/_task.py
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/examples/diagnostic.r
  esmvaltool/install/R/r_requirements.txt
  esmvaltool/install/R/setup.R
  esmvaltool/recipes/examples/recipe_r.yml
  language_support.sh
  meta.yaml
  tests/integration/test_diagnostic_run.py
Labels: enhancement, installation

#712 Cleaned python diagnostics
  esmvaltool/diag_scripts/climate_metrics/ecs.py
  esmvaltool/diag_scripts/ipcc_ar5/ch09_fig09_42a.py
  esmvaltool/diag_scripts/shared/__init__.py
  esmvaltool/diag_scripts/shared/_base.py
  esmvaltool/diag_scripts/shared/plot/_plot.py
Labels: diagnostic

#692 Improved NCL interface
  doc/sphinx/source/developer_guide2/porting.inc
  esmvaltool/_task.py
  esmvaltool/diag_scripts/clouds/clouds.ncl
  esmvaltool/diag_scripts/clouds/clouds_bias.ncl
  esmvaltool/diag_scripts/clouds/clouds_interannual.ncl
  esmvaltool/diag_scripts/clouds/clouds_ipcc.ncl
  esmvaltool/diag_scripts/clouds/clouds_taylor.ncl
  esmvaltool/diag_scripts/examples/diagnostic.ncl
  esmvaltool/diag_scripts/examples/diagnostic_pr.ncl
  esmvaltool/diag_scripts/examples/diagnostic_ta.ncl
  esmvaltool/diag_scripts/perfmetrics/collect.ncl
  esmvaltool/diag_scripts/perfmetrics/cycle.ncl
  esmvaltool/diag_scripts/perfmetrics/cycle_latlon.ncl
  esmvaltool/diag_scripts/perfmetrics/latlon.ncl
  esmvaltool/diag_scripts/perfmetrics/main.ncl
  esmvaltool/diag_scripts/perfmetrics/zonal.ncl
  esmvaltool/diag_scripts/shared/ensemble.ncl
  esmvaltool/diag_scripts/shared/plot/contour_maps.ncl
  esmvaltool/diag_scripts/shared/plot/portrait_plot.ncl
  esmvaltool/diag_scripts/shared/plot/style.ncl
  esmvaltool/diag_scripts/shared/plot/styles/go.style
  esmvaltool/diag_scripts/shared/plot/taylor_diagram_less_hardcoded.ncl
  esmvaltool/diag_scripts/shared/plot/taylor_plot.ncl
  esmvaltool/diag_scripts/shared/plot/xy_line.ncl
  esmvaltool/diag_scripts/shared/plot/zonalmean_profile.ncl
  esmvaltool/diag_scripts/shared/regridding.ncl
  esmvaltool/interface_scripts/auxiliary.ncl
  esmvaltool/interface_scripts/data_handling.ncl
  esmvaltool/interface_scripts/interface.ncl
  esmvaltool/interface_scripts/logging.ncl
  esmvaltool/interface_scripts/write_header.ncl
  esmvaltool/interface_scripts/write_references.ncl
  esmvaltool/preprocessor/_io.py
  esmvaltool/recipes/examples/recipe_ncl.yml
  esmvaltool/utils/editor-enhancements/ncl-ESMValTool.el
Labels: enhancement

#681 started a branch in which I (VP) will write a whole bunch of documentation
  doc/sphinx/source/user_guide2/first_diagnostic.inc
  doc/sphinx/source/user_guide2/preprocessor.inc
Labels: documentation
