Repository ESMValGroup/ESMValTool, pull requests merged in 2018-12, with the labels that each got.

#729 Concatenation of different experiments
  esmvaltool/_data_finder.py
  esmvaltool/_recipe.py
  esmvaltool/preprocessor/_io.py
  esmvaltool/recipe_schema.yml
  esmvaltool/recipes/examples/recipe_concatenate_exps.yml
  tests/integration/data_finder.yml
  tests/integration/preprocessor/_io/test_concatenate.py
  tests/integration/preprocessor/_io/test_load.py
  tests/integration/test_data_finder.py
Labels: enhancement

#550 WIP: Version2 irregular 2d regridding
  .gitignore
  environment.yml
  esmvaltool/preprocessor/_mapping.py
  esmvaltool/preprocessor/_regrid.py
  esmvaltool/preprocessor/_regrid_esmpy.py
  tests/unit/preprocessor/_mapping/__init__.py
  tests/unit/preprocessor/_mapping/test_mapping.py
  tests/unit/preprocessor/_regrid_esmpy/__init__.py
  tests/unit/preprocessor/_regrid_esmpy/test_regrid_esmpy.py
Labels: backend

#705 Version2 cvdp
  doc/sphinx/source/recipes/recipe_cvdp.rst
  esmvaltool/diag_scripts/cvdp/__init__.py
  esmvaltool/diag_scripts/cvdp/cvdp/CVDP_readme.pdf
  esmvaltool/diag_scripts/cvdp/cvdp/LICENSE
  esmvaltool/diag_scripts/cvdp/cvdp/driver.ncl
  esmvaltool/diag_scripts/cvdp/cvdp/example_namelists/multiple_obs/namelist
  esmvaltool/diag_scripts/cvdp/cvdp/example_namelists/multiple_obs/namelist_obs
  esmvaltool/diag_scripts/cvdp/cvdp/example_namelists/multiple_obs/obs2_directory_contents
  esmvaltool/diag_scripts/cvdp/cvdp/example_namelists/namelist.CESM1-LENS
  esmvaltool/diag_scripts/cvdp/cvdp/example_namelists/namelist.CESMcomparison
  esmvaltool/diag_scripts/cvdp/cvdp/example_namelists/namelist.cmip3_20c3m
  esmvaltool/diag_scripts/cvdp/cvdp/example_namelists/namelist.cmip3_historical
  esmvaltool/diag_scripts/cvdp/cvdp/example_namelists/namelist.cmip5_historical
  esmvaltool/diag_scripts/cvdp/cvdp/example_namelists/namelist.cmip5_historical_1900-2005
  esmvaltool/diag_scripts/cvdp/cvdp/example_namelists/namelist.lgens
  esmvaltool/diag_scripts/cvdp/cvdp/example_namelists/namelist.lgens.add2ndobs
  esmvaltool/diag_scripts/cvdp/cvdp/example_namelists/namelist.multobs
  esmvaltool/diag_scripts/cvdp/cvdp/example_namelists/namelist.obs1
  esmvaltool/diag_scripts/cvdp/cvdp/example_namelists/namelist_obs_4sets
  esmvaltool/diag_scripts/cvdp/cvdp/namelist
  esmvaltool/diag_scripts/cvdp/cvdp/namelist_obs
  esmvaltool/diag_scripts/cvdp/cvdp/ncl_scripts/aice.mean_stddev.ncl
  esmvaltool/diag_scripts/cvdp/cvdp/ncl_scripts/aice.trends_timeseries.ncl
  esmvaltool/diag_scripts/cvdp/cvdp/ncl_scripts/amo.ncl
  esmvaltool/diag_scripts/cvdp/cvdp/ncl_scripts/amoc.ncl
  esmvaltool/diag_scripts/cvdp/cvdp/ncl_scripts/cas-cvdp.png
  esmvaltool/diag_scripts/cvdp/cvdp/ncl_scripts/functions.ncl
  esmvaltool/diag_scripts/cvdp/cvdp/ncl_scripts/ipo.ncl
  esmvaltool/diag_scripts/cvdp/cvdp/ncl_scripts/metrics.ncl
  esmvaltool/diag_scripts/cvdp/cvdp/ncl_scripts/namelist.ncl
  esmvaltool/diag_scripts/cvdp/cvdp/ncl_scripts/ncfiles.append.ncl
  esmvaltool/diag_scripts/cvdp/cvdp/ncl_scripts/pdo.ncl
  esmvaltool/diag_scripts/cvdp/cvdp/ncl_scripts/pr.mean_stddev.ncl
  esmvaltool/diag_scripts/cvdp/cvdp/ncl_scripts/pr.trends_timeseries.ncl
  esmvaltool/diag_scripts/cvdp/cvdp/ncl_scripts/psl.mean_stddev.ncl
  esmvaltool/diag_scripts/cvdp/cvdp/ncl_scripts/psl.modes_indices.ncl
  esmvaltool/diag_scripts/cvdp/cvdp/ncl_scripts/psl.nam_nao.ncl
  esmvaltool/diag_scripts/cvdp/cvdp/ncl_scripts/psl.pna_npo.ncl
  esmvaltool/diag_scripts/cvdp/cvdp/ncl_scripts/psl.sam_psa.ncl
  esmvaltool/diag_scripts/cvdp/cvdp/ncl_scripts/psl.trends.ncl
  esmvaltool/diag_scripts/cvdp/cvdp/ncl_scripts/snd.mean_stddev.ncl
  esmvaltool/diag_scripts/cvdp/cvdp/ncl_scripts/snd.trends.ncl
  esmvaltool/diag_scripts/cvdp/cvdp/ncl_scripts/sst.indices.ncl
  esmvaltool/diag_scripts/cvdp/cvdp/ncl_scripts/sst.mean_stddev.ncl
  esmvaltool/diag_scripts/cvdp/cvdp/ncl_scripts/sst.trends_timeseries.ncl
  esmvaltool/diag_scripts/cvdp/cvdp/ncl_scripts/tas.mean_stddev.ncl
  esmvaltool/diag_scripts/cvdp/cvdp/ncl_scripts/tas.trends_timeseries.ncl
  esmvaltool/diag_scripts/cvdp/cvdp/ncl_scripts/webpage.ncl
  esmvaltool/diag_scripts/cvdp/cvdp_wrapper.py
  esmvaltool/recipes/recipe_cvdp.yml
  tests/unit/diag_scripts/test_cvdp.py
  tests/unit/test_lint.py
  tests/unit/test_naming.py
Labels: MAGIC, diagnostic

#719 Version2 runoff et
  doc/sphinx/source/recipes/figures/runoff_et/MPI-ESM-LR_historical_r1i1p1_bias-plot_mrro.png
  doc/sphinx/source/recipes/figures/runoff_et/MPI-ESM-LR_historical_r1i1p1_rocoef-vs-relprbias.png
  doc/sphinx/source/recipes/figures/runoff_et/catchments.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_runoff_et.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/runoff_et/catchment_analysis.py
  esmvaltool/recipes/recipe_runoff_et.yml
Labels: diagnostic

#730 Version2 flato 9 8
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_flato13ipcc.rst
  esmvaltool/diag_scripts/ipcc_ar5/tsline.ncl
  esmvaltool/diag_scripts/shared/plot/styles/cmip5.style
  esmvaltool/diag_scripts/shared/plot/xy_line.ncl
  esmvaltool/interface_scripts/interface.ncl
  esmvaltool/recipes/recipe_flato13ipcc.yml
  esmvaltool/utils/batch-jobs/job_DKRZ-MISTRAL.sh
  esmvaltool/utils/editor-enhancements/ncl-ESMValTool.el
Labels: diagnostic
