Repository ESMValGroup/ESMValTool, pull requests merged in 2018-07, with the labels that each got.

#490 Basic plotting for python diagnostics
  esmvaltool/diag_scripts/examples/diagnostic_object_oriented.py
  esmvaltool/diag_scripts/shared/_diag.py
  esmvaltool/diag_scripts/shared/plot/__init__.py
  esmvaltool/diag_scripts/shared/plot/_plot.py
  esmvaltool/diag_scripts/shared/plot/styles_python/cmip5.yml
  esmvaltool/diag_scripts/shared/plot/styles_python/convert_ncl_style.py
  esmvaltool/diag_scripts/shared/plot/styles_python/style_header
Labels: enhancement

#502 Allowing empty preprocessor
  esmvaltool/_recipe.py
Labels: bug

#511 ECS diagnostic
  esmvaltool/diag_scripts/climate_metrics/ecs.py
  esmvaltool/diag_scripts/shared/_diag.py
  esmvaltool/diag_scripts/shared/names.py
  esmvaltool/diag_scripts/shared/plot/_plot.py
  esmvaltool/preprocessor/_time_area.py
Labels: diagnostic

#515 First figure (9.42a) of IPCC AR5 ch.9 recipe (Flato 2013)
  esmvaltool/diag_scripts/climate_metrics/ecs.py
  esmvaltool/diag_scripts/ipcc_ar5/ch09_fig09_42a.py
  esmvaltool/diag_scripts/shared/_diag.py
  esmvaltool/diag_scripts/shared/names.py
  esmvaltool/diag_scripts/shared/plot/_plot.py
  esmvaltool/recipes/recipe_flato13ipcc.yml
  esmvaltool/recipes/recipe_perfmetrics_CMIP5.yml
Labels: diagnostic

#533 Allowed recipes with no scripts
  esmvaltool/_recipe.py
  esmvaltool/recipes/recipe_preprocessor_test.yml
Labels: bug

#536 Update _data_finder.py
  esmvaltool/_data_finder.py
  tests/unit/data_finder/test_get_start_end_year.py
Labels: backend, enhancement, standards

#534 Version2 autoassess v1 port
  esmvaltool/cmor/tables/custom/CMOR_rlns.dat
  esmvaltool/cmor/tables/custom/CMOR_rsns.dat
  esmvaltool/cmor/tables/custom/CMOR_rsnt.dat
  esmvaltool/cmor/tables/custom/CMOR_rtnt.dat
  esmvaltool/diag_scripts/autoassess/autoassess_radiation_rms.py
  esmvaltool/diag_scripts/autoassess/autoassess_source/__init__.py
  esmvaltool/diag_scripts/autoassess/autoassess_source/area_utils.py
  esmvaltool/diag_scripts/autoassess/autoassess_source/landsea.nc
  esmvaltool/diag_scripts/autoassess/autoassess_source/rms.py
  esmvaltool/diag_scripts/autoassess/autoassess_source/valmod_radiation.py
  esmvaltool/preprocessor/_derive.py
  esmvaltool/recipes/recipe_autoassess_radiation_rms_Amon_all.yml
  esmvaltool/recipes/recipe_autoassess_radiation_rms_Amon_obs.yml
  esmvaltool/recipes/recipe_autoassess_radiation_rms_cfMon_all.yml
Labels: portingV1toV2
