Repository ESMValGroup/ESMValTool, pull requests merged in 2019-05, with the labels that each got.

#1008 Provenance logging for zmnam figures
  esmvaltool/diag_scripts/zmnam/zmnam.py
  esmvaltool/diag_scripts/zmnam/zmnam_calc.py
Labels: MAGIC, diagnostic

#1007 Provenance logging for MiLES figures
  esmvaltool/diag_scripts/miles/block_figures.R
  esmvaltool/diag_scripts/miles/eof_figures.R
  esmvaltool/diag_scripts/miles/miles_block.R
  esmvaltool/diag_scripts/miles/miles_eof.R
  esmvaltool/diag_scripts/miles/miles_regimes.R
  esmvaltool/diag_scripts/miles/regimes_figures.R
  esmvaltool/recipes/recipe_miles_block.yml
  esmvaltool/recipes/recipe_miles_eof.yml
  esmvaltool/recipes/recipe_miles_regimes.yml
Labels: MAGIC, diagnostic

#957 Improved ensclus diagnostics
  doc/sphinx/source/recipes/figures/ensclus/ensclus.png
  doc/sphinx/source/recipes/recipe_ensclus.rst
  esmvaltool/diag_scripts/ensclus/ens_eof_kmeans.py
  esmvaltool/diag_scripts/ensclus/ens_plots.py
  esmvaltool/diag_scripts/ensclus/ensclus.py
  esmvaltool/recipes/recipe_ensclus.yml
Labels: MAGIC, diagnostic

#996 Fix provenance logging error
  esmvaltool/_task.py
Labels: documentation

#619 MAGIC WP7 RainFARM stochastic downscaling
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_rainfarm.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/rainfarm/rainfarm.R
  esmvaltool/install/Julia/julia_requirements.txt
  esmvaltool/install/R/r_requirements.txt
  esmvaltool/recipes/recipe_rainfarm.yml
Labels: MAGIC, diagnostic

#1039 Allow specifying all information in dataset
  esmvaltool/_recipe.py
  esmvaltool/recipe_schema.yml
  tests/integration/test_recipe.py
Labels: MAGIC

#1040 Only plot provenance if it contains fewer than 100 records
  esmvaltool/_provenance.py
Labels: MAGIC

#995 Doc magic bsc
  doc/sphinx/source/recipes/recipe_combined_climate_extreme_index.rst
  doc/sphinx/source/recipes/recipe_diurnal_temperature_index.rst
  doc/sphinx/source/recipes/recipe_modes_of_variability.rst
  doc/sphinx/source/recipes/recipe_multimodel_products.rst
  doc/sphinx/source/recipes/recipe_toymodel.rst
  esmvaltool/diag_scripts/magic_bsc/capacity_factor.r
  esmvaltool/diag_scripts/magic_bsc/combined_indices.r
  esmvaltool/diag_scripts/magic_bsc/extreme_index.r
  esmvaltool/diag_scripts/magic_bsc/multimodel_products.r
  esmvaltool/recipes/recipe_capacity_factor.yml
  esmvaltool/recipes/recipe_combined_indices.yml
  esmvaltool/recipes/recipe_diurnal_temperature_index.yml
  esmvaltool/recipes/recipe_extreme_index.yml
  esmvaltool/recipes/recipe_extreme_index_wp7.yml
  esmvaltool/recipes/recipe_heatwaves_coldwaves.yml
  esmvaltool/recipes/recipe_modes_of_variability.yml
  esmvaltool/recipes/recipe_multimodel_products.yml
  esmvaltool/recipes/recipe_toymodel.yml
Labels: MAGIC, documentation

#1045 Clean auxiliary.ncl
  esmvaltool/diag_scripts/shared/statistics.ncl
  esmvaltool/interface_scripts/auxiliary.ncl
  esmvaltool/utils/editor-enhancements/ncl-ESMValTool.el
Labels: Workshop / Paper, enhancement

#1049 Update recipe_quantilebias.rst
  doc/sphinx/source/recipes/recipe_quantilebias.rst
Labels: MAGIC, documentation

#1048 Update recipe_shapeselect.rst
  doc/sphinx/source/recipes/recipe_shapeselect.rst
Labels: MAGIC, documentation

#1050 Develop extreme
  doc/sphinx/source/recipes/recipe_combined_climate_extreme_index.rst
  esmvaltool/diag_scripts/magic_bsc/extreme_index.r
  esmvaltool/recipes/recipe_extreme_index.yml
Labels: MAGIC, diagnostic

#1035 Add provenance log to perfmetrics diagnostics
  doc/sphinx/source/recipes/recipe_perfmetrics.rst
  doc/sphinx/source/recipes/recipe_smpi.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/perfmetrics/collect.ncl
  esmvaltool/diag_scripts/perfmetrics/cycle.ncl
  esmvaltool/diag_scripts/perfmetrics/cycle_latlon.ncl
  esmvaltool/diag_scripts/perfmetrics/cycle_zonal.ncl
  esmvaltool/diag_scripts/perfmetrics/latlon.ncl
  esmvaltool/diag_scripts/perfmetrics/main.ncl
  esmvaltool/diag_scripts/perfmetrics/zonal.ncl
  esmvaltool/diag_scripts/shared/latlon.ncl
  esmvaltool/diag_scripts/shared/plot/portrait_plot.ncl
  esmvaltool/interface_scripts/logging.ncl
  esmvaltool/recipes/recipe_perfmetrics_CMIP5.yml
  esmvaltool/recipes/recipe_perfmetrics_CMIP5_4cds.yml
  esmvaltool/recipes/recipe_smpi.yml
  esmvaltool/utils/editor-enhancements/ncl-ESMValTool.el
Labels: MAGIC

#782 Version2 thermodyn diagtool
  doc/sphinx/source/recipes/figures/thermodyn_diagtool/CanESM2_2458_lec_diagram.pdf
  doc/sphinx/source/recipes/figures/thermodyn_diagtool/CanESM2_wmb_transp.png
  doc/sphinx/source/recipes/figures/thermodyn_diagtool/IPSL-CM5A-MR_energy_climap.png
  doc/sphinx/source/recipes/figures/thermodyn_diagtool/meridional_transp.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_thermodyn_diagtool.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/thermodyn_diagtool/__init__.py
  esmvaltool/diag_scripts/thermodyn_diagtool/computations.py
  esmvaltool/diag_scripts/thermodyn_diagtool/fluxogram.py
  esmvaltool/diag_scripts/thermodyn_diagtool/fourier_coefficients.py
  esmvaltool/diag_scripts/thermodyn_diagtool/lorenz_cycle.py
  esmvaltool/diag_scripts/thermodyn_diagtool/mkthe.py
  esmvaltool/diag_scripts/thermodyn_diagtool/plot_script.py
  esmvaltool/diag_scripts/thermodyn_diagtool/provenance_meta.py
  esmvaltool/diag_scripts/thermodyn_diagtool/thermodyn_diagnostics.py
  esmvaltool/recipes/recipe_thermodyn_diagtool.yml
Labels: diagnostic

#1056 Added CMORizer for MTE
  doc/sphinx/source/user_guide2/observations.inc
  esmvaltool/cmor/tables/custom/CMOR_gppStderr.dat
  esmvaltool/cmor/tables/custom/CMOR_nbp_grid.dat
  esmvaltool/config-references.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/utils/cmorizers/obs/cmor_config/MTE.yml
  esmvaltool/utils/cmorizers/obs/cmorize_obs_Landschuetzer2016.py
  esmvaltool/utils/cmorizers/obs/cmorize_obs_MTE.py
  esmvaltool/utils/cmorizers/obs/cmorize_obs_WOA.py
  esmvaltool/utils/cmorizers/obs/utilities.py
Labels: standards

#754 MAGIC WP4 and WP6 hyint
  doc/sphinx/source/recipes/figures/hyint/hyint_maps.png
  doc/sphinx/source/recipes/figures/hyint/hyint_timeseries.png
  doc/sphinx/source/recipes/figures/hyint/hyint_trends.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_hyint.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/hyint/hyint.R
  esmvaltool/diag_scripts/hyint/hyint_diagnostic.R
  esmvaltool/diag_scripts/hyint/hyint_etccdi_preproc.R
  esmvaltool/diag_scripts/hyint/hyint_functions.R
  esmvaltool/diag_scripts/hyint/hyint_metadata.R
  esmvaltool/diag_scripts/hyint/hyint_parameters.R
  esmvaltool/diag_scripts/hyint/hyint_plot_maps.R
  esmvaltool/diag_scripts/hyint/hyint_plot_trends.R
  esmvaltool/diag_scripts/hyint/hyint_preproc.R
  esmvaltool/diag_scripts/hyint/hyint_trends.R
  esmvaltool/install/R/r_requirements.txt
  esmvaltool/recipes/recipe_hyint.yml
Labels: MAGIC, diagnostic

#1054 Update select_metadata_by_atts (interface.ncl)
  esmvaltool/interface_scripts/interface.ncl
Labels: enhancement

#1067 diag_shapeselect updated to write non-string attributes to xlsx
  esmvaltool/diag_scripts/shapeselect/diag_shapeselect.py
Labels: MAGIC

#1012 Various changes (unit tests, scripts from private repositories)
  esmvaltool/cmor/_fixes/CMIP5/GFDL_ESM2G.py
  esmvaltool/cmor/_fixes/CMIP5/NorESM1_ME.py
  esmvaltool/cmor/_fixes/CMIP6/__init__.py
  esmvaltool/cmor/tables/custom/CMOR_fgco2_grid.dat
  esmvaltool/cmor/tables/custom/CMOR_nbp_grid.dat
  esmvaltool/diag_scripts/climate_metrics/ecs.py
  esmvaltool/diag_scripts/climate_metrics/external_sources/ipcc_ar5.yml
  esmvaltool/diag_scripts/emergent_constraints/cox18nature.py
  esmvaltool/diag_scripts/ipcc_ar5/ch09_fig09_42a.py
  esmvaltool/diag_scripts/shared/_base.py
  esmvaltool/diag_scripts/shared/io.py
  esmvaltool/diag_scripts/shared/iris_helpers.py
  esmvaltool/diag_scripts/shared/plot/styles_python/cmip6.yml
  esmvaltool/preprocessor/_derive/_shared.py
  esmvaltool/preprocessor/_derive/fgco2_grid.py
  esmvaltool/preprocessor/_derive/nbp_grid.py
  esmvaltool/recipes/examples/recipe_preprocessor_derive_test.yml
  esmvaltool/recipes/recipe_cox18nature.yml
  esmvaltool/recipes/recipe_ecs.yml
  esmvaltool/recipes/recipe_flato13ipcc.yml
  tests/integration/cmor/_fixes/CMIP5/test_GFDL_ESM2G.py
  tests/integration/cmor/_fixes/CMIP5/test_MPI_ESM_LR.py
  tests/integration/cmor/_fixes/CMIP5/test_NorESM1_ME.py
  tests/unit/diag_scripts/shared/configs/test_io.yml
  tests/unit/diag_scripts/shared/test_io.py
  tests/unit/diag_scripts/shared/test_iris_helpers.py
  tests/unit/preprocessor/_derive/test_fgco2_grid.py
  tests/unit/preprocessor/_derive/test_nbp_grid.py
  tests/unit/preprocessor/_derive/test_shared.py
Labels: enhancement, fixes for datasets

#1061 Indices based on area averages
  doc/sphinx/source/recipes/figures/Index_NAO.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_combined_indices.rst
  esmvaltool/diag_scripts/magic_bsc/combined_indices.r
  esmvaltool/recipes/recipe_combined_indices.yml
Labels: MAGIC, diagnostic

#1075 Improve diagnostic task runner
  esmvaltool/_task.py
Labels: MAGIC

#1041 Use conda compilers instead of OS provided
  .circleci/config.yml
  CONTRIBUTING.md
  doc/sphinx/source/developer_guide2/config_developer.inc
  doc/sphinx/source/recipes/recipe_miles.rst
  doc/sphinx/source/user_guide2/config.inc
  doc/sphinx/source/user_guide2/install.inc
  environment.yml
Labels: installation

#1073 Added CMORizer for CRU
  doc/sphinx/source/user_guide2/observations.inc
  esmvaltool/config-references.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/utils/cmorizers/obs/cmor_config/CRU.yml
  esmvaltool/utils/cmorizers/obs/cmorize_obs_CRU.py
  esmvaltool/utils/cmorizers/obs/utilities.py
Labels: observations

#1014 Crescendo wp5 obs esacci oc
  doc/sphinx/source/user_guide2/observations.inc
  environment.yml
  esmvaltool/config-references.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/utils/cmorizers/obs/cmor_config/ESACCI-OC.yml
  esmvaltool/utils/cmorizers/obs/cmorize_obs_ESACCI-OC.py
Labels: observations

#1081 Remove unused XML library import and sort imports
  esmvaltool/diag_scripts/magic_bsc/PC.r
  esmvaltool/diag_scripts/magic_bsc/capacity_factor.r
Labels: MAGIC

#1087 Improve documentation
  doc/sphinx/source/conf.py
  doc/sphinx/source/process_ncl_docs2.py
  doc/sphinx/source/recipes/recipe_template.rst.template
  doc/sphinx/source/recipes/recipe_zmnam.rst
  esmvaltool/cmor/check.py
  esmvaltool/cmor/fix.py
  esmvaltool/preprocessor/_regrid.py
Labels: documentation

#1086 Any atmospheric variable
  doc/sphinx/source/recipes/recipe_multimodel_products.rst
Labels: MAGIC, documentation

#1088 doc and prov update for smpi running on Jasmin
  doc/sphinx/source/recipes/recipe_smpi.rst
  esmvaltool/recipes/recipe_smpi_4cds.yml
Labels: MAGIC, documentation

#1089 Update recipe_smpi.yml
  esmvaltool/recipes/recipe_smpi.yml
Labels: MAGIC, documentation

#1078 Improving Modes of Variability recipe
  doc/sphinx/source/recipes/recipe_modes_of_variability.rst
  esmvaltool/diag_scripts/magic_bsc/combined_indices.r
  esmvaltool/diag_scripts/magic_bsc/weather_regime.r
  esmvaltool/recipes/recipe_modes_of_variability.yml
Labels: MAGIC, diagnostic

#1080 Cvdp provenance v2
  doc/sphinx/source/recipes/figures/cvdp/nam.prreg.ann.png
  doc/sphinx/source/recipes/recipe_cvdp.rst
  environment.yml
  esmvaltool/diag_scripts/cvdp/cvdp_wrapper.py
  esmvaltool/recipes/recipe_cvdp.yml
Labels: MAGIC, diagnostic

#1091 Fix issue when downloading from multiple tasks
  esmvaltool/preprocessor/_download.py
Labels: enhancement

#1071 Added CMORizer for LandFlux-EVAL
  doc/sphinx/source/user_guide2/observations.inc
  esmvaltool/cmor/tables/custom/CMOR_et.dat
  esmvaltool/cmor/tables/custom/CMOR_etStderr.dat
  esmvaltool/config-references.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/utils/cmorizers/obs/cmor_config/LandFlux-EVAL.yml
  esmvaltool/utils/cmorizers/obs/cmor_config/MTE.yml
  esmvaltool/utils/cmorizers/obs/cmorize_obs.py
  esmvaltool/utils/cmorizers/obs/cmorize_obs_LandFlux_EVAL.py
Labels: observations

#1097 Revert "Improve diagnostic task runner"
  esmvaltool/_task.py
Labels: enhancement

#1052 Extreme Events
  doc/sphinx/source/recipes/figures/extreme_events/cdd_timeseries.png
  doc/sphinx/source/recipes/figures/extreme_events/gleckler.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_extreme_events.rst
  environment.yml
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/extreme_events/cfg_climdex.R
  esmvaltool/diag_scripts/extreme_events/cfg_extreme.R
  esmvaltool/diag_scripts/extreme_events/climdex.pcic.ncdf/CHANGELOG
  esmvaltool/diag_scripts/extreme_events/climdex.pcic.ncdf/CONTRIBUTING.rst
  esmvaltool/diag_scripts/extreme_events/climdex.pcic.ncdf/COPYING
  esmvaltool/diag_scripts/extreme_events/climdex.pcic.ncdf/DESCRIPTION
  esmvaltool/diag_scripts/extreme_events/climdex.pcic.ncdf/R/ncdf.R
  esmvaltool/diag_scripts/extreme_events/climdex.pcic.ncdf/README.rst
  esmvaltool/diag_scripts/extreme_events/climdex.pcic.ncdf/tests/bootstrap.R
  esmvaltool/diag_scripts/extreme_events/climdex.pcic.ncdf/tests/exemplar_data.rda
  esmvaltool/diag_scripts/extreme_events/climdex.pcic.ncdf/tests/test_basic_file_funcs.R
  esmvaltool/diag_scripts/extreme_events/climdex.pcic.ncdf/tests/test_var_meta.R
  esmvaltool/diag_scripts/extreme_events/common_climdex_preprocessing_for_plots.R
  esmvaltool/diag_scripts/extreme_events/extreme_events.R
  esmvaltool/diag_scripts/extreme_events/make_glecker_plot.R
  esmvaltool/diag_scripts/extreme_events/make_timeseries_plot.R
  esmvaltool/diag_scripts/shared/external.R
  esmvaltool/install/R/r_requirements.txt
  esmvaltool/recipes/recipe_extreme_events.yml
  meta.yaml
Labels: MAGIC, diagnostic, metric

#1102 Increase stdout buffer size to prevent NCL crash
  esmvaltool/_task.py
Labels: MAGIC

#1103 Prepare for MAGIC release
  conda_build_config.yaml
  esmvaltool/_version.py
  meta.yaml
Labels: MAGIC

#1060 Extend provenance test so it includes chained scripts
  tests/integration/test_recipe.py
Labels: documentation

#1094 Version2 eval4 cmip deangelis li framework
  esmvaltool/cmor/_fixes/CMIP5/ACCESS1_0.py
  esmvaltool/cmor/_fixes/CMIP5/ACCESS1_3.py
  esmvaltool/cmor/_fixes/CMIP5/CCSM4.py
  esmvaltool/cmor/tables/custom/CMOR_lvp.dat
  esmvaltool/cmor/tables/custom/CMOR_rlnst.dat
  esmvaltool/cmor/tables/custom/CMOR_rlnstcs.dat
  esmvaltool/cmor/tables/custom/CMOR_rsnst.dat
  esmvaltool/cmor/tables/custom/CMOR_rsnstcs.dat
  esmvaltool/cmor/tables/custom/CMOR_rsnstcsnorm.dat
  esmvaltool/config-references.yml
  esmvaltool/preprocessor/_derive/lvp.py
  esmvaltool/preprocessor/_derive/rlnst.py
  esmvaltool/preprocessor/_derive/rlnstcs.py
  esmvaltool/preprocessor/_derive/rsnst.py
  esmvaltool/preprocessor/_derive/rsnstcs.py
  esmvaltool/preprocessor/_derive/rsnstcsnorm.py
Labels: fixes for datasets
