Repository ESMValGroup/ESMValTool, pull requests merged in 2019-08, with the labels that each got.

#1221 Add alias to documentation
  doc/sphinx/source/esmvaldiag/new_diagnostic.rst
  esmvaltool/diag_scripts/shared/names.py
Labels: diagnostic, documentation

#1234 pin r-lintr to last stable version
  .circleci/config.yml
Labels: installation

#1214 Misspeling correction and sea mask
  doc/sphinx/source/recipes/figures/diurnal_temp_index/Seasonal_DTRindicator_MPI-ESM-MR_2030_2080_1961_1990.png
  doc/sphinx/source/recipes/figures/diurnal_temp_index/rcp85_diurnal.png
  doc/sphinx/source/recipes/recipe_diurnal_temperature_index.rst
  esmvaltool/diag_scripts/magic_bsc/diurnal_temp_index.r
  esmvaltool/recipes/recipe_diurnal_temperature_index.yml
Labels: diagnostic

#1237 R lintr install directly from CRAN
  .circleci/config.yml
  CONTRIBUTING.md
  esmvaltool/install/R/setup_lintr.R
Labels: installation

#1243 Fix environment in light of numerous problems with conda and deps
  .circleci/config.yml
  CONTRIBUTING.md
  doc/sphinx/source/requirements.txt
  environment.yml
  esmvaltool/install/R/setup_devutils.R
  esmvaltool/install/R/setup_lintr.R
Labels: HIGHPRIO, installation

#1252 pinned tiledb version and unpinned ncl
  CONTRIBUTING.md
  environment.yml
Labels: installation

#1259 added instructions how to install Julia
  CONTRIBUTING.md
Labels: documentation, installation

#1172 Adding a dumpload of documentation
  doc/sphinx/source/getting_started/config_user.rst
  doc/sphinx/source/preface/architecture.rst
Labels: documentation
