Repository ESMValGroup/ESMValTool, pull requests merged in 2019-07, with the labels that each got.

#1182 Fixed bug in shared I/O module
  esmvaltool/diag_scripts/shared/io.py
  tests/unit/diag_scripts/shared/test_io.py
Labels: bug

#1185 Improved plot labels in zmnam
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/zmnam/zmnam_plot.py
Labels: MAGIC

#1197 added the user config file as (one of any) keyword args to cmorizer func in python cmorizer scripts
  esmvaltool/cmorizers/obs/cmorize_obs.py
  esmvaltool/cmorizers/obs/cmorize_obs_cru.py
  esmvaltool/cmorizers/obs/cmorize_obs_esacci_oc.py
  esmvaltool/cmorizers/obs/cmorize_obs_landflux_eval.py
  esmvaltool/cmorizers/obs/cmorize_obs_landschuetzer2016.py
  esmvaltool/cmorizers/obs/cmorize_obs_mte.py
  esmvaltool/cmorizers/obs/cmorize_obs_woa.py
Labels: observations

#1204 Version2 fix recipe landschuetzer2016
  esmvaltool/recipes/recipe_ocean_Landschuetzer2016.yml
Labels: bug, observations

#1192 PR to hold changes to Autoassess Stratosphere codes resulting from review with Met Office
  esmvaltool/diag_scripts/autoassess/autoassess_area_base.py
  esmvaltool/diag_scripts/autoassess/land_surface_surfrad/surfrad.py
  esmvaltool/diag_scripts/autoassess/stratosphere/strat_metrics_1.py
Labels: diagnostic

#1198 Autoassess Stratosphere recipe and metrics documentation
  doc/sphinx/source/recipes/figures/autoassess_stratosphere/HadGEM3-GC31-LL_qbo.png
  doc/sphinx/source/recipes/figures/autoassess_stratosphere/HadGEM3-GC31-LL_u_jan.png
  doc/sphinx/source/recipes/figures/autoassess_stratosphere/UKESM1-0-LL_qbo.png
  doc/sphinx/source/recipes/figures/autoassess_stratosphere/UKESM1-0-LL_u_jan.png
  doc/sphinx/source/recipes/figures/autoassess_stratosphere/metrics.png
  doc/sphinx/source/recipes/figures/autoassess_stratosphere/qbo_30hpa.png
  doc/sphinx/source/recipes/figures/autoassess_stratosphere/teq_100hpa.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_autoassess_stratosphere.rst
  esmvaltool/diag_scripts/autoassess/autoassess_area_base.py
Labels: documentation

#1157 Show ESMValTool and ESMValCore documentation on a single readthedocs site
  .gitignore
  doc/sphinx/source/api/esmvaltool.diag_scripts.ocean.rst
  doc/sphinx/source/api/esmvaltool.diag_scripts.rst
  doc/sphinx/source/api/esmvaltool.diag_scripts.shared.rst
  doc/sphinx/source/api/esmvaltool.rst
  doc/sphinx/source/codedoc2/esmvalcore.cmor.rst
  doc/sphinx/source/codedoc2/esmvalcore.preprocessor.rst
  doc/sphinx/source/conf.py
  doc/sphinx/source/esmvalcore/config.inc
  doc/sphinx/source/esmvalcore/datafinder.inc
  doc/sphinx/source/esmvalcore/index.rst
  doc/sphinx/source/esmvalcore/preprocessor.inc
  doc/sphinx/source/esmvalcore/recipe.inc
  doc/sphinx/source/esmvaldiag/config_developer.rst
  doc/sphinx/source/esmvaldiag/git_repository.rst
  doc/sphinx/source/esmvaldiag/index.rst
  doc/sphinx/source/esmvaldiag/new_diagnostic.rst
  doc/sphinx/source/esmvaldiag/observations.rst
  doc/sphinx/source/esmvaldiag/porting.rst
  doc/sphinx/source/gensidebar.py
  doc/sphinx/source/getting_started/config_user.rst
  doc/sphinx/source/getting_started/index.rst
  doc/sphinx/source/getting_started/inputdata.rst
  doc/sphinx/source/getting_started/install.rst
  doc/sphinx/source/getting_started/outputdata.rst
  doc/sphinx/source/getting_started/running.rst
  doc/sphinx/source/index.rst
  doc/sphinx/source/preface/architecture.rst
  doc/sphinx/source/preface/core_team.rst
  doc/sphinx/source/preface/index.rst
  doc/sphinx/source/preface/intro.rst
  doc/sphinx/source/preface/license.rst
  doc/sphinx/source/preface/objectives.rst
Labels: documentation, paper

#1216 Fixed CRU CMORizer
  esmvaltool/cmorizers/obs/cmor_config/CRU.yml
  esmvaltool/cmorizers/obs/cmorize_obs_cru.py
  esmvaltool/cmorizers/obs/utilities.py
Labels: observations

#1084 CRESCENDO_WP5_OBS for ocean Primary Production
  doc/sphinx/source/getting_started/inputdata.rst
  esmvaltool/cmorizers/obs/cmor_config/Eppley-VGPM-MODIS.yml
  esmvaltool/cmorizers/obs/cmorize_obs_eppley_vgpm_modis.py
  esmvaltool/config-references.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
Labels: observations

#1206 Improving Toy Model Plot
  doc/sphinx/source/recipes/figures/toymodel/synthetic_CMIP5_IPSL-CM5A-LR_day_historical_r1i1p1_T2M_tasmax_1999-2000.jpg
  doc/sphinx/source/recipes/figures/toymodel/synthetic_CMIP5_bcc-csm1-1_Amon_rcp45_r1i1p1_psl_2051-2060.jpg
  doc/sphinx/source/recipes/recipe_toymodel.rst
  esmvaltool/diag_scripts/magic_bsc/toymodel.r
  esmvaltool/recipes/recipe_toymodel.yml
Labels: diagnostic

#1209 Improving Modes Of Variability recipe
  esmvaltool/diag_scripts/magic_bsc/weather_regime.r
  esmvaltool/recipes/recipe_modes_of_variability.yml
Labels: diagnostic

#1217 Sea mask and Timeseries plot added
  esmvaltool/diag_scripts/magic_bsc/extreme_spells.r
  esmvaltool/recipes/recipe_heatwaves_coldwaves.yml
Labels: diagnostic

#1146 V2 dev cmorizer docu
  doc/sphinx/source/esmvaldiag/observations.rst
Labels: documentation, paper

#1179 Added CMORizer for LAI3g
  doc/sphinx/source/getting_started/inputdata.rst
  esmvaltool/cmorizers/obs/cmor_config/LAI3g.yml
  esmvaltool/cmorizers/obs/cmorize_obs_lai3g.py
  esmvaltool/cmorizers/obs/utilities.py
  esmvaltool/config-references.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
Labels: observations
