Repository ESMValGroup/ESMValTool, pull requests merged in 2019-12, with the labels that each got.

#1346 eWaterCycle: Add recipe to prepare input for WFlow
  doc/sphinx/source/recipes/recipe_hydrology.rst
  esmvaltool/diag_scripts/hydrology/__init__.py
  esmvaltool/diag_scripts/hydrology/derive_evspsblpot.py
  esmvaltool/diag_scripts/hydrology/marrmot.py
  esmvaltool/diag_scripts/hydrology/wflow.py
  esmvaltool/recipes/hydrology/recipe_wflow.yml
Labels: diagnostic, eWaterCycle

#1459 Cmorizer for PHC3.0
  doc/sphinx/source/getting_started/inputdata.rst
  esmvaltool/cmorizers/obs/cmor_config/PHC.yml
  esmvaltool/cmorizers/obs/cmorize_obs_phc.py
  esmvaltool/config-references.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
  meta.yaml
  setup.py
Labels: observations

#1462 Pinning cdo to a fully functional version
  environment.yml
  meta.yaml
Labels: installation

#1466 Added recipe anav13jclim.yml
  doc/sphinx/source/recipes/figures/anav13jclim/cSoil-cVeg_scatter_global.png
  doc/sphinx/source/recipes/figures/anav13jclim/diag_grading_pr-global_to_diag_grading_gpp-global_RMSD.png
  doc/sphinx/source/recipes/figures/anav13jclim/gpp_cycle_nh.png
  doc/sphinx/source/recipes/figures/anav13jclim/gpp_errorbar_trop.png
  doc/sphinx/source/recipes/figures/anav13jclim/nbp_evolution_global.png
  doc/sphinx/source/recipes/figures/anav13jclim/tas_global.png
  doc/sphinx/source/recipes/figures/anav13jclim/tos_scatter_global.png
  doc/sphinx/source/recipes/figures/flato13ipcc/fig-9-26.png
  doc/sphinx/source/recipes/figures/flato13ipcc/fig-9-27.png
  doc/sphinx/source/recipes/figures/flato13ipcc/fig-9-42a.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_anav13jclim.rst
  doc/sphinx/source/recipes/recipe_flato13ipcc.rst
  doc/sphinx/source/recipes/recipe_wenzel16jclim.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/carbon_cycle/main.ncl
  esmvaltool/diag_scripts/carbon_cycle/mvi.ncl
  esmvaltool/diag_scripts/carbon_cycle/two_variables.ncl
  esmvaltool/diag_scripts/perfmetrics/cycle_latlon.ncl
  esmvaltool/diag_scripts/shared/plot/scatterplot.ncl
  esmvaltool/diag_scripts/shared/plot/xy_line.ncl
  esmvaltool/diag_scripts/shared/scaling.ncl
  esmvaltool/interface_scripts/data_handling.ncl
  esmvaltool/interface_scripts/interface.ncl
  esmvaltool/recipes/examples/recipe_preprocessor_derive_test.yml
  esmvaltool/recipes/recipe_anav13jclim.yml
  esmvaltool/recipes/recipe_flato13ipcc.yml
Labels: diagnostic

#1453 Fixed ECS calculation when no input data is given
  esmvaltool/diag_scripts/climate_metrics/ecs.py
Labels: bug

#1457 Merra2
  doc/sphinx/source/getting_started/inputdata.rst
  esmvaltool/cmorizers/obs/cmor_config/MERRA2.yml
  esmvaltool/cmorizers/obs/cmorize_obs_merra2.py
  esmvaltool/cmorizers/obs/download_scripts/download_merra2.sh
  esmvaltool/config-references.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
Labels: observations

#1433 added types of data to README
  README.md
Labels: documentation

#1370 Add diagnostic albedolandcover
  doc/sphinx/source/recipes/figures/albedolandcover/MPI-ESM-LR_albedo_change_from_tree_to_crop-grass.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_albedolandcover.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/landcover/albedolandcover.py
  esmvaltool/recipes/recipe_albedolandcover.yml
Labels: diagnostic

#1240 Julia example
  doc/sphinx/source/esmvaldiag/new_diagnostic.rst
  esmvaltool/diag_scripts/examples/diagnostic.jl
  esmvaltool/diag_scripts/shared/external.jl
  esmvaltool/install/Julia/julia_requirements.txt
  esmvaltool/install/Julia/setup.jl
  esmvaltool/recipes/examples/recipe_julia.yml
Labels: enhancement

#1471 Fix making latitude increasing for ERA5
  esmvaltool/cmorizers/obs/cmorize_obs_era5.py
Labels: observations
