Repository ESMValGroup/ESMValTool, pull requests merged in 2019-06, with the labels that each got.

#1001 Reduce memory use of area preprocessors
  esmvaltool/preprocessor/_area.py
Labels: backend, enhancement

#1126 Restructure documentation
  doc/sphinx/source/developer_guide2/index.rst
  doc/sphinx/source/esmvalcore/config.inc
  doc/sphinx/source/esmvalcore/datafinder.inc
  doc/sphinx/source/esmvalcore/index.rst
  doc/sphinx/source/esmvalcore/preprocessor.inc
  doc/sphinx/source/esmvalcore/recipe.inc
  doc/sphinx/source/esmvaldiag/config_developer.inc
  doc/sphinx/source/esmvaldiag/first_diagnostic.inc
  doc/sphinx/source/esmvaldiag/git_repository.inc
  doc/sphinx/source/esmvaldiag/index.rst
  doc/sphinx/source/esmvaldiag/new_diagnostic.inc
  doc/sphinx/source/esmvaldiag/observations.inc
  doc/sphinx/source/esmvaldiag/porting.inc
  doc/sphinx/source/getting_started/config_user.inc
  doc/sphinx/source/getting_started/index.rst
  doc/sphinx/source/getting_started/inputdata.inc
  doc/sphinx/source/getting_started/install.inc
  doc/sphinx/source/getting_started/outputdata.inc
  doc/sphinx/source/getting_started/running.inc
  doc/sphinx/source/index.rst
  doc/sphinx/source/known_issues.rst
  doc/sphinx/source/preface.rst
  doc/sphinx/source/preface/architecture.inc
  doc/sphinx/source/preface/core_team.inc
  doc/sphinx/source/preface/index.rst
  doc/sphinx/source/preface/intro.inc
  doc/sphinx/source/preface/license.inc
  doc/sphinx/source/preface/objectives.inc
  doc/sphinx/source/user_guide2/dirstruct.inc
  doc/sphinx/source/user_guide2/index.rst
  doc/sphinx/source/user_guide2/recipe.inc
Labels: documentation

#1092 Improving public functions documentation with numpy-style documentation
  esmvalcore/preprocessor/_area.py
  esmvalcore/preprocessor/_multimodel.py
  esmvalcore/preprocessor/_regrid.py
  esmvalcore/preprocessor/_time.py
  esmvalcore/preprocessor/_volume.py
Labels: Workshop / Paper, documentation

#1025 Mask preprocessor module cleanup and add tests
  doc/sphinx/source/esmvalcore/preprocessor.inc
  esmvalcore/cmor/check.py
  esmvalcore/preprocessor/_mask.py
  tests/integration/preprocessor/_mask/test_mask.py
  tests/unit/preprocessor/_mask/test_mask.py
Labels: Workshop / Paper, documentation, preprocessor

#1136 Removed unused NCL graphical scripts
  esmvaltool/diag_scripts/clouds/clouds_taylor.ncl
  esmvaltool/diag_scripts/shared/plot/GO_panels.ncl
  esmvaltool/diag_scripts/shared/plot/aux_plotting.ncl
  esmvaltool/diag_scripts/shared/plot/misc_function.ncl
  esmvaltool/diag_scripts/shared/plot/mjo_level1.ncl
  esmvaltool/diag_scripts/shared/plot/mjo_level2.ncl
  esmvaltool/diag_scripts/shared/plot/monsoon_domain_panels.ncl
  esmvaltool/diag_scripts/shared/plot/monsoon_panels.ncl
  esmvaltool/diag_scripts/shared/plot/taylor_diagram_less_hardcoded.ncl
  esmvaltool/diag_scripts/shared/plot/taylor_plot.ncl
  esmvaltool/diag_scripts/shared/plot/vector_scalar_map_polar.ncl
Labels: Workshop / Paper

#1123 Renaming the area and volume average preprocessors
  doc/sphinx/source/esmvalcore/preprocessor.inc
  doc/sphinx/source/recipes/recipe_oceans.rst
  esmvalcore/_recipe.py
  esmvalcore/preprocessor/__init__.py
  esmvalcore/preprocessor/_area.py
  esmvalcore/preprocessor/_volume.py
  esmvaltool/diag_scripts/examples/my_little_diagnostic.py
  esmvaltool/diag_scripts/ocean/diagnostic_profiles.py
  esmvaltool/diag_scripts/ocean/diagnostic_timeseries.py
  esmvaltool/recipes/recipe_cox18nature.yml
  esmvaltool/recipes/recipe_ecs.yml
  esmvaltool/recipes/recipe_flato13ipcc.yml
  esmvaltool/recipes/recipe_ocean_bgc.yml
  esmvaltool/recipes/recipe_ocean_example.yml
  tests/integration/test_recipe.py
  tests/unit/preprocessor/_area/test_area.py
  tests/unit/preprocessor/_volume/test_volume.py
Labels: documentation

#1140 Obs cmorizer tool - added warnings for missing obs data
  esmvaltool/utils/cmorizers/obs/cmorize_obs.py
Labels: enhancement

#1151 Update overview picture
  doc/sphinx/source/figures/schematic.png
Labels: documentation

#1153 Update utilities.py
  esmvaltool/utils/cmorizers/obs/utilities.py
Labels: observations

#1145 Added Gallery to documentation
  doc/sphinx/source/esmvalcore/preprocessor.inc
  doc/sphinx/source/gallery.rst
  doc/sphinx/source/generate_gallery.py
  doc/sphinx/source/getting_started/index.rst
  doc/sphinx/source/index.rst
  doc/sphinx/source/recipes/figures/cox18nature/emergent_relationship_HadCRUT4.png
  doc/sphinx/source/recipes/figures/cox18nature/pdf_HadCRUT4.png
  doc/sphinx/source/recipes/figures/cox18nature/temperature_anomaly_HadCRUT4.png
  doc/sphinx/source/recipes/figures/ecs/CanESM2.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_capacity_factor.rst
  doc/sphinx/source/recipes/recipe_clouds.rst
  doc/sphinx/source/recipes/recipe_consecdrydays.rst
  doc/sphinx/source/recipes/recipe_cox18nature.rst
  doc/sphinx/source/recipes/recipe_crem.rst
  doc/sphinx/source/recipes/recipe_cvdp.rst
  doc/sphinx/source/recipes/recipe_ecs.rst
  doc/sphinx/source/recipes/recipe_ensclus.rst
  doc/sphinx/source/recipes/recipe_extreme_events.rst
  doc/sphinx/source/recipes/recipe_flato13ipcc.rst
  doc/sphinx/source/recipes/recipe_hyint.rst
  doc/sphinx/source/recipes/recipe_landcover.rst
  doc/sphinx/source/recipes/recipe_miles.rst
  doc/sphinx/source/recipes/recipe_quantilebias.rst
  doc/sphinx/source/recipes/recipe_rainfarm.rst
  doc/sphinx/source/recipes/recipe_runoff_et.rst
  doc/sphinx/source/recipes/recipe_shapeselect.rst
  doc/sphinx/source/recipes/recipe_smpi.rst
  doc/sphinx/source/recipes/recipe_spei.rst
  doc/sphinx/source/recipes/recipe_template.rst.template
  doc/sphinx/source/recipes/recipe_thermodyn_diagtool.rst
  doc/sphinx/source/recipes/recipe_zmnam.rst
  esmvaltool/recipes/recipe_ecs.yml
Labels: documentation, paper

#1129 Legend modification and sea mask added
  doc/sphinx/source/recipes/figures/capacity_factor/capacity_factor_IPSL-CM5A-LR_1980-2005.png
  doc/sphinx/source/recipes/figures/capacity_factor_IPSL-CM5A-MR_2021-2050.png
  doc/sphinx/source/recipes/recipe_capacity_factor.rst
  esmvaltool/diag_scripts/magic_bsc/capacity_factor.r
  esmvaltool/recipes/recipe_capacity_factor.yml
Labels: diagnostic

#1152 Documentation: convert .inc to .rst
  .circleci/config.yml
  .gitignore
  doc/sphinx/source/conf.py
  doc/sphinx/source/esmvalcore/datafinder.inc
  doc/sphinx/source/esmvalcore/preprocessor.inc
  doc/sphinx/source/esmvaldiag/config_developer.inc
  doc/sphinx/source/esmvaldiag/first_diagnostic.inc
  doc/sphinx/source/esmvaldiag/git_repository.inc
  doc/sphinx/source/esmvaldiag/new_diagnostic.inc
  doc/sphinx/source/esmvaldiag/observations.inc
  doc/sphinx/source/gallery.rst
  doc/sphinx/source/generate_gallery.py
  doc/sphinx/source/getting_started/config_user.inc
  doc/sphinx/source/getting_started/inputdata.inc
  doc/sphinx/source/getting_started/install.inc
  doc/sphinx/source/getting_started/outputdata.inc
  doc/sphinx/source/getting_started/running.inc
  doc/sphinx/source/preface/architecture.inc
  doc/sphinx/source/preface/core_team.inc
  doc/sphinx/source/preface/intro.inc
  doc/sphinx/source/preface/license.inc
  doc/sphinx/source/preface/objectives.inc
  doc/sphinx/source/recipes/figures/capacity_factor/capacity_factor_IPSL-CM5A-MR_2021-2050.png
  doc/sphinx/source/recipes/recipe_capacity_factor.rst
  doc/sphinx/source/requirements.txt
Labels: documentation, enhancement

#1128 Bringing in new Documentation
  doc/sphinx/source/esmvalcore/recipe.inc
  doc/sphinx/source/esmvaldiag/new_diagnostic.inc
  doc/sphinx/source/getting_started/config_user.inc
  doc/sphinx/source/getting_started/outputdata.inc
Labels: documentation, paper

#807 Ar6 color
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_blue_multiple_hue_non-diverging_03.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_blue_multiple_hue_non-diverging_04.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_blue_multiple_hue_non-diverging_05.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_blue_non-diverging_03.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_blue_non-diverging_04.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_blue_non-diverging_05.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_green_multiple_hue_non-diverging_03.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_green_multiple_hue_non-diverging_04.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_green_multiple_hue_non-diverging_05.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_green_non-diverging_03.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_green_non-diverging_04.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_green_non-diverging_05.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_line_01.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_line_02.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_line_03.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_line_04.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_line_05.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_line_06.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_line_shading.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_precipitation_05.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_precipitation_06.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_precipitation_07.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_precipitation_08.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_precipitation_09.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_precipitation_10.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_precipitation_11.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_purple_multiple_hue_non-diverging_03.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_purple_multiple_hue_non-diverging_04.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_purple_multiple_hue_non-diverging_05.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_purple_non-diverging_03.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_purple_non-diverging_04.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_purple_non-diverging_05.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_rcp_line.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_rcp_shading.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_red_multiple_hue_non-diverging_03.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_red_multiple_hue_non-diverging_04.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_red_multiple_hue_non-diverging_05.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_red_non-diverging_03.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_red_non-diverging_04.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_red_non-diverging_05.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_temperature_05.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_temperature_06.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_temperature_07.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_temperature_08.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_temperature_09.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_temperature_10.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_temperature_11.rgb
  esmvaltool/utils/color_tables/__init__.py
  esmvaltool/utils/color_tables/show_color_tables.py
  meta.yaml
  setup.py
Labels: standards

#1135 First go at preprocessor documentation
  doc/sphinx/source/esmvalcore/preprocessor.inc
Labels: documentation, paper
