Repository ESMValGroup/ESMValTool, pull requests merged in 2019-03, with the labels that each got.

#818 Adding a download path into config-user.yml
  doc/sphinx/source/developer_guide2/config_developer.inc
  doc/sphinx/source/developer_guide2/index.rst
  doc/sphinx/source/recipes/recipe_oceans.rst
  doc/sphinx/source/user_guide2/config.inc
  esmvaltool/_config.py
  esmvaltool/_recipe.py
  esmvaltool/config-user.yml
  esmvaltool/diag_scripts/ocean/diagnostic_maps.py
  esmvaltool/diag_scripts/ocean/diagnostic_seaice.py
Labels: enhancement

#891 Update recipe_zmnam.rst
  doc/sphinx/source/recipes/recipe_zmnam.rst
Labels: documentation

#879 fix in project_style.ncl
  esmvaltool/diag_scripts/shared/plot/style.ncl
Labels: bug

#710 Magic bsc
  doc/sphinx/source/developer_guide2/new_diagnostic.inc
  doc/sphinx/source/recipes/figures/capacity_factor/capacity_factor_IPSL-CM5A-LR_1980-2005.png
  doc/sphinx/source/recipes/figures/combined_climate_extreme_index/t90p_IPSL-CM5A-LR_rcp85_2020_2040.png
  doc/sphinx/source/recipes/figures/diurnal_temp_index/rcp85_diurnal.png
  doc/sphinx/source/recipes/figures/heatwaves/tasmax_extreme_spell_durationsummer_IPSL-CM5A-LR_rcp85_2020_2040.png
  doc/sphinx/source/recipes/figures/modes_of_variability/DJF-psl_observed_regimes.png
  doc/sphinx/source/recipes/figures/multimodel_products/tas_JUN_multimodel-anomaly_2006_2099_1961_1990.png
  doc/sphinx/source/recipes/figures/toymodel/synthetic_CMIP5_IPSL-CM5A-LR_day_historical_r1i1p1_T2M_tasmax_1999-2000.jpg
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_capacity_factor.rst
  doc/sphinx/source/recipes/recipe_combined_climate_extreme_index.rst
  doc/sphinx/source/recipes/recipe_diurnal_temperature_index.rst
  doc/sphinx/source/recipes/recipe_ensclus.rst
  doc/sphinx/source/recipes/recipe_heatwaves_coldwaves.rst
  doc/sphinx/source/recipes/recipe_modes_of_variability.rst
  doc/sphinx/source/recipes/recipe_multimodel_products.rst
  doc/sphinx/source/recipes/recipe_oceans.rst
  doc/sphinx/source/recipes/recipe_toymodel.rst
  doc/sphinx/source/user_guide2/install.inc
  environment.yml
  esmvaltool/config-developer.yml
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/magic_bsc/PC.r
  esmvaltool/diag_scripts/magic_bsc/PowerCurves/Enercon_E70_2.3MW.txt
  esmvaltool/diag_scripts/magic_bsc/PowerCurves/Gamesa_G80_2.0MW.txt
  esmvaltool/diag_scripts/magic_bsc/PowerCurves/Gamesa_G87_2.0MW.txt
  esmvaltool/diag_scripts/magic_bsc/PowerCurves/Vestas_V100_2.0MW.txt
  esmvaltool/diag_scripts/magic_bsc/PowerCurves/Vestas_V110_2.0MW.txt
  esmvaltool/diag_scripts/magic_bsc/RegimesAssign.r
  esmvaltool/diag_scripts/magic_bsc/WeatherRegime.r
  esmvaltool/diag_scripts/magic_bsc/capacity_factor.r
  esmvaltool/diag_scripts/magic_bsc/combined_indices_wp6.r
  esmvaltool/diag_scripts/magic_bsc/diurnal_temp_index.r
  esmvaltool/diag_scripts/magic_bsc/extreme_index.r
  esmvaltool/diag_scripts/magic_bsc/extreme_spells.r
  esmvaltool/diag_scripts/magic_bsc/multimodel_products.r
  esmvaltool/diag_scripts/magic_bsc/toymodel.r
  esmvaltool/diag_scripts/magic_bsc/weather_regime.r
  esmvaltool/install/R/r_requirements.txt
  esmvaltool/recipes/recipe_capacity_factor_wp7.yml
  esmvaltool/recipes/recipe_combined_indices_wp6.yml
  esmvaltool/recipes/recipe_diurnal_temperature_index_wp7.yml
  esmvaltool/recipes/recipe_extreme_index_wp7.yml
  esmvaltool/recipes/recipe_heatwaves_coldwaves_wp7.yml
  esmvaltool/recipes/recipe_modes_of_variability_wp4.yml
  esmvaltool/recipes/recipe_multimodel_products_wp5.yml
  esmvaltool/recipes/recipe_toymodel_wp4.yml
Labels: MAGIC, diagnostic

#899 Search for custom cmor table if OBS and table not found
  esmvaltool/config-developer.yml
Labels: standards

#909 Update recipe_cvdp.rst
  doc/sphinx/source/recipes/recipe_cvdp.rst
Labels: MAGIC

#910 Update recipe_perfmetrics.rst
  doc/sphinx/source/recipes/recipe_perfmetrics.rst
Labels: MAGIC

#911 Update recipe_ensclus.rst
  doc/sphinx/source/recipes/recipe_ensclus.rst
Labels: MAGIC

#700 Magic watersector
  doc/sphinx/source/recipes/figures/spei/histogram_spei.png
  doc/sphinx/source/recipes/figures/spei/histogram_spi.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_consecdrydays.rst
  doc/sphinx/source/recipes/recipe_shapeselect.rst
  doc/sphinx/source/recipes/recipe_spei.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/droughtindex/diag_cdd.py
  esmvaltool/diag_scripts/droughtindex/diag_spei.r
  esmvaltool/diag_scripts/droughtindex/diag_spi.r
  esmvaltool/diag_scripts/shapeselect/diag_shapeselect.py
  esmvaltool/diag_scripts/shapeselect/testdata/Elbe.dbf
  esmvaltool/diag_scripts/shapeselect/testdata/Elbe.prj
  esmvaltool/diag_scripts/shapeselect/testdata/Elbe.shp
  esmvaltool/diag_scripts/shapeselect/testdata/Elbe.shx
  esmvaltool/diag_scripts/shapeselect/testdata/MotalaStrom.dbf
  esmvaltool/diag_scripts/shapeselect/testdata/MotalaStrom.prj
  esmvaltool/diag_scripts/shapeselect/testdata/MotalaStrom.shp
  esmvaltool/diag_scripts/shapeselect/testdata/MotalaStrom.shx
  esmvaltool/diag_scripts/shapeselect/testdata/Thames.dbf
  esmvaltool/diag_scripts/shapeselect/testdata/Thames.prj
  esmvaltool/diag_scripts/shapeselect/testdata/Thames.shp
  esmvaltool/diag_scripts/shapeselect/testdata/Thames.shx
  esmvaltool/diag_scripts/shapeselect/testdata/multicatchment.dbf
  esmvaltool/diag_scripts/shapeselect/testdata/multicatchment.prj
  esmvaltool/diag_scripts/shapeselect/testdata/multicatchment.shp
  esmvaltool/diag_scripts/shapeselect/testdata/multicatchment.shx
  esmvaltool/diag_scripts/shapeselect/testdata/testfile.dbf
  esmvaltool/diag_scripts/shapeselect/testdata/testfile.prj
  esmvaltool/diag_scripts/shapeselect/testdata/testfile.shp
  esmvaltool/diag_scripts/shapeselect/testdata/testfile.shx
  esmvaltool/install/R/r_requirements.txt
  esmvaltool/recipes/recipe_consecdrydays.yml
  esmvaltool/recipes/recipe_shapeselect.yml
  esmvaltool/recipes/recipe_spei.yml
  meta.yaml
  setup.py
  tests/unit/check_r_code.R
Labels: MAGIC, diagnostic

#908 Update preprocessor.inc
  doc/sphinx/source/user_guide2/preprocessor.inc
Labels: MAGIC

#875 Version2 development preprocessor nomenclature 847
  doc/sphinx/source/user_guide2/preprocessor.inc
  esmvaltool/preprocessor/__init__.py
  esmvaltool/preprocessor/_area.py
  esmvaltool/preprocessor/_time.py
  esmvaltool/preprocessor/_volume.py
  esmvaltool/recipes/recipe_ocean_bgc.yml
  esmvaltool/recipes/recipe_ocean_example.yml
  tests/unit/preprocessor/_area/__init__.py
  tests/unit/preprocessor/_area/test_area.py
  tests/unit/preprocessor/_time/__init__.py
  tests/unit/preprocessor/_time/test_time.py
  tests/unit/preprocessor/_time_area/__init__.py
  tests/unit/preprocessor/_volume/__init__.py
  tests/unit/preprocessor/_volume/test_volume.py
Labels: backend

#900 improved version of python cmorization utilities
  esmvaltool/utils/cmorizers/obs/utilities.py
Labels: backend

#905 Small fix to add also ps and epsi plot types for Miles
  esmvaltool/diag_scripts/miles/basis_functions.R
Labels: MAGIC, diagnostic

#930 Fix NCEP cmorizer
  esmvaltool/utils/cmorizers/obs/cmorize_obs_NCEP.ncl
Labels: standards

#935 Bugfix: segmentation violation in NCL provenance function log_provenance
  esmvaltool/interface_scripts/logging.ncl
Labels: bug

#921 Fix handling of dtype in irregular regridding.
  esmvaltool/preprocessor/_mapping.py
  esmvaltool/preprocessor/_regrid_esmpy.py
  tests/unit/preprocessor/_mapping/test_mapping.py
  tests/unit/preprocessor/_regrid_esmpy/test_regrid_esmpy.py
Labels: backend

#917 Removal of Python 2 test support
  .circleci/config.yml
  conda_build_config.yaml
  doc/sphinx/source/user_guide2/install.inc
  esmvaltool/_main.py
  esmvaltool/diag_scripts/autoassess/_plot_mo_metrics.py
  esmvaltool/preprocessor/_mask.py
  esmvaltool/preprocessor/_regrid.py
  setup.py
  tests/__init__.py
  tests/integration/cmor/_fixes/CMIP5/test_CCSM4.py
  tests/integration/cmor/_fixes/CMIP5/test_inmcm4.py
  tests/integration/cmor/_fixes/test_fix.py
  tests/integration/preprocessor/_io/test_cleanup.py
  tests/integration/preprocessor/_io/test_concatenate.py
  tests/integration/preprocessor/_io/test_load.py
  tests/integration/preprocessor/_io/test_save.py
  tests/integration/preprocessor/_mask/test_mask.py
  tests/integration/preprocessor/_regrid/test_extract_levels.py
  tests/integration/preprocessor/_regrid/test_get_cmor_levels.py
  tests/integration/preprocessor/_regrid/test_get_file_levels.py
  tests/integration/preprocessor/_regrid/test_regrid.py
  tests/integration/test_recipe.py
  tests/system/data_simulator.py
  tests/system/esmvaltool_testlib.py
  tests/unit/cmor/test_cmor_check.py
  tests/unit/cmor/test_fix.py
  tests/unit/diag_scripts/test_cvdp.py
  tests/unit/preprocessor/_area/test_area.py
  tests/unit/preprocessor/_derive/test_p_level_widths.py
  tests/unit/preprocessor/_mapping/test_mapping.py
  tests/unit/preprocessor/_mask/test_mask.py
  tests/unit/preprocessor/_regrid/__init__.py
  tests/unit/preprocessor/_regrid/test__create_cube.py
  tests/unit/preprocessor/_regrid/test__stock_cube.py
  tests/unit/preprocessor/_regrid/test_extract_levels.py
  tests/unit/preprocessor/_regrid/test_regrid.py
  tests/unit/preprocessor/_regrid_esmpy/test_regrid_esmpy.py
  tests/unit/preprocessor/_time/test_time.py
  tests/unit/preprocessor/_volume/test_volume.py
  tests/unit/test_lint.py
Labels: enhancement

#904 Cmorizer for GHCN pr measurements
  doc/sphinx/source/user_guide2/observations.inc
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/utils/cmorizers/obs/cmorize_obs_GHCN.ncl
Labels: standards

#898 Version2 clouds provenance
  esmvaltool/diag_scripts/clouds/clouds.ncl
  esmvaltool/diag_scripts/clouds/clouds_bias.ncl
  esmvaltool/diag_scripts/clouds/clouds_interannual.ncl
  esmvaltool/diag_scripts/clouds/clouds_ipcc.ncl
  esmvaltool/diag_scripts/clouds/clouds_taylor.ncl
  esmvaltool/recipes/recipe_clouds_bias.yml
  esmvaltool/recipes/recipe_clouds_ipcc.yml
  esmvaltool/recipes/recipe_flato13ipcc.yml
  esmvaltool/recipes/recipe_lauer13jclim.yml
Labels: diagnostic, enhancement

#872 CREM updates for CMIP6
  doc/sphinx/source/recipes/recipe_crem.rst
  esmvaltool/diag_scripts/crem/ww09_esmvaltool.py
  esmvaltool/recipes/recipe_williams09climdyn_CREM.yml
Labels: diagnostic, enhancement

#928 Add log messages with task name
  esmvaltool/_task.py
Labels: enhancement

#955 Update recipe_spei.rst
  doc/sphinx/source/recipes/recipe_spei.rst
Labels: diagnostic

#936 Stable and up-to-date conda environment March 2019
  .circleci/config.yml
  environment.yml
  esmvaltool/install/R/r_requirements.txt
  meta.yaml
Labels: installation

#954 Update recipe_cvdp.rst
  doc/sphinx/source/recipes/recipe_cvdp.rst
Labels: diagnostic

#964 Add CDS cmorizer
  doc/sphinx/source/user_guide2/observations.inc
  esmvaltool/cmor/tables/custom/CMOR_xch4.dat
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/utils/cmorizers/obs/cmorize_obs_CDS-XCH4.ncl
Labels: standards

#770 Version2 landcover
  doc/sphinx/source/recipes/figures/landcover/area_treeFrac.png
  doc/sphinx/source/recipes/figures/landcover/bias_CMIP5_MPI-ESM-LR_rcp85_r1i1p1.png
  doc/sphinx/source/recipes/figures/landcover/frac_grassFrac.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_landcover.rst
  esmvaltool/cmor/_fixes/CMIP5/inmcm4.py
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/landcover/landcover.py
  esmvaltool/recipes/recipe_landcover.yml
Labels: diagnostic

#965 Version 2: Environment fix
  .circleci/config.yml
  conda_build_config.yaml
  environment.yml
  meta.yaml
  setup.py
Labels: installation

#750 MAGIC WP4 quantilebias
  doc/sphinx/source/recipes/recipe_quantilebias.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/quantilebias/quantilebias.R
  esmvaltool/install/R/r_requirements.txt
  esmvaltool/recipes/recipe_quantilebias.yml
Labels: MAGIC, diagnostic

#848 Adding the annual average preprocessor
  doc/sphinx/source/user_guide2/preprocessor.inc
  esmvaltool/preprocessor/__init__.py
  esmvaltool/preprocessor/_area.py
  esmvaltool/preprocessor/_time.py
  esmvaltool/preprocessor/_volume.py
  esmvaltool/recipes/recipe_ocean_bgc.yml
  tests/unit/preprocessor/_area/test_area.py
  tests/unit/preprocessor/_time/test_time.py
Labels: backend

#962 Update CMIP6 cmor tables from PCMDI at DReq 01.00.30
  esmvaltool/cmor/tables/cmip6/README.md
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_3hr.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_6hrLev.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_6hrPlev.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_6hrPlevPt.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_AERday.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_AERhr.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_AERmon.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_AERmonZ.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_Amon.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_CF3hr.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_CFday.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_CFmon.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_CFsubhr.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_CV.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_E1hr.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_E1hrClimMon.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_E3hr.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_E3hrPt.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_E6hrZ.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_Eday.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_EdayZ.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_Efx.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_Emon.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_EmonZ.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_Esubhr.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_Eyr.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_IfxAnt.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_IfxGre.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_ImonAnt.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_ImonGre.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_IyrAnt.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_IyrGre.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_LImon.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_Lmon.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_Oclim.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_Oday.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_Odec.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_Ofx.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_Omon.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_Oyr.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_SIday.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_SImon.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_coordinate.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_day.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_formula_terms.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_fx.json
  esmvaltool/cmor/tables/cmip6/Tables/CMIP6_grids.json
Labels: standards

#956 More variables in ERA-Interim cmorizer
  doc/sphinx/source/user_guide2/observations.inc
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/utils/cmorizers/obs/cmorize_obs_ERA-Interim.ncl
Labels: standards

#654 initial version of Julia support
  .circleci/config.yml
  CONTRIBUTING.md
  README.md
  doc/sphinx/source/user_guide2/install.inc
  environment.yml
  esmvaltool/_task.py
  esmvaltool/install/Julia/julia_requirements.txt
  esmvaltool/install/Julia/setup.jl
  language_support.sh
  meta.yaml
  tests/integration/test_diagnostic_run.py
Labels: enhancement, installation

#948 Crescendo wp5 diag co2
  doc/sphinx/source/recipes/recipe_oceans.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/ocean/diagnostic_maps.py
  esmvaltool/diag_scripts/ocean/diagnostic_model_vs_obs.py
  esmvaltool/diag_scripts/ocean/diagnostic_tools.py
  esmvaltool/recipes/recipe_ocean_Landschutzer2016.yml
Labels: diagnostic

#989 Fix for use of fx file in variable derivation
  esmvaltool/_recipe.py
  esmvaltool/preprocessor/_derive/__init__.py
  tests/integration/preprocessor/_derive/test_interface.py
  tests/integration/test_recipe.py
Labels: bug

#939 Adapt perfmetrics recipe for cds data situation
  esmvaltool/recipes/recipe_perfmetrics_CMIP5_4cds.yml
Labels: MAGIC

#1000 Reduce memory usage in cmor fix
  esmvaltool/cmor/check.py
  esmvaltool/cmor/fix.py
  tests/unit/cmor/test_cmor_check.py
Labels: backend, enhancement

#867 PR to fix a number of small issues
  doc/sphinx/source/user_guide2/preprocessor.inc
  esmvaltool/_recipe.py
  esmvaltool/preprocessor/__init__.py
  esmvaltool/preprocessor/_regrid.py
  esmvaltool/preprocessor/_time.py
  tests/integration/preprocessor/_regrid/test_get_file_levels.py
  tests/integration/test_recipe.py
  tests/unit/preprocessor/_time/test_time.py
Labels: enhancement
