Repository ESMValGroup/ESMValTool, pull requests merged in 2019-10, with the labels that each got.

#1330 Update getting started docs for new users
  doc/sphinx/source/gensidebar.py
  doc/sphinx/source/getting_started/config_user.rst
  doc/sphinx/source/getting_started/index.rst
  doc/sphinx/source/getting_started/inputdata.rst
  doc/sphinx/source/getting_started/install.rst
  doc/sphinx/source/getting_started/outputdata.rst
  doc/sphinx/source/getting_started/running.rst
  esmvaltool/recipes/examples/recipe_python.yml
Labels: documentation

#1064 Add piomas sit reanalysis
  doc/sphinx/source/getting_started/inputdata.rst
  esmvaltool/cmorizers/obs/cmor_config/PIOMAS.yml
  esmvaltool/cmorizers/obs/cmorize_obs_piomas.py
  esmvaltool/config-references.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
Labels: PRIMAVERA, enhancement, observations, workshop

#1090 Use workdir files for provenance
  esmvaltool/diag_scripts/perfmetrics/collect.ncl
  esmvaltool/diag_scripts/perfmetrics/main.ncl
Labels: diagnostic, workshop

#1310 Crescendo collins13ipcc
  doc/sphinx/source/recipes/figures/collins13ipcc/collins_fig_1.png
  doc/sphinx/source/recipes/figures/collins13ipcc/collins_fig_2.png
  doc/sphinx/source/recipes/figures/collins13ipcc/collins_fig_3.png
  doc/sphinx/source/recipes/figures/collins13ipcc/collins_fig_4.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_collins13ipcc.rst
  esmvaltool/diag_scripts/ipcc_ar5/ch12_calc_IAV_for_stippandhatch.ncl
  esmvaltool/diag_scripts/ipcc_ar5/ch12_calc_map_diff_mmm_stippandhatch.ncl
  esmvaltool/diag_scripts/ipcc_ar5/ch12_calc_map_diff_scaleT_mmm_stipp.ncl
  esmvaltool/diag_scripts/ipcc_ar5/ch12_calc_zonal_cont_diff_mmm_stippandhatch.ncl
  esmvaltool/diag_scripts/ipcc_ar5/ch12_map_diff_each_model_fig12-9.ncl
  esmvaltool/diag_scripts/ipcc_ar5/ch12_plot_map_diff_mmm_stipp.ncl
  esmvaltool/diag_scripts/ipcc_ar5/ch12_plot_ts_line_mean_spread.ncl
  esmvaltool/diag_scripts/ipcc_ar5/ch12_plot_zonal_diff_mmm_stipp.ncl
  esmvaltool/diag_scripts/ipcc_ar5/ch12_snw_area_change_fig12-32.ncl
  esmvaltool/diag_scripts/ipcc_ar5/ch12_ts_line_mean_spread.ncl
  esmvaltool/recipes/recipe_collins13ipcc.yml
Labels: diagnostic, workshop

#1379 Added CMORizer for NDP
  doc/sphinx/source/getting_started/inputdata.rst
  environment.yml
  esmvaltool/cmorizers/obs/cmor_config/NDP.yml
  esmvaltool/cmorizers/obs/cmorize_obs_lai3g.py
  esmvaltool/cmorizers/obs/cmorize_obs_ndp.py
  esmvaltool/config-references.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
Labels: observations

#1376 Fix on CVDP to distinguish inputdata with the same dataset name.
  esmvaltool/diag_scripts/cvdp/cvdp_wrapper.py
  esmvaltool/recipes/recipe_cvdp.yml
Labels: bug

#1368 multimodel_products (multimodel_products.r): added manual option for colorbar
  doc/sphinx/source/recipes/figures/multimodel_products/tas_JUN_multimodel-anomaly_2006_2099_1961_1990.png
  doc/sphinx/source/recipes/recipe_multimodel_products.rst
  esmvaltool/diag_scripts/magic_bsc/multimodel_products.R
  esmvaltool/recipes/recipe_multimodel_products.yml
Labels: diagnostic

#1183 Port flato13ipcc_9_14 to v2.0 (closes #429)
  doc/sphinx/source/recipes/figures/flato13ipcc/fig-9-14.png
  doc/sphinx/source/recipes/recipe_flato13ipcc.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/ipcc_ar5/ch09_fig09_14.py
  esmvaltool/recipes/recipe_flato13ipcc.yml
Labels: diagnostic, workshop

#888 Version 2 provenance ncl seaice
  doc/sphinx/source/recipes/figures/seaice/seaice_fig_1.png
  doc/sphinx/source/recipes/figures/seaice/seaice_fig_2.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_seaice.rst
  esmvaltool/diag_scripts/seaice/seaice_aux.ncl
  esmvaltool/diag_scripts/seaice/seaice_tsline.ncl
  esmvaltool/diag_scripts/shared/plot/xy_line.ncl
  esmvaltool/interface_scripts/interface.ncl
  esmvaltool/recipes/recipe_seaice.yml
Labels: documentation, workshop

#1392 Added CMORizer for HWSD
  doc/sphinx/source/getting_started/inputdata.rst
  esmvaltool/cmorizers/obs/cmor_config/HWSD.yml
  esmvaltool/cmorizers/obs/cmorize_obs_hwsd.py
  esmvaltool/cmorizers/obs/cmorize_obs_ndp.py
  esmvaltool/config-references.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
Labels: observations

#1385 Sorting and reordering documentation of the recipes
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_autoassess_stratosphere.rst
  doc/sphinx/source/recipes/recipe_collins13ipcc.rst
  doc/sphinx/source/recipes/recipe_combined_climate_extreme_index.rst
  doc/sphinx/source/recipes/recipe_combined_indices.rst
  doc/sphinx/source/recipes/recipe_cvdp.rst
  doc/sphinx/source/recipes/recipe_diurnal_temperature_index.rst
  doc/sphinx/source/recipes/recipe_ensclus.rst
  doc/sphinx/source/recipes/recipe_extreme_events.rst
  doc/sphinx/source/recipes/recipe_flato13ipcc.rst
  doc/sphinx/source/recipes/recipe_heatwaves_coldwaves.rst
  doc/sphinx/source/recipes/recipe_hydrology.rst
  doc/sphinx/source/recipes/recipe_hyint.rst
  doc/sphinx/source/recipes/recipe_landcover.rst
  doc/sphinx/source/recipes/recipe_multimodel_products.rst
  doc/sphinx/source/recipes/recipe_oceans.rst
  doc/sphinx/source/recipes/recipe_rainfarm.rst
  doc/sphinx/source/recipes/recipe_runoff_et.rst
  doc/sphinx/source/recipes/recipe_smpi.rst
  doc/sphinx/source/recipes/recipe_spei.rst
  doc/sphinx/source/recipes/recipe_thermodyn_diagtool.rst
  doc/sphinx/source/recipes/recipe_toymodel.rst
  doc/sphinx/source/recipes/recipe_validation.rst
Labels: documentation

#1399 Added CMORizer for JMA-TRANSCOM
  doc/sphinx/source/getting_started/inputdata.rst
  esmvaltool/cmorizers/obs/cmor_config/JMA-TRANSCOM.yml
  esmvaltool/cmorizers/obs/cmorize_obs_jma_transcom.py
  esmvaltool/cmorizers/obs/cmorize_obs_lai3g.py
  esmvaltool/cmorizers/obs/cmorize_obs_ndp.py
  esmvaltool/config-references.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
Labels: observations

#1381 Added examples plots for consecdrydays and shapeselect recipes.
  doc/sphinx/source/recipes/figures/consecdrydays/consec_example_freq.png
  doc/sphinx/source/recipes/figures/shapeselect/shapeselect.png
  doc/sphinx/source/recipes/recipe_consecdrydays.rst
  doc/sphinx/source/recipes/recipe_shapeselect.rst
Labels: diagnostic, documentation

#1398 Added CMORizer for GCP
  doc/sphinx/source/getting_started/inputdata.rst
  esmvaltool/cmorizers/obs/cmor_config/GCP.yml
  esmvaltool/cmorizers/obs/cmorize_obs_gcp.py
  esmvaltool/config-references.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
  meta.yaml
  setup.py
Labels: observations

#1410 Added documentation for IPCC AR5 fig 9.42a
  doc/sphinx/source/recipes/figures/flato13ipcc/fig-9-42a.png
  doc/sphinx/source/recipes/recipe_flato13ipcc.rst
  esmvaltool/recipes/recipe_flato13ipcc.yml
Labels: documentation

#1405 Removed 'field' check from diag_script
  esmvaltool/diag_scripts/ipcc_ar5/tsline.ncl
Labels: bug

#1011 Version2 emergent constraints
  doc/sphinx/source/recipes/figures/emergent_constraints/covrefl.png
  doc/sphinx/source/recipes/figures/emergent_constraints/humidx.png
  doc/sphinx/source/recipes/figures/emergent_constraints/itczidx.png
  doc/sphinx/source/recipes/figures/emergent_constraints/ltmi.png
  doc/sphinx/source/recipes/figures/emergent_constraints/shhc.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_emergent_constraints.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/emergent_constraints/ecs_cmip.cdl
  esmvaltool/diag_scripts/emergent_constraints/ecs_cmip.nc
  esmvaltool/diag_scripts/emergent_constraints/ecs_scatter.ncl
  esmvaltool/diag_scripts/shared/plot/scatterplot.ncl
  esmvaltool/recipes/recipe_ecs_scatter.yml
Labels: diagnostic, workshop

#1297 Cmorize ERA-interim in Python and add extra variables
  doc/sphinx/source/getting_started/inputdata.rst
  esmvaltool/cmorizers/obs/cmor_config/ERA-Interim.yml
  esmvaltool/cmorizers/obs/cmorize_obs_era_interim.ncl
  esmvaltool/cmorizers/obs/cmorize_obs_era_interim.py
  esmvaltool/cmorizers/obs/download_scripts/__init__.py
  esmvaltool/cmorizers/obs/download_scripts/download_era_interim.py
  esmvaltool/cmorizers/obs/utilities.py
  esmvaltool/config-references.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
  meta.yaml
  setup.py
Labels: observations, workshop

#1364 Version2 development flexible cmip era validation
  esmvaltool/diag_scripts/validation.py
  esmvaltool/recipes/recipe_validation.yml
  esmvaltool/recipes/recipe_validation_CMIP6.yml
Labels: diagnostic, enhancement

#1411 Update ERA-Interim recipes to OBS6
  esmvaltool/recipes/recipe_autoassess_stratosphere.yml
  esmvaltool/recipes/recipe_clouds_bias.yml
  esmvaltool/recipes/recipe_extreme_events.yml
  esmvaltool/recipes/recipe_flato13ipcc.yml
  esmvaltool/recipes/recipe_miles_block.yml
  esmvaltool/recipes/recipe_miles_eof.yml
  esmvaltool/recipes/recipe_miles_regimes.yml
  esmvaltool/recipes/recipe_perfmetrics_CMIP5.yml
  esmvaltool/recipes/recipe_perfmetrics_CMIP5_4cds.yml
  esmvaltool/recipes/recipe_smpi.yml
  esmvaltool/recipes/recipe_smpi_4cds.yml
  esmvaltool/recipes/recipe_spei.yml
  esmvaltool/recipes/recipe_validation_CMIP6.yml
Labels: diagnostic, observations

#1417 Repair autoassess stratosphere
  esmvaltool/diag_scripts/autoassess/_plot_mo_metrics.py
  esmvaltool/diag_scripts/autoassess/stratosphere/strat_metrics_1.py
Labels: diagnostic
