Repository ESMValGroup/ESMValTool, pull requests merged in 2019-11, with the labels that each got.

#1325 Add precipitation type to ERA5
  doc/sphinx/source/getting_started/inputdata.rst
  esmvaltool/cmorizers/obs/cmor_config/ERA5.yml
  esmvaltool/cmorizers/obs/cmorize_obs_era5.py
  esmvaltool/recipes/examples/recipe_check_obs.yml
Labels: eWaterCycle, observations, workshop

#1419 Add orography to ERA5 CMORizer
  doc/sphinx/source/getting_started/inputdata.rst
  esmvaltool/cmorizers/obs/cmor_config/ERA5.yml
  esmvaltool/cmorizers/obs/cmorize_obs_era5.py
  esmvaltool/recipes/examples/recipe_check_obs.yml
Labels: observations

#1272 Update recipes and diagnostics to use simplified fx file definition in recipe
  environment.yml
  esmvaltool/diag_scripts/autoassess/autoassess_area_base.py
  esmvaltool/diag_scripts/examples/diagnostic.ncl
  esmvaltool/diag_scripts/ocean/diagnostic_profiles.py
  esmvaltool/diag_scripts/ocean/diagnostic_timeseries.py
  esmvaltool/diag_scripts/thermodyn_diagtool/computations.py
  esmvaltool/diag_scripts/thermodyn_diagtool/fourier_coefficients.py
  esmvaltool/diag_scripts/thermodyn_diagtool/lorenz_cycle.py
  esmvaltool/diag_scripts/thermodyn_diagtool/mkthe.py
  esmvaltool/diag_scripts/thermodyn_diagtool/plot_script.py
  esmvaltool/diag_scripts/thermodyn_diagtool/provenance_meta.py
  esmvaltool/diag_scripts/thermodyn_diagtool/thermodyn_diagnostics.py
  esmvaltool/interface_scripts/data_handling.ncl
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/recipes/examples/recipe_my_personal_diagnostic.yml
  esmvaltool/recipes/examples/recipe_ncl.yml
  esmvaltool/recipes/examples/recipe_preprocessor_test.yml
  esmvaltool/recipes/recipe_autoassess_landsurface_permafrost.yml
  esmvaltool/recipes/recipe_autoassess_landsurface_snow.yml
  esmvaltool/recipes/recipe_autoassess_landsurface_surfrad.yml
  esmvaltool/recipes/recipe_ocean_Landschuetzer2016.yml
  esmvaltool/recipes/recipe_ocean_bgc.yml
  esmvaltool/recipes/recipe_thermodyn_diagtool.yml
  esmvaltool/utils/editor-enhancements/ncl-ESMValTool.el
  meta.yaml
  setup.py
Labels: diagnostic, enhancement, standards, workshop

#1362 Updates to recipe_combined_indices.yml
  doc/sphinx/source/recipes/figures/Combined_Indices_Area_Average/Nino3.4_tos_Dec-Feb_running-mean__1950-2005.png
  doc/sphinx/source/recipes/figures/Index_NAO.png
  doc/sphinx/source/recipes/recipe_combined_indices.rst
  esmvaltool/diag_scripts/magic_bsc/combined_indices.R
  esmvaltool/recipes/recipe_combined_indices.yml
Labels: diagnostic

#1276 Multimodel option for Capacity factor recipe
  esmvaltool/diag_scripts/magic_bsc/capacity_factor.R
  esmvaltool/recipes/recipe_capacity_factor.yml
Labels: diagnostic, workshop

#1229 Cmorize fluxcom gpp
  doc/sphinx/source/getting_started/inputdata.rst
  esmvaltool/cmorizers/obs/cmor_config/FLUXCOM.yml
  esmvaltool/cmorizers/obs/cmorize_obs_fluxcom.py
  esmvaltool/config-references.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
Labels: observations, workshop

#1421 New sea ice diagnostics from v1.0
  doc/sphinx/source/recipes/figures/seaice/SSIE-MEAN_vs_YOD_sic_extend_Arctic_September_1960-2100.png
  doc/sphinx/source/recipes/figures/seaice/extent_sic_Arctic_September_1960-2005.png
  doc/sphinx/source/recipes/figures/seaice/seaice_fig_1.png
  doc/sphinx/source/recipes/figures/seaice/seaice_fig_2.png
  doc/sphinx/source/recipes/figures/seaice/timeseries_rcp85.png
  doc/sphinx/source/recipes/figures/seaice/trend_sic_extend_Arctic_September_histogram.png
  doc/sphinx/source/recipes/recipe_collins13ipcc.rst
  doc/sphinx/source/recipes/recipe_flato13ipcc.rst
  doc/sphinx/source/recipes/recipe_seaice.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/seaice/seaice_aux.ncl
  esmvaltool/diag_scripts/seaice/seaice_ecs.ncl
  esmvaltool/diag_scripts/seaice/seaice_trends.ncl
  esmvaltool/diag_scripts/seaice/seaice_yod.ncl
  esmvaltool/recipes/recipe_collins13ipcc.yml
  esmvaltool/recipes/recipe_flato13ipcc.yml
  esmvaltool/recipes/recipe_seaice.yml
Labels: diagnostic

#1427 Fix captions of various sphinx example figures
  doc/sphinx/source/recipes/figures/rainfarm/rainfarm.png
  doc/sphinx/source/recipes/recipe_ensclus.rst
  doc/sphinx/source/recipes/recipe_extreme_events.rst
  doc/sphinx/source/recipes/recipe_hyint.rst
  doc/sphinx/source/recipes/recipe_miles.rst
  doc/sphinx/source/recipes/recipe_rainfarm.rst
  doc/sphinx/source/recipes/recipe_zmnam.rst
Labels: MAGIC

#1424 Figure caption added
  doc/sphinx/source/recipes/recipe_capacity_factor.rst
  doc/sphinx/source/recipes/recipe_combined_climate_extreme_index.rst
  doc/sphinx/source/recipes/recipe_diurnal_temperature_index.rst
  doc/sphinx/source/recipes/recipe_heatwaves_coldwaves.rst
  doc/sphinx/source/recipes/recipe_modes_of_variability.rst
  doc/sphinx/source/recipes/recipe_multimodel_products.rst
  doc/sphinx/source/recipes/recipe_toymodel.rst
Labels: documentation

#1275 Cmorize cds uerra reanalysis
  doc/sphinx/source/getting_started/inputdata.rst
  esmvaltool/cmorizers/obs/cmor_config/CDS-UERRA.yml
  esmvaltool/cmorizers/obs/cmorize_obs_cds_uerra.py
  esmvaltool/config-references.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
  meta.yaml
  setup.py
Labels: observations, workshop

#1387 Fix to cvdp that data are not overwritten but there for all datasets.
  doc/sphinx/source/recipes/recipe_cvdp.rst
  esmvaltool/diag_scripts/cvdp/cvdp_wrapper.py
Labels: diagnostic

#1439 [MAGIC] Enhancement of the documentation of some recipes
  doc/sphinx/source/recipes/recipe_cvdp.rst
  doc/sphinx/source/recipes/recipe_perfmetrics.rst
  doc/sphinx/source/recipes/recipe_smpi.rst
Labels: documentation

#1428 Improve quantilebias docs
  doc/sphinx/source/recipes/figures/quantilebias/quantilebias.png
  doc/sphinx/source/recipes/recipe_quantilebias.rst
  esmvaltool/diag_scripts/quantilebias/quantilebias.R
  esmvaltool/diag_scripts/quantilebias/quantilebias_functions.R
  esmvaltool/recipes/recipe_quantilebias.yml
Labels: MAGIC

#1445 Added TCR recipe and fig. 9.42b to Flato13 recipe
  doc/sphinx/source/recipes/figures/ecs/CanESM2.png
  doc/sphinx/source/recipes/figures/flato13ipcc/fig-9-42a.png
  doc/sphinx/source/recipes/figures/flato13ipcc/fig-9-42b.png
  doc/sphinx/source/recipes/figures/flato13ipcc/figure-9-42a.png
  doc/sphinx/source/recipes/figures/tcr/CanESM2.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_cox18nature.rst
  doc/sphinx/source/recipes/recipe_ecs.rst
  doc/sphinx/source/recipes/recipe_flato13ipcc.rst
  doc/sphinx/source/recipes/recipe_tcr.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/climate_metrics/create_barplot.py
  esmvaltool/diag_scripts/climate_metrics/create_scatterplot.py
  esmvaltool/diag_scripts/climate_metrics/ecs.py
  esmvaltool/diag_scripts/climate_metrics/tcr.py
  esmvaltool/diag_scripts/emergent_constraints/cox18nature.py
  esmvaltool/diag_scripts/ipcc_ar5/ch09_fig09_42a.py
  esmvaltool/diag_scripts/ipcc_ar5/ch09_fig09_42b.py
  esmvaltool/diag_scripts/shared/io.py
  esmvaltool/diag_scripts/shared/plot/styles_python/cmip5.yml
  esmvaltool/diag_scripts/shared/plot/styles_python/cmip6.yml
  esmvaltool/recipes/recipe_ecs.yml
  esmvaltool/recipes/recipe_flato13ipcc.yml
  esmvaltool/recipes/recipe_tcr.yml
  meta.yaml
  setup.py
Labels: diagnostic

#1435 Snow-albedo effect
  doc/sphinx/source/getting_started/inputdata.rst
  doc/sphinx/source/recipes/figures/flato13ipcc/fig-9-45a.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_flato13ipcc.rst
  doc/sphinx/source/recipes/recipe_snowalbedo.rst
  esmvaltool/cmorizers/obs/cmorize_obs_isccp_fh.ncl
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/emergent_constraints/snowalbedo.ncl
  esmvaltool/recipes/recipe_flato13ipcc.yml
  esmvaltool/recipes/recipe_snowalbedo.yml
Labels: diagnostic

#1448 Added diagnostic and recipe of Wenzel et al. , J. Climate 29 (2016)
  doc/sphinx/source/recipes/figures/wenzel16jclim/CMPI5_uajet-pos_rcp45_20ystep_FIG1.png
  doc/sphinx/source/recipes/figures/wenzel16jclim/CMPI5_uajet-pos_rcp45_20ystep_FIG2b.png
  doc/sphinx/source/recipes/figures/wenzel16jclim/CMPI5_uajet-pos_rcp45_20ystep_FIG3.png
  doc/sphinx/source/recipes/figures/wenzel16jclim/ta_trop250_ta_DJF_trend.png
  doc/sphinx/source/recipes/figures/wenzel16jclim/uajet-pos_rcp45_2040-2059.png
  doc/sphinx/source/recipes/figures/wenzel16jclim/uajet_H-SH_c.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_wenzel16jclim.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/austral_jet/asr.ncl
  esmvaltool/diag_scripts/austral_jet/main.ncl
  esmvaltool/diag_scripts/mder/absolute_correlation.ncl
  esmvaltool/diag_scripts/mder/regression_stepwise.ncl
  esmvaltool/diag_scripts/mder/select_for_mder.ncl
  esmvaltool/diag_scripts/shared/mder.ncl
  esmvaltool/diag_scripts/shared/plot/mder.ncl
  esmvaltool/diag_scripts/shared/plot/style.ncl
  esmvaltool/diag_scripts/shared/statistics.ncl
  esmvaltool/interface_scripts/auxiliary.ncl
  esmvaltool/interface_scripts/data_handling.ncl
  esmvaltool/interface_scripts/logging.ncl
  esmvaltool/recipes/recipe_wenzel16jclim.yml
Labels: diagnostic

#1348 Add recipe to prepare input for the MARRMoT hydrological model
  doc/sphinx/source/recipes/recipe_hydrology.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/hydrology/marrmot.py
  esmvaltool/recipes/hydrology/recipe_marrmot.yml
Labels: diagnostic, eWaterCycle
