Repository ESMValGroup/ESMValTool, pull requests merged in 2020-08, with the labels that each got.

#1776 Update command line interface documentation and add links to ESMValCore configuration documentation
  doc/sphinx/source/quickstart/configuration.rst
  doc/sphinx/source/quickstart/running.rst
Labels: documentation

#1774 Fix extreme events and extreme index ancestors
  esmvaltool/diag_scripts/extreme_events/extreme_events.R
  esmvaltool/diag_scripts/magic_bsc/extreme_index.R
Labels: bug

#1773 Correct date in output filenames of ERA5 CMORizer recipe
  esmvaltool/diag_scripts/cmorizers/era5.py
  esmvaltool/recipes/examples/recipe_check_obs.yml
Labels: bug, observations

#1777 Documentation on how to find shapefiles for hydrology recipes
  doc/sphinx/source/recipes/recipe_hydrology.rst
Labels: documentation

#1781 Add v2.0.0 release notes
  doc/sphinx/source/changelog.rst
Labels: documentation

#1783 Add pip installation instructions
  doc/sphinx/source/quickstart/installation.rst
Labels: documentation

#1787 Add installation instruction for R and Julia dependencies tot pip install
  doc/sphinx/source/quickstart/installation.rst
  setup.py
Labels: documentation

#1737 Add extra steps to diagnostic to make output of hydrology/recipe_lisflood.yml usable by the LISFLOOD model
  esmvaltool/diag_scripts/hydrology/lisflood.py
Labels: diagnostic, eWaterCycle

#1789 Fix R installation in WSL
  esmvaltool/install/R/setup.R
Labels: installation

#1794 Avoid autodocsumm 0.2.0 and update documentation build dependencies
  doc/sphinx/source/conf.py
  doc/sphinx/source/requirements.txt
  setup.py
Labels: documentation
