Repository ESMValGroup/ESMValTool, pull requests merged in 2020-11, with the labels that each got.

#1864 Add mapplot diagnostic to ClimWIP
  doc/sphinx/source/recipes/figures/climwip/temperature_change_weighted_map.png
  doc/sphinx/source/recipes/recipe_climwip.rst
  esmvaltool/diag_scripts/weighting/plot_utilities.py
  esmvaltool/diag_scripts/weighting/weighted_temperature_graph.py
  esmvaltool/diag_scripts/weighting/weighted_temperature_map.py
  esmvaltool/recipes/recipe_climwip.yml
Labels: EUCP

#1856 Add the option to weight variable groups in ClimWIP
  doc/sphinx/source/recipes/recipe_climwip.rst
  esmvaltool/diag_scripts/weighting/climwip.py
  esmvaltool/recipes/recipe_climwip.yml
Labels: EUCP, diagnostic

#1852 Implementation of ensemble member recognition to the ClimWIP diagnostic
  doc/sphinx/source/recipes/recipe_climwip.rst
  esmvaltool/diag_scripts/weighting/climwip.py
  esmvaltool/recipes/recipe_climwip.yml
Labels: EUCP, diagnostic

#1913 switched miniconda conda setup hooks for Github Actions workflows
  .github/workflows/action-conda-build.yml
  .github/workflows/action-conda-publish.yml
  .github/workflows/action-install-from-conda.yml
  .github/workflows/action-install-from-source.yml
  .github/workflows/action-test.yml
Labels: test

#1919 Restructure ClimWIP
  esmvaltool/diag_scripts/weighting/climwip/core_functions.py
  esmvaltool/diag_scripts/weighting/climwip/io_functions.py
  esmvaltool/diag_scripts/weighting/climwip/main.py
  esmvaltool/diag_scripts/weighting/plot_utilities.py
  esmvaltool/diag_scripts/weighting/weighted_temperature_graph.py
  esmvaltool/diag_scripts/weighting/weighted_temperature_map.py
  esmvaltool/recipes/recipe_climwip.yml
Labels: EUCP, diagnostic

#1872 Add guidance on how to review a pull request
  .github/pull_request_template.md
  doc/sphinx/source/community/index.rst
  doc/sphinx/source/community/review.rst
Labels: community, documentation
