Repository ESMValGroup/ESMValTool, pull requests merged in 2020-07, with the labels that each got.

#1702 Fix pep8-naming errors and fix zmnam diagnostic
  esmvaltool/cmorizers/mip_convert/esmvt_mipconv_setup.py
  esmvaltool/cmorizers/obs/cmorize_obs_mls_aura.py
  esmvaltool/diag_scripts/landcover/albedolandcover.py
  esmvaltool/diag_scripts/zmnam/zmnam.py
  esmvaltool/diag_scripts/zmnam/zmnam_calc.py
  esmvaltool/diag_scripts/zmnam/zmnam_plot.py
  esmvaltool/diag_scripts/zmnam/zmnam_preproc.py
  esmvaltool/utils/rose-cylc/esmvt_rose_wrapper.py
Labels: bug, diagnostic

#1725 Gmd laueretal2020 revisions
  esmvaltool/diag_scripts/emergent_constraints/ecs_scatter.ncl
  esmvaltool/recipes/recipe_ecs_scatter.yml
Labels: diagnostic

#1721 Fix keyword argument
  esmvaltool/cmorizers/obs/cmorize_obs.py
Labels: bug, observations

#1735 Fixed JMA-TRANSCOM CMORizer
  esmvaltool/cmorizers/obs/cmorize_obs_jma_transcom.py
Labels: bug, observations

#1734 Fix bug in extract_doi_value
  esmvaltool/cmorizers/obs/utilities.py
Labels: bug, observations

#1728 PERSIANN-CDR cmorizer update: adding the capability to save monthly mean files
  doc/sphinx/source/input.rst
  esmvaltool/cmorizers/obs/cmorize_obs_persiann_cdr.py
  esmvaltool/recipes/examples/recipe_check_obs.yml
Labels: enhancement, observations

#1722 Fix small errors in the arctic_ocean diagnostic
  esmvaltool/diag_scripts/arctic_ocean/plotting.py
  esmvaltool/diag_scripts/arctic_ocean/utils.py
Labels: bug

#1699 Update CMORizers and recipes for ESMValCore v2.0.0
  environment.yml
  esmvaltool/cmorizers/obs/cmorize_obs.py
  esmvaltool/recipes/recipe_wenzel14jgr.yml
  package/meta.yaml
  setup.py
  tests/integration/test_diagnostic_run.py
  tests/integration/test_recipes_loading.py
Labels: enhancement

#1692 Wenzel16nature
  doc/sphinx/source/input.rst
  doc/sphinx/source/recipes/figures/wenzel16nat/fig_1.png
  doc/sphinx/source/recipes/figures/wenzel16nat/fig_2.png
  doc/sphinx/source/recipes/figures/wenzel16nat/fig_3.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_wenzel16nat.rst
  esmvaltool/cmorizers/obs/cmorize_obs_esrl.ncl
  esmvaltool/cmorizers/obs/utilities.ncl
  esmvaltool/diag_scripts/carbon_ec/carbon_aux.ncl
  esmvaltool/diag_scripts/carbon_ec/carbon_beta.ncl
  esmvaltool/diag_scripts/carbon_ec/carbon_co2_cycle.ncl
  esmvaltool/diag_scripts/shared/plot/aux_plotting.ncl
  esmvaltool/diag_scripts/shared/plot/carbon_plots.ncl
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/recipes/recipe_wenzel16nat.yml
  esmvaltool/references/wenzel16nat.bibtex
Labels: diagnostic, requires new ESMValCore release

#1701 Move draft_release_notes.py from ESMValCore to here and update
  .prospector.yml
  doc/sphinx/source/gensidebar.py
  doc/sphinx/source/utils.rst
  esmvaltool/utils/draft_release_notes.py
Labels: documentation

#1700 Update setup.py for PyPI package
  MANIFEST.in
  setup.py
Labels: installation

#1745 Flatten ancestor lists for diag_spei.R and diag_spi.R.
  esmvaltool/diag_scripts/droughtindex/diag_spei.R
  esmvaltool/diag_scripts/droughtindex/diag_spi.R
Labels: bug

#1744 Quick fix for recipe_ocean_ice_extent.yml
  esmvaltool/diag_scripts/ocean/diagnostic_seaice.py
Labels: bug, diagnostic

#1673 Add mask albedolandcover
  esmvaltool/diag_scripts/landcover/albedolandcover.py
Labels: diagnostic

#1740 Cleanup recipe headers before the release
  doc/sphinx/source/recipes/figures/droughtindex/martin18grl_fig1.png
  doc/sphinx/source/recipes/figures/droughtindex/martin18grl_fig2.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_martin18grl.rst
  esmvaltool/diag_scripts/droughtindex/collect_drought_func.py
  esmvaltool/recipes/examples/recipe_julia.yml
  esmvaltool/recipes/examples/recipe_my_personal_diagnostic.yml
  esmvaltool/recipes/examples/recipe_python.yml
  esmvaltool/recipes/examples/recipe_r.yml
  esmvaltool/recipes/examples/recipe_variable_groups.yml
  esmvaltool/recipes/hydrology/recipe_hype.yml
  esmvaltool/recipes/hydrology/recipe_lisflood.yml
  esmvaltool/recipes/hydrology/recipe_marrmot.yml
  esmvaltool/recipes/hydrology/recipe_pcrglobwb.yml
  esmvaltool/recipes/hydrology/recipe_wflow.yml
  esmvaltool/recipes/recipe_albedolandcover.yml
  esmvaltool/recipes/recipe_anav13jclim.yml
  esmvaltool/recipes/recipe_collins13ipcc.yml
  esmvaltool/recipes/recipe_consecdrydays.yml
  esmvaltool/recipes/recipe_cox18nature.yml
  esmvaltool/recipes/recipe_deangelis15nat.yml
  esmvaltool/recipes/recipe_ecs.yml
  esmvaltool/recipes/recipe_ecs_scatter.yml
  esmvaltool/recipes/recipe_ensclus.yml
  esmvaltool/recipes/recipe_eyring06jgr.yml
  esmvaltool/recipes/recipe_flato13ipcc.yml
  esmvaltool/recipes/recipe_hyint.yml
  esmvaltool/recipes/recipe_hyint_extreme_events.yml
  esmvaltool/recipes/recipe_landcover.yml
  esmvaltool/recipes/recipe_li17natcc.yml
  esmvaltool/recipes/recipe_martin18grl.yml
  esmvaltool/recipes/recipe_miles_block.yml
  esmvaltool/recipes/recipe_miles_eof.yml
  esmvaltool/recipes/recipe_miles_regimes.yml
  esmvaltool/recipes/recipe_multimodel_products.yml
  esmvaltool/recipes/recipe_ocean_Landschuetzer2016.yml
  esmvaltool/recipes/recipe_ocean_amoc.yml
  esmvaltool/recipes/recipe_quantilebias.yml
  esmvaltool/recipes/recipe_rainfarm.yml
  esmvaltool/recipes/recipe_seaice_drift.yml
  esmvaltool/recipes/recipe_seaice_feedback.yml
  esmvaltool/recipes/recipe_shapeselect.yml
  esmvaltool/recipes/recipe_spei.yml
  esmvaltool/recipes/recipe_tcr.yml
  esmvaltool/recipes/recipe_thermodyn_diagtool.yml
  esmvaltool/recipes/recipe_toymodel.yml
  esmvaltool/recipes/recipe_validation.yml
  esmvaltool/recipes/recipe_validation_CMIP6.yml
  esmvaltool/recipes/recipe_wenzel14jgr.yml
  esmvaltool/recipes/recipe_wenzel16jclim.yml
  esmvaltool/recipes/recipe_williams09climdyn_CREM.yml
  esmvaltool/recipes/recipe_zmnam.yml
  esmvaltool/references/martin18grl.bibtex
Labels: enhancement

#1746 Fix recipe_combined_indices.yml provenance
  esmvaltool/diag_scripts/magic_bsc/combined_indices.R
Labels: bug, diagnostic

#1747 Fix provenance in recipe_multimodel_products
  esmvaltool/diag_scripts/magic_bsc/multimodel_products.R
Labels: bug, diagnostic

#1726 IPCC AR5 fig. 9.3 (seasonality)
  doc/sphinx/source/recipes/figures/flato13ipcc/fig-9-3.png
  doc/sphinx/source/recipes/recipe_flato13ipcc.rst
  esmvaltool/diag_scripts/ipcc_ar5/ch09_fig09_3.ncl
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-tas-seasdelta.rgb
  esmvaltool/recipes/recipe_flato13ipcc.yml
Labels: diagnostic

#1634 Improve the installation instructions
  doc/sphinx/source/quickstart/installation.rst
Labels: documentation, enhancement

#1749 Exclude FGOALS-g2 due to ESMValCore issue #728
  esmvaltool/recipes/recipe_ocean_amoc.yml
Labels: bug, diagnostic

#1753 Fix recipe_modes_of_variability
  esmvaltool/diag_scripts/magic_bsc/weather_regime.R
Labels: bug, diagnostic

#1666 Update CLI: convert showcolortables to subcommand as an example
  esmvaltool/utils/color_tables/show_color_tables.py
  package/meta.yaml
  setup.py
Labels: enhancement

#1752 Flatten lists for ancestors for hyint to prevent nested lists.
  esmvaltool/diag_scripts/hyint/hyint.R
  esmvaltool/diag_scripts/hyint/hyint_diagnostic.R
  esmvaltool/diag_scripts/hyint/hyint_functions.R
  esmvaltool/diag_scripts/hyint/hyint_plot_maps.R
  esmvaltool/diag_scripts/hyint/hyint_plot_trends.R
  esmvaltool/diag_scripts/hyint/hyint_trends.R
Labels: bug

#1757 Update job script
  esmvaltool/utils/batch-jobs/job_DKRZ-MISTRAL.sh
  esmvaltool/utils/batch-jobs/job_PA2-CLUSTER.sh
Labels: enhancement

#1758 Read authors and description from .zenodo.json
  MANIFEST.in
  setup.py
Labels: enhancement

#1759 fix bug in cmorize_obs_eppley_vgpm_modis.py (#1729)
  environment.yml
  esmvaltool/cmorizers/obs/cmorize_obs_eppley_vgpm_modis.py
  package/meta.yaml
  setup.py
Labels: observations

#1585 Added additional emergent constraints on ECS
  doc/sphinx/source/recipes/figures/emergent_constraints/volodin.png
  doc/sphinx/source/recipes/recipe_cox18nature.rst
  doc/sphinx/source/recipes/recipe_ecs.rst
  doc/sphinx/source/recipes/recipe_emergent_constraints.rst
  esmvaltool/diag_scripts/climate_metrics/ecs.py
  esmvaltool/diag_scripts/climate_metrics/psi.py
  esmvaltool/diag_scripts/emergent_constraints/__init__.py
  esmvaltool/diag_scripts/emergent_constraints/cox18nature.py
  esmvaltool/diag_scripts/emergent_constraints/ecs_scatter.ncl
  esmvaltool/diag_scripts/emergent_constraints/ecs_scatter.py
  esmvaltool/diag_scripts/emergent_constraints/univariate_constraint.py
  esmvaltool/recipes/recipe_ecs_constraints.yml
  esmvaltool/references/brient16climdyn.bibtex
  esmvaltool/references/su14jgr.bibtex
  esmvaltool/references/volodin08izvestiya.bibtex
  esmvaltool/references/zhai15grl.bibtex
  package/meta.yaml
  setup.py
Labels: diagnostic

#1395 a diagnostic to evaluate the turnover times of land ecosystem carbon
  doc/sphinx/source/recipes/figures/carvalhais14nat/global_matrix_map_ecosystem_carbon_turnover_time_Carvalhais2014_gn.png
  doc/sphinx/source/recipes/figures/carvalhais14nat/global_multimodelAgreement_ecosystem_carbon_turnover_time_Carvalhais2014_gn.png
  doc/sphinx/source/recipes/figures/carvalhais14nat/r_tau_ctotal_climate_pearson_Carvalhais2014_gnz.png
  doc/sphinx/source/recipes/figures/carvalhais14nat/zonal_mean_ecosystem_carbon_turnover_time_Carvalhais2014_gnz.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_carvalhais14nat.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/land_carbon_cycle/diag_global_turnover.py
  esmvaltool/diag_scripts/land_carbon_cycle/diag_zonal_correlation.py
  esmvaltool/diag_scripts/land_carbon_cycle/diag_zonal_turnover.py
  esmvaltool/diag_scripts/land_carbon_cycle/plot_utils.py
  esmvaltool/diag_scripts/land_carbon_cycle/provenance.py
  esmvaltool/diag_scripts/land_carbon_cycle/shared.py
  esmvaltool/recipes/recipe_carvalhais14nat.yml
  esmvaltool/references/carvalhais14nature.bibtex
Labels: diagnostic

#1754 Allow for incomplete months on daily frequency in cmorizer ncl utilities
  esmvaltool/cmorizers/obs/utilities.ncl
Labels: observations

#1766 Fix AURA-TES cmorizer
  esmvaltool/cmorizers/obs/cmorize_obs_aura_tes.ncl
  package/meta.yaml
  setup.py
Labels: observations

#1768 Correct mip for clltkisccp in example derive preprocessor recipe
  esmvaltool/recipes/examples/recipe_preprocessor_derive_test.yml
Labels: bug, diagnostic

#1769 Update date conversion in recipe_hype.yml
  esmvaltool/diag_scripts/hydrology/hype.py
Labels: bug, diagnostic

#1767 Fix recipe_correlation.yml
  esmvaltool/diag_scripts/examples/correlate.py
Labels: bug, diagnostic

#1771 Add attribute positive: down to plev coordinate in ERA-Interim CMORizer
  esmvaltool/cmorizers/obs/cmorize_obs_era_interim.py
Labels: bug, observations

#1772 Fix sispeed in recipe_preprocessor_derive_test
  esmvaltool/recipes/examples/recipe_preprocessor_derive_test.yml
Labels: bug
