Repository ESMValGroup/ESMValTool, pull requests merged in 2020-10, with the labels that each got.

#1820 Update esmvaltool run command everywhere in documentation
  doc/sphinx/source/faq.rst
  doc/sphinx/source/input.rst
  esmvaltool/diag_scripts/ocean/diagnostic_maps.py
  esmvaltool/diag_scripts/ocean/diagnostic_seaice.py
  esmvaltool/diag_scripts/ocean/diagnostic_transects.py
  esmvaltool/diag_scripts/thermodyn_diagtool/thermodyn_diagnostics.py
Labels: documentation

#1648 Implement the climwip weighting scheme in a recipe and diagnostic
  doc/sphinx/source/recipes/figures/climwip/independence_tas.png
  doc/sphinx/source/recipes/figures/climwip/performance_pr.png
  doc/sphinx/source/recipes/figures/climwip/temperature_anomaly_graph.png
  doc/sphinx/source/recipes/figures/climwip/weights_tas.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_climwip.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/weighting/climwip.py
  esmvaltool/diag_scripts/weighting/weighted_temperature_graph.py
  esmvaltool/recipes/recipe_climwip.yml
  esmvaltool/references/brunner2019.bibtex
  esmvaltool/references/knutti2017.bibtex
  esmvaltool/references/lorenz2018.bibtex
  package/meta.yaml
  setup.py
Labels: EUCP, diagnostic

#1795 Add more info on documenting a recipe
  doc/sphinx/source/community/introduction.rst
Labels: documentation

#1845 Changes in shared scripts for Schlund et al., JGR: Biogeosciences, 2020
  esmvaltool/diag_scripts/emergent_constraints/__init__.py
  esmvaltool/diag_scripts/emergent_constraints/cox18nature.py
  esmvaltool/diag_scripts/shared/io.py
  esmvaltool/diag_scripts/shared/iris_helpers.py
  esmvaltool/diag_scripts/shared/plot/__init__.py
  esmvaltool/diag_scripts/shared/plot/_plot.py
  tests/unit/diag_scripts/shared/configs/test_io.yml
  tests/unit/diag_scripts/shared/test_io.py
  tests/unit/diag_scripts/shared/test_iris_helpers.py
Labels: diagnostic

#1857 Added CMORizer for Scripps-CO2-KUM
  doc/sphinx/source/input.rst
  esmvaltool/cmorizers/obs/cmor_config/Scripps-CO2-KUM.yml
  esmvaltool/cmorizers/obs/cmorize_obs_scripps_co2_kum.py
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/scripps_co2.bibtex
Labels: observations

#1827 Improve the Python example diagnostic and documentation
  .pre-commit-config.yaml
  doc/sphinx/source/community/introduction.rst
  doc/sphinx/source/conf.py
  doc/sphinx/source/input.rst
  doc/sphinx/source/quickstart/installation.rst
  doc/sphinx/source/recipes/figures/examples/map.png
  doc/sphinx/source/recipes/figures/examples/timeseries.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_python.rst
  esmvaltool/diag_scripts/examples/diagnostic.py
  esmvaltool/diag_scripts/shared/__init__.py
  esmvaltool/diag_scripts/shared/_base.py
  esmvaltool/diag_scripts/shared/plot/_plot.py
  esmvaltool/recipes/examples/recipe_python.yml
Labels: documentation

#1790 Updated derivation test recipe
  esmvaltool/recipes/examples/recipe_preprocessor_derive_test.yml
Labels: enhancement

#1848 Improve description of how to use draft_release_notes.py
  doc/sphinx/source/utils.rst
Labels: documentation

#1649 support for multiple model occurence in perf main
  esmvaltool/diag_scripts/perfmetrics/main.ncl
Labels: diagnostic

#1869 Pin eccodes to not use eccodes=2.19.0 for cdo to work fine
  .github/workflows/action-conda-build.yml
  environment.yml
  package/meta.yaml
Labels: installation

#1880 Adjust recipe_extract_shape.yml to recent changes in the example diagnostic.py
  doc/sphinx/source/conf.py
  doc/sphinx/source/recipes/figures/examples/elbe.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_examples.rst
  esmvaltool/recipes/examples/recipe_extract_shape.yml
Labels: diagnostic

#1858 Github Actions Build Packages and Deploy tests (conda and PyPi)
  .github/workflows/action-conda-publish.yml
  .github/workflows/action-pypi-build-and-deploy.yml
  pyproject.toml
  setup.py
Labels: deployment, test

#1886 Update changelog for release 2.1
  doc/sphinx/source/changelog.rst
Labels: documentation

#1867 Update instructions on making a release
  doc/sphinx/source/community/index.rst
  doc/sphinx/source/community/introduction.rst
  doc/sphinx/source/community/release_strategy.rst
  doc/sphinx/source/utils.rst
Labels: documentation
