Repository ESMValGroup/ESMValTool, pull requests merged in 2020-03, with the labels that each got.

#1556 Remove mention of obsolete mailing list.
  doc/sphinx/source/preface/core_team.rst
Labels: documentation

#1489 replaced 1:length(x) by seq_len statements
  esmvaltool/diag_scripts/droughtindex/diag_spei.R
  esmvaltool/diag_scripts/droughtindex/diag_spi.R
  esmvaltool/diag_scripts/extreme_events/extreme_events.R
  esmvaltool/diag_scripts/hyint/hyint_functions.R
  esmvaltool/diag_scripts/hyint/hyint_plot_maps.R
  esmvaltool/diag_scripts/hyint/hyint_plot_trends.R
  esmvaltool/diag_scripts/hyint/hyint_trends.R
  esmvaltool/diag_scripts/magic_bsc/PC.R
  esmvaltool/diag_scripts/magic_bsc/RegimesAssign.R
  esmvaltool/diag_scripts/magic_bsc/WeatherRegime.R
  esmvaltool/diag_scripts/magic_bsc/diurnal_temp_index.R
  esmvaltool/diag_scripts/magic_bsc/extreme_index.R
  esmvaltool/diag_scripts/magic_bsc/extreme_spells.R
  esmvaltool/diag_scripts/magic_bsc/multimodel_products.R
  esmvaltool/diag_scripts/magic_bsc/toymodel.R
  esmvaltool/diag_scripts/magic_bsc/weather_regime.R
  esmvaltool/diag_scripts/miles/basis_functions.R
  esmvaltool/diag_scripts/shared/external.R
  tests/unit/check_r_code.R
Labels: enhancement

#1540 Changes to zmNAM diagnostic
  esmvaltool/diag_scripts/zmnam/zmnam_calc.py
  esmvaltool/diag_scripts/zmnam/zmnam_plot.py
  esmvaltool/diag_scripts/zmnam/zmnam_preproc.py
  esmvaltool/recipes/recipe_zmnam.yml
Labels: diagnostic

#1541 New dataset CDS-SATELLITE-ALBEDO
  doc/sphinx/source/getting_started/inputdata.rst
  esmvaltool/cmorizers/obs/cmor_config/CDS-SATELLITE-ALBEDO.yml
  esmvaltool/cmorizers/obs/cmorize_obs_cds_satellite_albedo.py
  esmvaltool/cmorizers/obs/download_scripts/download_cds_satellite_albedo.py
  esmvaltool/config-references.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
  meta.yaml
  setup.py
Labels: observations

#1553 Cmorize regen
  doc/sphinx/source/getting_started/inputdata.rst
  esmvaltool/cmorizers/obs/cmor_config/REGEN.yml
  esmvaltool/cmorizers/obs/cmorize_obs_regen.py
  esmvaltool/config-references.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/regen.bibtex
Labels: observations

#1559 Cmorize berkeley earth
  doc/sphinx/source/getting_started/inputdata.rst
  esmvaltool/cmorizers/obs/cmor_config/BerkeleyEarth.yml
  esmvaltool/cmorizers/obs/cmorize_obs_berkeleyearth.py
  esmvaltool/config-references.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/berkeleyearth.bibtex
Labels: observations

#1572 Cmorize gistemp
  doc/sphinx/source/getting_started/inputdata.rst
  esmvaltool/cmorizers/obs/cmor_config/GISTEMP.yml
  esmvaltool/cmorizers/obs/cmorize_obs_gistemp.py
  esmvaltool/config-references.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/gistemp.bibtex
Labels: observations

#1573 Cmorize ghcn cams.sh
  doc/sphinx/source/getting_started/inputdata.rst
  esmvaltool/cmorizers/obs/cmor_config/GHCN-CAMS.yml
  esmvaltool/cmorizers/obs/cmorize_obs_ghcn_cams.py
  esmvaltool/config-references.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/ghcn_cams.bibtex
Labels: observations

#1299 Applicate sea ice negative feedback
  doc/sphinx/source/recipes/figures/seaice_feedback/negative_feedback.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_seaice_feedback.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/seaice_feedback/negative_seaice_feedback.py
  esmvaltool/diag_scripts/shared/names.py
  esmvaltool/recipes/recipe_seaice_feedback.yml
  esmvaltool/references/massonet18natcc.bibtex
Labels: diagnostic

#1590 Fix HALOE plev coordinate
  esmvaltool/cmorizers/obs/cmorize_obs_haloe.ncl
Labels: bug, observations

#1587 Restructure documentation
  CONTRIBUTING.md
  doc/sphinx/source/changelog.rst
  doc/sphinx/source/community/contact.rst
  doc/sphinx/source/community/diagnostic.rst
  doc/sphinx/source/community/index.rst
  doc/sphinx/source/community/introduction.rst
  doc/sphinx/source/community/porting.rst
  doc/sphinx/source/community/repository.rst
  doc/sphinx/source/conf.py
  doc/sphinx/source/develop/dataset.rst
  doc/sphinx/source/develop/diagnostic.rst
  doc/sphinx/source/develop/index.rst
  doc/sphinx/source/develop/introduction.rst
  doc/sphinx/source/develop/recipe.rst
  doc/sphinx/source/esmvaldiag/config_developer.rst
  doc/sphinx/source/esmvaldiag/index.rst
  doc/sphinx/source/esmvaldiag/new_diagnostic.rst
  doc/sphinx/source/faq.rst
  doc/sphinx/source/generate_gallery.py
  doc/sphinx/source/gensidebar.py
  doc/sphinx/source/getting_started/index.rst
  doc/sphinx/source/input.rst
  doc/sphinx/source/introduction.rst
  doc/sphinx/source/preface/architecture.rst
  doc/sphinx/source/preface/core_team.rst
  doc/sphinx/source/preface/index.rst
  doc/sphinx/source/preface/intro.rst
  doc/sphinx/source/preface/license.rst
  doc/sphinx/source/preface/objectives.rst
  doc/sphinx/source/quickstart/configuration.rst
  doc/sphinx/source/quickstart/index.rst
  doc/sphinx/source/quickstart/installation.rst
  doc/sphinx/source/quickstart/output.rst
  doc/sphinx/source/quickstart/running.rst
  doc/sphinx/source/recipes/recipe_emergent_constraints.rst
  doc/sphinx/source/utils.rst
Labels: documentation

#1591 Fix tro3 units in HALOE
  esmvaltool/cmorizers/obs/cmorize_obs_haloe.ncl
Labels: bug, observations

#1592 Add Russell18jgr ocean diagnostics
  doc/sphinx/source/recipes/figures/russell18jgr/Fig1_polar-contour_tauu_1986-2005.png
  doc/sphinx/source/recipes/figures/russell18jgr/Fig2_1986-2005.png
  doc/sphinx/source/recipes/figures/russell18jgr/Fig3_Polar-Front.png
  doc/sphinx/source/recipes/figures/russell18jgr/Fig3_Subantarctic-Fronts.png
  doc/sphinx/source/recipes/figures/russell18jgr/Fig4_Drake_passage.png
  doc/sphinx/source/recipes/figures/russell18jgr/Fig5_sic-max-min.png
  doc/sphinx/source/recipes/figures/russell18jgr/Fig5g_sic-line.png
  doc/sphinx/source/recipes/figures/russell18jgr/Fig6a.png
  doc/sphinx/source/recipes/figures/russell18jgr/Fig6b.png
  doc/sphinx/source/recipes/figures/russell18jgr/Fig7_fgco2_polar.png
  doc/sphinx/source/recipes/figures/russell18jgr/Fig7h_fgco2_zonal-flux.png
  doc/sphinx/source/recipes/figures/russell18jgr/Fig7i_fgco2_integrated-flux.png
  doc/sphinx/source/recipes/figures/russell18jgr/Fig8_polar-ph.png
  doc/sphinx/source/recipes/figures/russell18jgr/Fig9a.png
  doc/sphinx/source/recipes/figures/russell18jgr/Fig9b.png
  doc/sphinx/source/recipes/figures/russell18jgr/Fig9c.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_russell18jgr.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/russell18jgr/russell18jgr-fig2.ncl
  esmvaltool/diag_scripts/russell18jgr/russell18jgr-fig3b-2.ncl
  esmvaltool/diag_scripts/russell18jgr/russell18jgr-fig3b.ncl
  esmvaltool/diag_scripts/russell18jgr/russell18jgr-fig4.ncl
  esmvaltool/diag_scripts/russell18jgr/russell18jgr-fig5.ncl
  esmvaltool/diag_scripts/russell18jgr/russell18jgr-fig5g.ncl
  esmvaltool/diag_scripts/russell18jgr/russell18jgr-fig6a.ncl
  esmvaltool/diag_scripts/russell18jgr/russell18jgr-fig6b.ncl
  esmvaltool/diag_scripts/russell18jgr/russell18jgr-fig7h.ncl
  esmvaltool/diag_scripts/russell18jgr/russell18jgr-fig7i.ncl
  esmvaltool/diag_scripts/russell18jgr/russell18jgr-fig9a.ncl
  esmvaltool/diag_scripts/russell18jgr/russell18jgr-fig9b.ncl
  esmvaltool/diag_scripts/russell18jgr/russell18jgr-fig9c.ncl
  esmvaltool/diag_scripts/russell18jgr/russell18jgr-polar.ncl
  esmvaltool/recipes/recipe_russell18jgr.yml
Labels: diagnostic

#1545 Remove reference section in config-references.yml
  doc/sphinx/source/community/diagnostic.rst
  environment.yml
  esmvaltool/cmorizers/obs/utilities.py
  esmvaltool/config-references.yml
  esmvaltool/references/cowtanway.bibtex
  esmvaltool/references/docquier2017cryo.bibtex
  esmvaltool/references/ghcn-cams.bibtex
  esmvaltool/references/mls-aura.bibtex
  esmvaltool/references/righi19gmdd.bibtex
  esmvaltool/references/russell18jgr.bibtex
  meta.yaml
  setup.py
  tests/integration/test_recipes_loading.py
  tests/unit/test_recipes.py
Labels: enhancement

#1604 Add CMORizer for CT2019
  doc/sphinx/source/input.rst
  esmvaltool/cmorizers/obs/cmor_config/CT2019.yml
  esmvaltool/cmorizers/obs/cmorize_obs_ct2019.py
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/ct2019.bibtex
Labels: observations
