Repository ESMValGroup/ESMValTool, pull requests merged in 2020-06, with the labels that each got.

#1674 Workaround for permetrics recipe until Iris3
  esmvaltool/recipes/recipe_perfmetrics_CMIP5.yml
Labels: diagnostic, iris

#1678 Add ncdf4.helpers package as a dependency again
  .circleci/install_triggers
  esmvaltool/install/R/r_requirements.yml
Labels: installation

#1677 Speed up conda installation
  environment.yml
  esmvaltool/diag_scripts/autoassess/stratosphere/strat_metrics_1.py
  esmvaltool/diag_scripts/ensclus/eof_tool.py
  esmvaltool/utils/color_tables/show_color_tables.py
  package/meta.yaml
  setup.py
Labels: installation

#1681 Replace dead link with ESGF link.
  doc/sphinx/source/input.rst
Labels: documentation

#1641 Additional Land perfmetrics
  doc/sphinx/source/recipes/recipe_perfmetrics.rst
  esmvaltool/recipes/recipe_perfmetrics_land_CMIP5.yml
Labels: diagnostic

#1685 Update Sphinx to v3 or later
  doc/sphinx/source/conf.py
  doc/sphinx/source/requirements.txt
  setup.py
Labels: documentation

#1661 Make format time check more flexible
  doc/sphinx/source/input.rst
  esmvaltool/cmorizers/obs/cmorize_obs_cds_satellite_soil_moisture.ncl
  esmvaltool/cmorizers/obs/download_scripts/download_cds_satellite_soil_moisture.py
  esmvaltool/cmorizers/obs/utilities.ncl
  esmvaltool/recipes/examples/recipe_check_obs.yml
Labels: enhancement, observations

#1686 Necessary diagnostic from eyring06jgr for the release of version2
  doc/sphinx/source/recipes/figures/eyring06jgr/fig_diagn01.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_eyring06jgr.rst
  esmvaltool/diag_scripts/eyring06jgr/eyring06jgr_fig01.ncl
  esmvaltool/diag_scripts/eyring06jgr/eyring06jgr_fig05a.ncl
  esmvaltool/diag_scripts/eyring06jgr/eyring06jgr_fig05b.ncl
  esmvaltool/diag_scripts/eyring06jgr/eyring06jgr_fig15.ncl
  esmvaltool/diag_scripts/shared/plot/aux_plotting.ncl
  esmvaltool/recipes/recipe_eyring06jgr.yml
  esmvaltool/utils/editor-enhancements/ncl-ESMValTool.el
Labels: diagnostic

#1689 Drought characteristics based on Martin2018 and SPI for gmd paper
  doc/sphinx/source/recipes/figures/droughtindex/martin2018grl_fig1.png
  doc/sphinx/source/recipes/figures/droughtindex/martin2018grl_fig2.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_martin2018grl.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/droughtindex/collect_drought_func.py
  esmvaltool/diag_scripts/droughtindex/collect_drought_model.py
  esmvaltool/diag_scripts/droughtindex/collect_drought_obs_multi.py
  esmvaltool/diag_scripts/droughtindex/diag_save_spi.R
  esmvaltool/recipes/recipe_martin2018grl.yml
  esmvaltool/references/martin2018grl.bibtex
  esmvaltool/references/mckee93proc.bibtex
Labels: diagnostic
