Repository ESMValGroup/ESMValTool, pull requests merged in 2020-02, with the labels that each got.

#1509 Better default configuration
  config-user-example.yml
  doc/sphinx/source/getting_started/outputdata.rst
  esmvaltool/utils/batch-jobs/job_DKRZ-MISTRAL.sh
Labels: enhancement

#1490 Added more plotting and saving options for recipe validation
  doc/sphinx/source/recipes/recipe_validation.rst
  esmvaltool/diag_scripts/validation.py
  esmvaltool/recipes/recipe_validation.yml
  esmvaltool/recipes/recipe_validation_CMIP6.yml
Labels: diagnostic, enhancement

#1512 Add communities and grant to zenodo file
  .zenodo.json
  CITATION.cff
Labels: enhancement

#1514 Cmorizer wrapper now uses the in-built logger configuration and outputs stdout to out and stderr to err
  esmvaltool/cmorizers/obs/cmorize_obs.py
Labels: bug, enhancement

#1521 Took out fx_files from recipe albedolandcover
  esmvaltool/recipes/recipe_albedolandcover.yml
Labels: bug

#1524 New cmorizer for CALIPSO-GOCCP
  doc/sphinx/source/getting_started/inputdata.rst
  esmvaltool/cmorizers/obs/cmorize_obs_calipso_goccp.ncl
  esmvaltool/cmorizers/obs/utilities.ncl
  esmvaltool/recipes/examples/recipe_check_obs.yml
Labels: observations

#1432 ERA5 CMORization by recipe
  config-user-example.yml
  doc/sphinx/source/esmvaldiag/observations.rst
  esmvaltool/cmorizers/obs/cmor_config/ERA5.yml
  esmvaltool/cmorizers/obs/cmorize_obs_era5.py
  esmvaltool/diag_scripts/cmorizers/era5.py
  esmvaltool/recipes/cmorizers/recipe_era5.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
Labels: observations

#1508 Added CMORizer for MLS (hur, hurStderr)
  doc/sphinx/source/getting_started/inputdata.rst
  esmvaltool/cmorizers/obs/cmor_config/MLS-AURA.yml
  esmvaltool/cmorizers/obs/cmorize_obs_mls_aura.py
  esmvaltool/config-references.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
Labels: observations

#1349 eWaterCycle: Add recipe to prepare input for PCR-GlobWB
  esmvaltool/diag_scripts/hydrology/pcrglobwb.py
  esmvaltool/recipes/hydrology/recipe_pcrglobwb.yml
Labels: diagnostic, eWaterCycle

#1526 Fix hard-coded path in recipe_runoff_et.yml
  esmvaltool/diag_scripts/runoff_et/catchment_analysis.py
  esmvaltool/recipes/recipe_runoff_et.yml
Labels: diagnostic, enhancement

#1334 eWaterCycle: Add recipe to prepare input for HYPE
  doc/sphinx/source/recipes/recipe_hydrology.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/hydrology/hype.py
  esmvaltool/diag_scripts/shared/_base.py
  esmvaltool/recipes/hydrology/recipe_hype.yml
Labels: diagnostic, eWaterCycle

#1317 Documentation: added running pro tips
  doc/sphinx/source/esmvaldiag/index.rst
  doc/sphinx/source/esmvaldiag/protips.rst
Labels: documentation

#1504 fix monthly time for era-interim-land
  esmvaltool/cmorizers/obs/cmorize_obs_era_interim.py
Labels: observations

#1079 Add SeaIce Drift metric
  doc/sphinx/source/recipes/figures/seaice_drift/drift-strength.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_seaice_drift.rst
  esmvaltool/cmorizers/obs/utilities.py
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/seaice_drift/seaice_drift.py
  esmvaltool/diag_scripts/shared/names.py
  esmvaltool/recipes/recipe_seaice_drift.yml
  esmvaltool/references/docquier17.bibtex
  setup.py
Labels: PRIMAVERA, metric

#1531 Upgrade pcrglob recipe and diagnostic.
  esmvaltool/diag_scripts/hydrology/pcrglobwb.py
  esmvaltool/recipes/hydrology/recipe_pcrglobwb.yml
Labels: diagnostic, eWaterCycle

#1544 Add Era-Interim va and ta daily data
  doc/sphinx/source/getting_started/inputdata.rst
  esmvaltool/cmorizers/obs/cmor_config/ERA-Interim.yml
  esmvaltool/cmorizers/obs/download_scripts/download_era_interim.py
  esmvaltool/config-references.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
Labels: observations

#1550 Cmorize gpcc
  doc/sphinx/source/getting_started/inputdata.rst
  esmvaltool/cmorizers/obs/cmor_config/GPCC.yml
  esmvaltool/cmorizers/obs/cmorize_obs_gpcc.py
  esmvaltool/config-references.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/gpcc.bibtex
Labels: observations

#1552 Cmorize cowtan way
  doc/sphinx/source/getting_started/inputdata.rst
  esmvaltool/cmorizers/obs/cmor_config/CowtanWay.yml
  esmvaltool/cmorizers/obs/cmorize_obs_cowtanway.py
  esmvaltool/config-references.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/CowtanWay.bibtex
Labels: observations
