Repository ESMValGroup/ESMValTool, pull requests merged in 2020-05, with the labels that each got.

#1642 Extend getting started instructions to obtain config-user.yml
  doc/sphinx/source/quickstart/configuration.rst
Labels: documentation

#1554 Cmorize eobs
  doc/sphinx/source/input.rst
  esmvaltool/cmorizers/obs/cmor_config/E-OBS.yml
  esmvaltool/cmorizers/obs/cmorize_obs_e_obs.py
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/e-obs.bibtex
Labels: observations

#1298 eWaterCycle: Add recipe to prepare input for LISFLOOD
  doc/sphinx/source/recipes/recipe_hydrology.rst
  esmvaltool/diag_scripts/hydrology/lisflood.py
  esmvaltool/recipes/hydrology/recipe_lisflood.yml
Labels: diagnostic, eWaterCycle

#1644 Added monthly mean vars (ta, va, zg) to era5 cmorizer via recipe
  esmvaltool/recipes/cmorizers/recipe_era5.yml
Labels: era5, observations

#1652 Extend information about native6 support on RTD
  doc/sphinx/source/develop/dataset.rst
  doc/sphinx/source/input.rst
Labels: documentation

#1360 Support extra installation methods in R
  esmvaltool/install/R/r_requirements.txt
  esmvaltool/install/R/r_requirements.yml
  esmvaltool/install/R/setup.R
  esmvaltool/install/R/setup_devutils.R
Labels: installation
