Repository ESMValGroup/ESMValTool, pull requests merged in 2020-04, with the labels that each got.

#1607 Add info for new mailing list to documentation.
  doc/sphinx/source/community/contact.rst
  doc/sphinx/source/faq.rst
Labels: documentation

#1570 Various improvements to development infrastructure
  .circleci/config.yml
  .circleci/install_triggers
  RELEASE_NOTES
  doc/sphinx/source/community/introduction.rst
  environment.yml
  esmvaltool/cmorizers/obs/cmorize_obs_cds_satellite_albedo.py
  esmvaltool/cmorizers/obs/cmorize_obs_ndp.py
  package/language_support.sh
  package/meta.yaml
  setup.cfg
  setup.py
  tests/__init__.py
  tests/conftest.py
  tests/integration/test_diagnostic_run.py
  tests/integration/test_recipes_loading.py
  tests/unit/check_r_code.R
  tests/unit/diag_scripts/shared/test_io.py
  tests/unit/diag_scripts/shared/test_iris_helpers.py
Labels: enhancement

#1611 Install scikit-learn from conda, remove libunwind as a direct dependency
  environment.yml
  package/meta.yaml
  setup.py
Labels: installation

#1562 Fixed wenz14jgr
  doc/sphinx/source/recipes/figures/wenzel14jgr/constr_tas-nbp_30-1960.000001.png
  doc/sphinx/source/recipes/figures/wenzel14jgr/constr_tas-nbp_30-1960.000002.png
  doc/sphinx/source/recipes/figures/wenzel14jgr/corr_tas-nbp_anom_1960-2005.png
  doc/sphinx/source/recipes/figures/wenzel14jgr/tas_Global_CMIP5_1pctCO2_anom__1-1999.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_wenzel14jgr.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/carbon_ec/carbon_aux.ncl
  esmvaltool/diag_scripts/carbon_ec/carbon_constraint.ncl
  esmvaltool/diag_scripts/carbon_ec/carbon_gammaHist.ncl
  esmvaltool/diag_scripts/carbon_ec/carbon_tsline.ncl
  esmvaltool/diag_scripts/shared/scaling.ncl
  esmvaltool/recipes/recipe_wenzel14jgr.yml
Labels: diagnostic

#1133 Enhancement of the hyint recipe to include etccdi indices
  doc/sphinx/source/recipes/recipe_hyint.rst
  esmvaltool/diag_scripts/hyint/hyint.R
  esmvaltool/diag_scripts/hyint/hyint_diagnostic.R
  esmvaltool/diag_scripts/hyint/hyint_etccdi_preproc.R
  esmvaltool/diag_scripts/hyint/hyint_functions.R
  esmvaltool/diag_scripts/hyint/hyint_parameters.R
  esmvaltool/diag_scripts/hyint/hyint_plot_maps.R
  esmvaltool/diag_scripts/hyint/hyint_plot_trends.R
  esmvaltool/diag_scripts/hyint/hyint_trends.R
  esmvaltool/recipes/recipe_hyint_extreme_events.yml
Labels: diagnostic

#1635 Pin flake8<3.8.0
  package/meta.yaml
  setup.py
Labels: installation

#1626 Miles default domains to include lat=0
  esmvaltool/diag_scripts/miles/block_fast.R
  esmvaltool/recipes/recipe_miles_block.yml
  esmvaltool/recipes/recipe_miles_eof.yml
  esmvaltool/recipes/recipe_miles_regimes.yml
Labels: diagnostic, enhancement

#1555 Cmorize aphro ma
  doc/sphinx/source/input.rst
  esmvaltool/cmorizers/obs/cmor_config/APHRO-MA.yml
  esmvaltool/cmorizers/obs/cmorize_obs_aphro_ma.py
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/aphro-ma-v1101.bibtex
  esmvaltool/references/aphro-ma-v1808.bibtex
Labels: observations

#1517 Respectable testing for cmorizers/obs/utilities.py and cmorizers/obs/cmorize_obs.py
  tests/integration/test_cmorize_obs.py
  tests/unit/cmorizers/obs/test_utilities.py
Labels: enhancement, standards

#1638 Fix start year in recipe_check_obs
  esmvaltool/recipes/examples/recipe_check_obs.yml
Labels: observations

#1632 Miles: selection of reference dataset based on experiment
  doc/sphinx/source/recipes/recipe_miles.rst
  esmvaltool/diag_scripts/miles/miles_block.R
  esmvaltool/diag_scripts/miles/miles_eof.R
  esmvaltool/diag_scripts/miles/miles_regimes.R
  esmvaltool/recipes/recipe_miles_block.yml
  esmvaltool/recipes/recipe_miles_eof.yml
  esmvaltool/recipes/recipe_miles_regimes.yml
Labels: diagnostic, enhancement

#1633 Cmorizer for the PERSIANN-CDR precipitation data
  doc/sphinx/source/input.rst
  esmvaltool/cmorizers/obs/cmor_config/PERSIANN-CDR.yml
  esmvaltool/cmorizers/obs/cmorize_obs_persiann_cdr.py
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/persiann-cdr.bibtex
Labels: observations

#1567 New recipe/diagnostic: recipe_li17natcc.yml for Axels GMD Paper
  doc/sphinx/source/recipes/figures/emergent_constraints/li17natcc_fig2a.png
  doc/sphinx/source/recipes/figures/emergent_constraints/li17natcc_fig2b.png
  doc/sphinx/source/recipes/figures/emergent_constraints/li17natcc_fig2c.png
  doc/sphinx/source/recipes/figures/emergent_constraints/li17natcc_fig2d.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_li17natcc.rst
  esmvaltool/diag_scripts/emergent_constraints/lif1f2.py
  esmvaltool/recipes/recipe_li17natcc.yml
Labels: diagnostic

#1576 New recipe/diagnostics: recipe_deangelis_for_gmdpart4.yml for Axels GMD Paper
  doc/sphinx/source/recipes/figures/deangelis15nat/bar_all.png
  doc/sphinx/source/recipes/figures/deangelis15nat/exfig2a.png
  doc/sphinx/source/recipes/figures/deangelis15nat/fig3b.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_deangelis15nat.rst
  esmvaltool/diag_scripts/deangelis15nat/deangelisf1b.py
  esmvaltool/diag_scripts/deangelis15nat/deangelisf2ext.py
  esmvaltool/diag_scripts/deangelis15nat/deangelisf3f4.py
  esmvaltool/recipes/recipe_deangelis15nat.yml
Labels: diagnostic
