Repository ESMValGroup/ESMValTool, pull requests merged in 2020-01, with the labels that each got.

#1423 Added era-interim-land download to script
  esmvaltool/cmorizers/obs/download_scripts/download_era_interim.py
Labels: observations

#1474 Add orcid of some authors to the list
  esmvaltool/config-references.yml
Labels: enhancement

#1210 diagnostic for multi-model oceanic field maps (or bias against observations)
  doc/sphinx/source/recipes/recipe_oceans.rst
  esmvaltool/diag_scripts/ocean/diagnostic_maps_multimodel.py
  esmvaltool/recipes/recipe_ocean_multimap.yml
Labels: diagnostic

#1476 Change OBS to OBS6 for ERA-Interim
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/recipes/examples/recipe_concatenate_exps.yml
  esmvaltool/recipes/examples/recipe_correlation.yml
  esmvaltool/recipes/examples/recipe_extract_shape.yml
  esmvaltool/recipes/examples/recipe_julia.yml
  esmvaltool/recipes/examples/recipe_my_personal_diagnostic.yml
  esmvaltool/recipes/examples/recipe_ncl.yml
  esmvaltool/recipes/examples/recipe_preprocessor_derive_test.yml
  esmvaltool/recipes/examples/recipe_preprocessor_test.yml
  esmvaltool/recipes/examples/recipe_python.yml
  esmvaltool/recipes/examples/recipe_python_object_oriented.yml
  esmvaltool/recipes/examples/recipe_r.yml
  esmvaltool/recipes/examples/recipe_variable_groups.yml
  esmvaltool/recipes/hydrology/recipe_pcrglobwb.yml
  esmvaltool/recipes/recipe_ecs_scatter.yml
Labels: bug, observations

#1482 Update reference list for OBS
  esmvaltool/config-references.yml
Labels: documentation, observations

#1446 Adding a sea mask to recipe_extreme_index.yml
  doc/sphinx/source/recipes/figures/combined_climate_extreme_index/t90p_IPSL-CM5A-LR_rcp85_2020_2040.png
  esmvaltool/diag_scripts/magic_bsc/extreme_index.R
  esmvaltool/recipes/recipe_extreme_index.yml
Labels: diagnostic

#1485 Adapt diagnostics to ESMValCore no longer adding auxiliary coordinates
  esmvaltool/cmorizers/obs/cmorize_obs_era_interim.py
  esmvaltool/diag_scripts/autoassess/land_surface_permafrost/permafrost.py
  esmvaltool/diag_scripts/autoassess/loaddata.py
  esmvaltool/diag_scripts/climate_metrics/ecs.py
  esmvaltool/diag_scripts/climate_metrics/psi.py
  esmvaltool/diag_scripts/climate_metrics/tcr.py
  esmvaltool/diag_scripts/emergent_constraints/cox18nature.py
  esmvaltool/diag_scripts/ocean/diagnostic_profiles.py
  esmvaltool/diag_scripts/ocean/diagnostic_seaice.py
  esmvaltool/diag_scripts/runoff_et/catchment_analysis.py
Labels: diagnostic, standards

#1338 ERA-Interim Land
  doc/sphinx/source/getting_started/inputdata.rst
  esmvaltool/cmorizers/obs/cmor_config/ERA-Interim-Land.yml
  esmvaltool/cmorizers/obs/cmorize_obs_era_interim.py
  esmvaltool/cmorizers/obs/cmorize_obs_era_interim_land.py
  esmvaltool/config-references.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
Labels: help wanted, observations

#721 Arctic Ocean diagnostics [WIP]
  doc/sphinx/source/recipes/figures/arctic_ocean/aw_depth.png
  doc/sphinx/source/recipes/figures/arctic_ocean/aw_temp.png
  doc/sphinx/source/recipes/figures/arctic_ocean/bias.png
  doc/sphinx/source/recipes/figures/arctic_ocean/hofm.png
  doc/sphinx/source/recipes/figures/arctic_ocean/spatial.png
  doc/sphinx/source/recipes/figures/arctic_ocean/transect.png
  doc/sphinx/source/recipes/figures/arctic_ocean/ts.png
  doc/sphinx/source/recipes/figures/arctic_ocean/vertical.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_arctic_ocean.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/arctic_ocean/arctic_ocean.py
  esmvaltool/diag_scripts/arctic_ocean/getdata.py
  esmvaltool/diag_scripts/arctic_ocean/interpolation.py
  esmvaltool/diag_scripts/arctic_ocean/plotting.py
  esmvaltool/diag_scripts/arctic_ocean/regions.py
  esmvaltool/diag_scripts/arctic_ocean/utils.py
  esmvaltool/recipes/recipe_arctic_ocean.yml
  meta.yaml
  setup.py
Labels: diagnostic

#1384 Porting flato13 fig9 6
  doc/sphinx/source/recipes/figures/flato13ipcc/fig-9-6.png
  doc/sphinx/source/recipes/recipe_flato13ipcc.rst
  esmvaltool/diag_scripts/ipcc_ar5/ch09_fig09_6.ncl
  esmvaltool/diag_scripts/ipcc_ar5/ch09_fig09_6_collect.ncl
  esmvaltool/recipes/recipe_flato13ipcc.yml
Labels: diagnostic

#1042 Add cmorizer for OSI-450 dataset
  doc/sphinx/source/getting_started/inputdata.rst
  esmvaltool/cmorizers/obs/cmor_config/OSI-450-nh.yml
  esmvaltool/cmorizers/obs/cmor_config/OSI-450-sh.yml
  esmvaltool/cmorizers/obs/cmorize_obs_osi_450_nh.py
  esmvaltool/cmorizers/obs/cmorize_obs_osi_450_sh.py
  esmvaltool/cmorizers/obs/osi_common.py
  esmvaltool/cmorizers/obs/utilities.py
  esmvaltool/config-references.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
Labels: PRIMAVERA, observations

#1262 Dox how to run multiple recipes via a rose suite
  doc/sphinx/source/getting_started/running.rst
  esmvaltool/utils/rose-cylc/esmvt_rose_wrapper.py
Labels: documentation

#1290 Fix case of no zero crossings for QBO metric computation
  esmvaltool/diag_scripts/autoassess/_plot_mo_metrics.py
  esmvaltool/diag_scripts/autoassess/stratosphere/strat_metrics_1.py
Labels: bug, diagnostic

#1507 adding cmorizer script for the MAC-LWP dataset
  doc/sphinx/source/getting_started/inputdata.rst
  esmvaltool/cmorizers/obs/cmorize_obs_mac_lwp.ncl
  esmvaltool/config-references.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
Labels: observations
