Repository ESMValGroup/ESMValTool, pull requests merged in 2021-01, with the labels that each got.

#1969 Github Actions: change time for cron job that installs from conda
  .github/workflows/action-install-from-conda.yml
Labels: test

#1970 add some maintainers to some recipes that are missing them
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/recipes/recipe_deangelis15nat.yml
  esmvaltool/recipes/recipe_smpi.yml
  esmvaltool/recipes/recipe_smpi_4cds.yml
Labels: documentation

#1978 add required functional parameters for extract time in recipe_er5.yml
  esmvaltool/recipes/cmorizers/recipe_era5.yml
Labels: bug, test

#1967 Added changes in shared functions necessary for schlund20esd
  esmvaltool/diag_scripts/emergent_constraints/__init__.py
  esmvaltool/diag_scripts/emergent_constraints/cox18nature.py
  esmvaltool/diag_scripts/emergent_constraints/ecs_scatter.py
  esmvaltool/diag_scripts/emergent_constraints/single_constraint.py
  esmvaltool/diag_scripts/mlr/rescale_with_emergent_constraint.py
  esmvaltool/recipes/recipe_ecs_constraints.yml
Labels: diagnostic

#1993 Use new conda environment for installing ESMValTool in Docker containers
  .circleci/config.yml
  README.md
  docker/Dockerfile
  docker/Dockerfile.dev
  docker/Dockerfile.exp
Labels: installation

#1999 CI upload relevant artifacts for test job
  .circleci/config.yml
Labels: test

#1989 Github Actions test that runs with the latest ESMValCore master
  .github/workflows/action-test-development.yml
Labels: test

#1997 Python 3.9: remove pynio as dependency and replace with rasterio and pin Matplotlib>3.3.1 and pin cartopy>=0.18
  .circleci/config.yml
  doc/sphinx/source/conf.py
  environment.yml
  esmvaltool/cmorizers/obs/cmorize_obs_eppley_vgpm_modis.py
  package/meta.yaml
  setup.py
Labels: deprecated feature, installation

#1973 Update core team info
  CODE_OF_CONDUCT.md
  NOTICE
  doc/sphinx/source/introduction.rst
Labels: documentation

#1971 Combine installation from source instructions and add common issues
  .github/pull_request_template.md
  doc/sphinx/source/community/introduction.rst
  doc/sphinx/source/quickstart/installation.rst
Labels: documentation
