Repository ESMValGroup/ESMValTool, pull requests merged in 2021-06, with the labels that each got.

#2186 Force git to ignore VSCode workspace files
  .gitignore
Labels: enhancement

#2076 Update for outdated link to reference Déandreis et al. (2014).
  doc/sphinx/source/recipes/recipe_diurnal_temperature_index.rst
Labels: bug, documentation

#2168 Update to new ESMValTool logo
  README.md
  doc/sphinx/source/conf.py
  doc/sphinx/source/figures/ESMValTool-logo-2.pdf
  doc/sphinx/source/figures/ESMValTool-logo-2.png
Labels: looking for technical reviewer, release

#2197 Instructions to use pre-installed versions on HPC clusters
  doc/sphinx/source/quickstart/installation.rst
Labels: documentation, enhancement, is-enes, release

#2170 Add functional Autoassess diagnostics: land surface metrics: permafrost, soil moisture, surface radiation
  doc/sphinx/source/recipes/figures/autoassess_landsurface/Permafrost_Metrics.png
  doc/sphinx/source/recipes/figures/autoassess_landsurface/Soilmoisture_Metrics.png
  doc/sphinx/source/recipes/figures/autoassess_landsurface/Surfrad_Metrics.png
  doc/sphinx/source/recipes/figures/autoassess_landsurface/pf_extent_asia_ACCESS-CM2.png
  doc/sphinx/source/recipes/figures/autoassess_landsurface/pf_extent_north_america_ACCESS-CM2.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_autoassess_landsurface_permafrost.rst
  doc/sphinx/source/recipes/recipe_autoassess_landsurface_soilmoisture.rst
  doc/sphinx/source/recipes/recipe_autoassess_landsurface_surfrad.rst
  doc/sphinx/source/recipes/recipe_autoassess_stratosphere.rst
  esmvaltool/diag_scripts/autoassess/autoassess_area_base.py
  esmvaltool/diag_scripts/autoassess/land_surface_permafrost/permafrost.py
  esmvaltool/diag_scripts/autoassess/land_surface_soilmoisture/soilmoisture.py
  esmvaltool/diag_scripts/autoassess/land_surface_surfrad/surfrad.py
  esmvaltool/recipes/recipe_autoassess_landsurface_permafrost.yml
  esmvaltool/recipes/recipe_autoassess_landsurface_soilmoisture.yml
  esmvaltool/recipes/recipe_autoassess_landsurface_surfrad.yml
  esmvaltool/references/brown02nsidc.bibtex
  esmvaltool/references/dorigo17rse.bibtex
  esmvaltool/references/gruber19essd.bibtex
  esmvaltool/references/kato18ebaf.bibtex
  esmvaltool/references/koven13jclim.bibtex
  esmvaltool/references/legates90tac.bibtex
  esmvaltool/references/loeb19jclim.bibtex
Labels: approved by scientific reviewer, approved by technical reviewer, diagnostic, documentation, enhancement, is-enes, metric, release

#2200 Update pin on esmvalcore pick up esmvalcore=2.3.0
  .circleci/config.yml
  environment.yml
  esmvaltool/utils/recipe_filler.py
  package/meta.yaml
  setup.cfg
  setup.py
  tests/integration/test_recipe_filler.py
Labels: installation, release

#1808 Add GlobWat recipe and diagnostic
  doc/sphinx/source/recipes/recipe_hydrology.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/hydrology/globwat.py
  esmvaltool/recipes/hydrology/recipe_globwat.yml
  esmvaltool/references/debruin16ams.bibtex
  esmvaltool/references/hoogeveen15hess.bibtex
  esmvaltool/references/langbein1949usgs.bibtex
Labels: approved by scientific reviewer, approved by technical reviewer, diagnostic, eWaterCycle

#2109 Add ClimWIP recipe to reproduce Brunner et al. 2019
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_climwip.rst
  esmvaltool/diag_scripts/weighting/climwip/main.py
  esmvaltool/recipes/recipe_climwip_brunner2019_med.yml
Labels: EUCP, approved by scientific reviewer, diagnostic

#2188 Add citation info in `recipe_eady_growth_rate.yml`
  doc/sphinx/source/recipes/recipe_eady_growth_rate.rst
  esmvaltool/diag_scripts/primavera/eady_growth_rate/eady_growth_rate.py
  esmvaltool/recipes/recipe_eady_growth_rate.yml
  esmvaltool/references/morenochamarro2021.bibtex
Labels: documentation

#2203 Fixed recipes for ESMValCore 2.3.0
  esmvaltool/recipes/recipe_cox18nature.yml
  esmvaltool/recipes/recipe_ecs.yml
  esmvaltool/recipes/recipe_ecs_constraints.yml
  esmvaltool/recipes/recipe_schlund20esd.yml
  esmvaltool/recipes/recipe_tcr.yml
Labels: bug

#1859 Update Climwip recipe to reproduce brunner2020esd
  doc/sphinx/source/recipes/recipe_climwip.rst
  esmvaltool/diag_scripts/weighting/calculate_difference_variable_group.py
  esmvaltool/diag_scripts/weighting/climwip/calibrate_sigmas.py
  esmvaltool/diag_scripts/weighting/climwip/core_functions.py
  esmvaltool/diag_scripts/weighting/climwip/io_functions.py
  esmvaltool/diag_scripts/weighting/climwip/main.py
  esmvaltool/diag_scripts/weighting/weighted_temperature_graph.py
  esmvaltool/diag_scripts/weighting/weighted_temperature_map.py
  esmvaltool/recipes/recipe_climwip_brunner20esd.yml
  esmvaltool/references/brunner2020.bibtex
Labels: EUCP, approved by scientific reviewer, approved by technical reviewer, diagnostic

#2152 Python cmorizers for CDR1 and CDR2 ESACCI H2O (TCWV=prw) data.
  doc/sphinx/source/input.rst
  esmvaltool/cmorizers/obs/cmor_config/ESACCI-WATERVAPOUR.yml
  esmvaltool/cmorizers/obs/cmorize_obs_esacci_watervapour.py
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/esacci-watervapour.bibtex
Labels: approved by scientific reviewer, approved by technical reviewer

#2110 reinstate OSX Github Action tests
  .github/workflows/action-test.yml
  doc/sphinx/source/community/code_documentation.rst
  doc/sphinx/source/quickstart/installation.rst
  environment_osx.yml
  tests/integration/diagnostic.R
  tests/integration/diagnostic.jl
  tests/integration/diagnostic.ncl
  tests/integration/diagnostic.py
  tests/integration/test_diagnostic_run.py
  tests/unit/test_lint.py
Labels: testing

#1991 Cmorize wfde5
  doc/sphinx/source/input.rst
  esmvaltool/cmorizers/obs/cmor_config/WFDE5.yml
  esmvaltool/cmorizers/obs/cmorize_obs_wfde5.py
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/wfde5.bibtex
Labels: approved by technical reviewer, in scientific review, observations, release

#2208 Pin Python to 3.9 for development installation
  .circleci/config.yml
  doc/sphinx/source/quickstart/installation.rst
  environment.yml
Labels: installation

#2206 Make cmorizer utils funcs public in utilities.py and add some numpy style docstrings
  esmvaltool/cmorizers/obs/cmorize_obs_e_obs.py
  esmvaltool/cmorizers/obs/cmorize_obs_gpcc.py
  esmvaltool/cmorizers/obs/cmorize_obs_hadcrut5.py
  esmvaltool/cmorizers/obs/utilities.py
  tests/unit/cmorizers/obs/test_utilities.py
Labels: looking for technical reviewer, observations, standards

#2101 CMORizer for CLARA-AVHRR cloud data
  doc/sphinx/source/input.rst
  esmvaltool/cmorizers/obs/cmorize_obs_clara_avhrr.ncl
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/clara-avhrr.bibtex
Labels: looking for scientific reviewer, observations

#2211 Fix the WFDE5 cmorizer
  esmvaltool/cmorizers/obs/cmor_config/WFDE5.yml
Labels: bug, release

#2144 Update of ESACCI-CLOUD CMORizer
  doc/sphinx/source/input.rst
  esmvaltool/cmorizers/obs/cmorize_obs_esacci_cloud.ncl
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/recipes/recipe_perfmetrics_CMIP5.yml
  esmvaltool/recipes/recipe_perfmetrics_CMIP5_4cds.yml
Labels: approved by scientific reviewer, approved by technical reviewer, enhancement, observations
