Repository ESMValGroup/ESMValTool, pull requests merged in 2021-11, with the labels that each got.

#2397 Fix arctic ocean diagnostic
  esmvaltool/diag_scripts/arctic_ocean/utils.py
Labels: bug, diagnostic

#2289 Fix provenance of Julia example diagnostic
  doc/sphinx/source/recipes/recipe_examples.rst
  esmvaltool/diag_scripts/examples/diagnostic.jl
  esmvaltool/recipes/examples/recipe_julia.yml
Labels: documentation

#2403 Adapt diagnostic script to new version of iris
  esmvaltool/diag_scripts/ipcc_ar5/ch09_fig09_14.py
Labels: bug, diagnostic

#2406 Fix ocean multimap
  esmvaltool/diag_scripts/ocean/diagnostic_maps_multimodel.py
Labels: bug, diagnostic

#2399 Add missing preprocessor to recipe_gier2020bg and adapt to available data
  esmvaltool/recipes/recipe_gier2020bg.yml
Labels: diagnostic

#2405 Removed custom version of `AtmosphereSigmaFactory` in diagnostics
  esmvaltool/diag_scripts/emergent_constraints/ecs_scatter.py
Labels: iris

#2409 Fix diagnostic that uses `xarray`: `dtype` correctly set and harmonize `xarray` and `matplotlib`
  esmvaltool/diag_scripts/kcs/local_resampling.py
  esmvaltool/diag_scripts/weighting/weighted_temperature_graph.py
Labels: bug, diagnostic

#2236 added notes on use of mamba in the installation documentation chapter
  doc/sphinx/source/quickstart/installation.rst
Labels: enhancement, documentation

#2412 Update release schedule for 2.4.0
  doc/sphinx/source/community/release_strategy.rst
Labels: documentation, release

#2417 Comment out release candidate channel in environment.yml
  environment.yml
Labels: deployment, release

#2421 comment out rc channel in osx environment file
  environment_osx.yml
Labels: bug

#2420 Remove the use of `esmvalgroup` channel from the conda install Github Action workflow
  .github/workflows/install-from-conda.yml
Labels: bug
