Repository ESMValGroup/ESMValTool, pull requests merged in 2021-12, with the labels that each got.

#2282 Radiation budget new diagnostic
  doc/sphinx/source/recipes/figures/radiation_budget/UKESM1-0-LL.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_radiation_budget.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/radiation_budget/Demory_et_al_2014_obs_Energy_Budget.yml
  esmvaltool/diag_scripts/radiation_budget/Stephens_et_al_2012_obs_Energy_Budget.yml
  esmvaltool/diag_scripts/radiation_budget/radiation_budget.py
  esmvaltool/diag_scripts/radiation_budget/seasonal_radiation_budget.py
  esmvaltool/recipes/recipe_radiation_budget.yml
Labels: diagnostic, approved by technical reviewer, approved by scientific reviewer

#1832 CMUG Sea Surface Salinity dataset and diagnostic
  doc/sphinx/source/input.rst
  doc/sphinx/source/recipes/figures/sea_surface_salinity/radar.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_sea_surface_salinity.rst
  esmvaltool/cmorizers/obs/cmor_config/ESACCI-SEA-SURFACE-SALINITY.yml
  esmvaltool/cmorizers/obs/cmorize_obs_esacci_sea_surface_salinity.py
  esmvaltool/diag_scripts/sea_surface_salinity/compare_salinity.py
  esmvaltool/diag_scripts/shared/names.py
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/recipes/recipe_sea_surface_salinity.yml
  esmvaltool/references/esacci-sea-surface-salinity.bibtex
Labels: diagnostic, observations, approved by technical reviewer, approved by scientific reviewer

#2438 Mention ENES Climate Analytics service
  doc/sphinx/source/input.rst
Labels: documentation
