Repository ESMValGroup/ESMValTool, pull requests merged in 2021-09, with the labels that each got.

#2279 Fix provenance of NCL figures created using the log_provenance function
  esmvaltool/interface_scripts/logging.ncl
Labels: bug

#2290 add apt update so Julia gets found and installed by Docker
  docker/Dockerfile
  docker/Dockerfile.dev
  docker/Dockerfile.exp
Labels: testing

#2293 Removed write_plots and write_netcdf from some NCL diagnostics
  esmvaltool/diag_scripts/austral_jet/asr.ncl
  esmvaltool/diag_scripts/austral_jet/main.ncl
  esmvaltool/diag_scripts/carbon_cycle/main.ncl
  esmvaltool/diag_scripts/carbon_cycle/mvi.ncl
  esmvaltool/diag_scripts/carbon_cycle/two_variables.ncl
  esmvaltool/diag_scripts/emergent_constraints/ecs_scatter.ncl
  esmvaltool/diag_scripts/mder/absolute_correlation.ncl
  esmvaltool/diag_scripts/mder/regression_stepwise.ncl
  esmvaltool/diag_scripts/perfmetrics/collect.ncl
  esmvaltool/diag_scripts/perfmetrics/cycle.ncl
  esmvaltool/diag_scripts/perfmetrics/cycle_latlon.ncl
  esmvaltool/diag_scripts/perfmetrics/cycle_zonal.ncl
  esmvaltool/diag_scripts/perfmetrics/latlon.ncl
  esmvaltool/diag_scripts/perfmetrics/main.ncl
  esmvaltool/diag_scripts/perfmetrics/zonal.ncl
  esmvaltool/diag_scripts/shared/mder.ncl
  esmvaltool/interface_scripts/logging.ncl
Labels: deprecated feature

#2226 Fix bug in ClimWIP brunner19 recipe when plotting
  doc/sphinx/source/recipes/recipe_climwip.rst
  esmvaltool/recipes/recipe_climwip_brunner2019_med.yml
Labels: bug, EUCP

#2297 Use mamba for environment update and creation in the Docker container build on DockerHub
  docker/Dockerfile
  docker/Dockerfile.dev
  docker/Dockerfile.exp
Labels: installation, testing, deployment

#2296 Fixed provenance logging of all python diagnostics by removing 'plot_file' entry
  esmvaltool/diag_scripts/autoassess/land_surface_permafrost/permafrost.py
  esmvaltool/diag_scripts/autoassess/land_surface_soilmoisture/soilmoisture.py
  esmvaltool/diag_scripts/autoassess/land_surface_surfrad/surfrad.py
  esmvaltool/diag_scripts/climate_metrics/create_barplot.py
  esmvaltool/diag_scripts/climate_metrics/create_scatterplot.py
  esmvaltool/diag_scripts/climate_metrics/ecs.py
  esmvaltool/diag_scripts/climate_metrics/feedback_parameters.py
  esmvaltool/diag_scripts/climate_metrics/tcr.py
  esmvaltool/diag_scripts/crem/ww09_esmvaltool.py
  esmvaltool/diag_scripts/cvdp/cvdp_wrapper.py
  esmvaltool/diag_scripts/emergent_constraints/cox18nature.py
  esmvaltool/diag_scripts/ipcc_ar5/ch09_fig09_14.py
  esmvaltool/diag_scripts/ipcc_ar5/ch09_fig09_42a.py
  esmvaltool/diag_scripts/ipcc_ar5/ch09_fig09_42b.py
  esmvaltool/diag_scripts/land_carbon_cycle/diag_zonal_correlation.py
  esmvaltool/diag_scripts/mlr/evaluate_residuals.py
  esmvaltool/diag_scripts/mlr/models/__init__.py
  esmvaltool/diag_scripts/mlr/plot.py
  esmvaltool/diag_scripts/mlr/rescale_with_emergent_constraint.py
  esmvaltool/diag_scripts/ocean/diagnostic_maps_multimodel.py
  esmvaltool/diag_scripts/thermodyn_diagtool/plot_script.py
  esmvaltool/diag_scripts/thermodyn_diagtool/provenance_meta.py
Labels: diagnostic, deprecated feature

#2312 Pin docutils <0.17 to fix sphinx build with rtd theme
  doc/sphinx/source/requirements.txt
Labels: bug, documentation

#2306 Docker container experimental - run a full env solve with mamba instead of a conda update
  docker/Dockerfile.exp
Labels: installation, testing, deployment
