Repository ESMValGroup/ESMValTool, pull requests merged in 2021-04, with the labels that each got.

#2094 Added recipe for Meehl et al., Sci. Adv. (2020)
  doc/sphinx/source/recipes/figures/meehl20sciadv/cmip6_gregory_regression.png
  doc/sphinx/source/recipes/figures/meehl20sciadv/cmip6_tcr_vs_ecs.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_ecs.rst
  doc/sphinx/source/recipes/recipe_flato13ipcc.rst
  doc/sphinx/source/recipes/recipe_meehl20sciadv.rst
  doc/sphinx/source/recipes/recipe_schlund20esd.rst
  doc/sphinx/source/recipes/recipe_tcr.rst
  esmvaltool/diag_scripts/climate_metrics/create_table.py
  esmvaltool/diag_scripts/climate_metrics/tcr.py
  esmvaltool/diag_scripts/ipcc_ar5/ch09_fig09_42b.py
  esmvaltool/diag_scripts/shared/plot/styles_python/cmip6.yml
  esmvaltool/recipes/recipe_meehl20sciadv.yml
  esmvaltool/recipes/recipe_tcr.yml
  esmvaltool/references/meehl20sciadv.bibtex
Labels: diagnostic

#2111 Update documentation for ERA5 with new varibles
  doc/sphinx/source/input.rst
Labels: EUCP, documentation, era5

#2115 add OSX installation instructions to docs
  doc/sphinx/source/quickstart/installation.rst
Labels: documentation

#2107 Add fix for iris longitude bug to ClimWIP
  esmvaltool/diag_scripts/weighting/weighted_temperature_map.py
  esmvaltool/recipes/recipe_climwip_test_basic.yml
Labels: EUCP, approved by scientific reviewer, approved by technical reviewer, bug, requires new ESMValCore release
