Repository ESMValGroup/ESMValTool, pull requests merged in 2021-08, with the labels that each got.

#2253 Fixed `recipe_meehl20sciadv.yml` for ESMValCore 2.3
  esmvaltool/recipes/recipe_meehl20sciadv.yml
Labels: bug

#2264 Remove Python 3.6 tests from GitHub Actions
  .github/workflows/action-conda-publish.yml
  .github/workflows/action-install-from-conda.yml
  .github/workflows/action-install-from-source.yml
  .github/workflows/action-test-development.yml
  .github/workflows/action-test.yml
Labels: testing

#2266 Unpin upper bound for iris (previously was at <3.0.4)
  .github/workflows/action-test-development.yml
  .github/workflows/action-test.yml
  environment.yml
  package/meta.yaml
  setup.py
Labels: iris, installation, testing

#2182 Replace recipe_era5.yml with recipe_daily_era5.yml
  doc/sphinx/source/input.rst
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_cmorizers.rst
  esmvaltool/recipes/cmorizers/recipe_daily_era5.yml
  esmvaltool/recipes/cmorizers/recipe_era5.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/hersbach20rmets.bibtex
  setup.cfg
Labels: observations

#2269 Pin latest esmvalcore to allow use of the bugfix release 2.3.1 always
  environment.yml
  package/meta.yaml
  setup.py
Labels: installation, testing, deployment

#2268 List Manuel Schlund as release manager for v2.5
  doc/sphinx/source/community/release_strategy.rst
Labels: documentation, community
