Repository ESMValGroup/ESMValTool, pull requests merged in 2021-07, with the labels that each got.

#2220 Pin mpich to avoid default install of 3.4.1 and 3.4.2 with external_0 builds
  environment.yml
  package/meta.yaml
Labels: deployment, release, testing

#2225 Fix bug in ClimWIP basic test recipe when plotting
  esmvaltool/recipes/recipe_climwip_test_basic.yml
Labels: EUCP

#2227 Fix bug in ClimWIP advanced test recipe when plotting
  esmvaltool/recipes/recipe_climwip_test_performance_sigma.yml
Labels: EUCP, approved by scientific reviewer, approved by technical reviewer, bug

#1391 Update recipe_thermodyn_diagtool.yml: code improvements and more user options
  doc/sphinx/source/recipes/recipe_thermodyn_diagtool.rst
  esmvaltool/diag_scripts/thermodyn_diagtool/computations.py
  esmvaltool/diag_scripts/thermodyn_diagtool/fluxogram.py
  esmvaltool/diag_scripts/thermodyn_diagtool/fourier_coefficients.py
  esmvaltool/diag_scripts/thermodyn_diagtool/lorenz_cycle.py
  esmvaltool/diag_scripts/thermodyn_diagtool/mkthe.py
  esmvaltool/diag_scripts/thermodyn_diagtool/plot_script.py
  esmvaltool/diag_scripts/thermodyn_diagtool/thermodyn_diagnostics.py
  esmvaltool/recipes/recipe_thermodyn_diagtool.yml
Labels: approved by scientific reviewer, approved by technical reviewer, diagnostic, enhancement

#2234 Include test sources in distribution
  MANIFEST.in
Labels: deployment, enhancement, testing

#2232 Adjust time range for the `WDFE5` dataset in the `recipe_check_obs.yml`
  esmvaltool/recipes/examples/recipe_check_obs.yml
Labels: bug, observations

#2238 Remove model AWI-CM-1-1-MR from recipe_impact.yml
  esmvaltool/recipes/recipe_impact.yml
Labels: diagnostic

#2246 Pin `iris<3.0.4` to ensure we still (sort of) support Python 3.6
  .github/workflows/action-pypi-build-and-deploy.yml
  environment.yml
  environment_osx.yml
  package/meta.yaml
  setup.py
Labels: installation, iris, release, testing

#2244 Fix plot and provenance of recipe_consecdrydays
  doc/sphinx/source/recipes/recipe_consecdrydays.rst
  esmvaltool/diag_scripts/droughtindex/diag_cdd.py
Labels: bug, diagnostic

#2153 PV capacity factor for ESMValTool GMD paper
  doc/sphinx/source/recipes/figures/pv_capacity_factor/capacity_factor_IPSL-CM5A-MR_1980-2005_DJF.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_pv_capacity_factor.rst
  esmvaltool/diag_scripts/pv_capacityfactor/PV_CF.R
  esmvaltool/diag_scripts/pv_capacityfactor/pv_capacity_factor.R
  esmvaltool/recipes/recipe_pv_capacity_factor.yml
  esmvaltool/references/bett2016renene.bibtex
  esmvaltool/references/weigel2021gmd.bibtex
Labels: approved by scientific reviewer, approved by technical reviewer, diagnostic, release

#2213 Update version number to 2.3.0
  CITATION.cff
  esmvaltool/__init__.py
  package/meta.yaml
Labels: documentation

#2247 Update release schedule for 2.3.0
  doc/sphinx/source/community/release_strategy.rst
Labels: documentation

#2214 Changelog update to v2.3.0
  doc/sphinx/source/changelog.rst
  esmvaltool/utils/draft_release_notes.py
Labels: documentation

#2219 Add a cylc suite to run all recipes
  .gitignore
  doc/sphinx/source/utils.rst
  esmvaltool/utils/testing/regression/bin/run-esmvaltool.sh
  esmvaltool/utils/testing/regression/example-recipes.rc
  esmvaltool/utils/testing/regression/recipes.rc
  esmvaltool/utils/testing/regression/suite.rc
  esmvaltool/utils/testing/regression/summarize.py
Labels: testing

#2229 retire test with Python 3.6 from full development Github Actions test
  .github/workflows/action-test-development.yml
Labels: deployment, installation, testing
