Repository ESMValGroup/ESMValTool, pull requests merged in 2021-02, with the labels that each got.

#2003 Update iris documentation URL for sphinx
  doc/sphinx/source/conf.py
Labels: documentation

#1963 Add GRACE to the recipe check_obs
  esmvaltool/cmorizers/obs/cmor_config/GRACE.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/grace.bibtex
Labels: enhancement

#1988 fix longitude in ESRL cmorizer
  esmvaltool/cmorizers/obs/cmorize_obs_esrl.py
Labels: observations, release

#2012 fix iris documentation link(s) with new iris3 location on readthedocs
  doc/sphinx/source/recipes/recipe_examples.rst
Labels: documentation, release

#1847 Pointer to use updated pytest command to run tests in documentation
  doc/sphinx/source/quickstart/installation.rst
Labels: documentation, in technical review

#1874 Align ESMValTool to ESMValCore=2.2.0 (adopt iris3, fix environment for new Core release)
  environment.yml
  esmvaltool/cmorizers/obs/cmorize_obs.py
  esmvaltool/cmorizers/obs/nsidc_common.py
  esmvaltool/diag_scripts/autoassess/autoassess_area_base.py
  esmvaltool/diag_scripts/autoassess/land_surface_permafrost/permafrost.py
  esmvaltool/diag_scripts/autoassess/land_surface_surfrad/surfrad.py
  esmvaltool/diag_scripts/mlr/__init__.py
  esmvaltool/diag_scripts/shared/_supermeans.py
  esmvaltool/recipes/examples/recipe_preprocessor_derive_test.yml
  package/meta.yaml
  setup.py
Labels: enhancement, in technical review, iris, release, requires new ESMValCore release

#2017 List Remi Kazeroni as a code owner and sole merger of CMORizers
  .github/CODEOWNERS
  doc/sphinx/source/community/dataset.rst
  doc/sphinx/source/community/review.rst
  doc/sphinx/source/develop/dataset.rst
  doc/sphinx/source/input.rst
Labels: documentation

#1914 Adding recipe and diagnostics for Gier et al 2020
  doc/sphinx/source/recipes/figures/gier20bg/fig01.png
  doc/sphinx/source/recipes/figures/gier20bg/fig02.png
  doc/sphinx/source/recipes/figures/gier20bg/fig03.png
  doc/sphinx/source/recipes/figures/gier20bg/fig04.png
  doc/sphinx/source/recipes/figures/gier20bg/fig05.png
  doc/sphinx/source/recipes/figures/gier20bg/fig06.png
  doc/sphinx/source/recipes/figures/gier20bg/fig07.png
  doc/sphinx/source/recipes/figures/gier20bg/fig08.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_gier20bg.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/shared/plot/styles/cmip5.style
  esmvaltool/diag_scripts/shared/plot/styles/cmip6.style
  esmvaltool/diag_scripts/shared/scaling.ncl
  esmvaltool/diag_scripts/xco2_analysis/carbon_plots.ncl
  esmvaltool/diag_scripts/xco2_analysis/delta_T.ncl
  esmvaltool/diag_scripts/xco2_analysis/global_maps.ncl
  esmvaltool/diag_scripts/xco2_analysis/main.ncl
  esmvaltool/diag_scripts/xco2_analysis/panel_plots.ncl
  esmvaltool/diag_scripts/xco2_analysis/sat_masks.ncl
  esmvaltool/diag_scripts/xco2_analysis/stat.ncl
  esmvaltool/diag_scripts/xco2_analysis/station_comparison.ncl
  esmvaltool/interface_scripts/auxiliary.ncl
  esmvaltool/recipes/recipe_gier2020bg.yml
  esmvaltool/references/gier20bg.bibtex
Labels: approved by scientific reviewer, approved by technical reviewer, diagnostic, release

#2022 Fix logging import in cmorize_obs again since last merge was nulled by pre-commit hooks
  esmvaltool/cmorizers/obs/cmorize_obs.py
Labels: bug, release

#2023 Refactor the functions in derive_evspsblpot due to new iris
  esmvaltool/diag_scripts/hydrology/derive_evspsblpot.py
Labels: approved by technical reviewer, bug

#2027 Avoid importing private ESMValCore functions in CMORizer
  esmvaltool/cmorizers/obs/cmorize_obs.py
  esmvaltool/cmorizers/obs/cmorize_obs_esacci_sst.py
  esmvaltool/diag_scripts/autoassess/land_surface_soilmoisture/soilmoisture.py
  esmvaltool/diag_scripts/autoassess/land_surface_surfrad/surfrad.py
  esmvaltool/diag_scripts/cvdp/cvdp_wrapper.py
Labels: bug

#2026 Fix conda build
  package/meta.yaml
Labels: installation

#2030 Install documentation: mention that we build conda package with python>=3.7
  doc/sphinx/source/quickstart/installation.rst
Labels: documentation, release

#2029 introduce python 39 in Github Actions tests
  .github/workflows/action-conda-build.yml
  .github/workflows/action-conda-publish.yml
  .github/workflows/action-install-from-conda.yml
  .github/workflows/action-install-from-source.yml
  .github/workflows/action-pypi-build-and-deploy.yml
  .github/workflows/action-test.yml
Labels: release, test

#2014 selectively turn off fixing bounds for coordinates during cmorization with utilities.py
  esmvaltool/cmorizers/obs/utilities.py
  tests/unit/cmorizers/obs/test_utilities.py
Labels: enhancement, in technical review, observations, release

#2033 Remove test for conda package installation on Python 3.6
  .github/workflows/action-install-from-conda.yml
Labels: release, test

#1977 Cmorize hadcrut5
  doc/sphinx/source/input.rst
  esmvaltool/cmorizers/obs/cmor_config/HadCRUT5.yml
  esmvaltool/cmorizers/obs/cmorize_obs_hadcrut5.py
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/hadcrut5.bibtex
Labels: approved by scientific reviewer, approved by technical reviewer, observations, release

#2036 Removed write_plots and write_netcdf in some python diagnostics
  esmvaltool/diag_scripts/climate_metrics/create_barplot.py
  esmvaltool/diag_scripts/climate_metrics/create_scatterplot.py
  esmvaltool/diag_scripts/climate_metrics/ecs.py
  esmvaltool/diag_scripts/climate_metrics/tcr.py
  esmvaltool/diag_scripts/emergent_constraints/cox18nature.py
  esmvaltool/diag_scripts/ipcc_ar5/ch09_fig09_42a.py
  esmvaltool/diag_scripts/ipcc_ar5/ch09_fig09_42b.py
  esmvaltool/diag_scripts/mlr/models/__init__.py
  tests/integration/diag_scripts/mlr/configs/test_general.yml
  tests/integration/diag_scripts/mlr/configs/test_load_input_datasets.yml
  tests/integration/diag_scripts/mlr/generate_config.py
  tests/system/config-test.yml
  tests/unit/diag_scripts/shared/test_base.py
Labels: approved by technical reviewer, deprecated feature, release

#1995 Cmorize gpcc masking
  esmvaltool/cmorizers/obs/cmor_config/GPCC.yml
  esmvaltool/cmorizers/obs/cmorize_obs_gpcc.py
  esmvaltool/recipes/examples/recipe_check_obs.yml
Labels: approved by scientific reviewer, approved by technical reviewer, observations, release

#1990 cmorize_utils_save_1mon_Amon
  esmvaltool/cmorizers/obs/utilities.py
Labels: approved by scientific reviewer, approved by technical reviewer, observations, release

#1982 Cmorize gpcc fix
  esmvaltool/cmorizers/obs/cmorize_obs_gpcc.py
Labels: approved by scientific reviewer, approved by technical reviewer, observations, release

#1906 Recipe and documentation update for ERA5-Land.
  doc/sphinx/source/input.rst
  esmvaltool/recipes/cmorizers/recipe_era5-land.yml
  esmvaltool/references/era5-land.bibtex
Labels: approved by scientific reviewer, approved by technical reviewer, documentation, era5, observations, release

#1285 Add PRIMAVERA Eady Growth Rate diagnostic
  .zenodo.json
  doc/sphinx/source/recipes/figures/eady_growth_rate/HadGEM3-GC31-LM_winter_eady_growth_rate_70000.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_eady_growth_rate.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/primavera/eady_growth_rate/eady_growth_rate.py
  esmvaltool/recipes/recipe_eady_growth_rate.yml
Labels: PRIMAVERA, approved by scientific reviewer, approved by technical reviewer, diagnostic, release

#2038 fix flake8 raised by develop test in cmorize_obs_gpcc.py
  esmvaltool/cmorizers/obs/cmorize_obs_gpcc.py
Labels: bug, release

#1905 Implement shape parameter calibration for ClimWIP
  doc/sphinx/source/recipes/figures/climwip/performance_sigma_calibration.png
  doc/sphinx/source/recipes/recipe_climwip.rst
  esmvaltool/diag_scripts/weighting/climwip/calibrate_sigmas.py
  esmvaltool/diag_scripts/weighting/climwip/core_functions.py
  esmvaltool/diag_scripts/weighting/climwip/main.py
  esmvaltool/recipes/recipe_climwip_test_basic.yml
  esmvaltool/recipes/recipe_climwip_test_performance_sigma.yml
Labels: EUCP, approved by scientific reviewer, approved by technical reviewer, diagnostic, release

#2035 Revise lisflood and hype recipes
  esmvaltool/recipes/hydrology/recipe_hype.yml
  esmvaltool/recipes/hydrology/recipe_lisflood.yml
Labels: enhancement

#2039 Update codacy coverage reporter to fix coverage
  .circleci/config.yml
Labels: test

#1942 Use latest version of autodocsumm
  doc/sphinx/source/requirements.txt
  setup.py
Labels: approved by technical reviewer, documentation, installation, release

#2024 Refactor lazy_regrid.py for wflow diagnostics
  esmvaltool/diag_scripts/hydrology/compute_chunks.py
  esmvaltool/diag_scripts/hydrology/lazy_regrid.py
  esmvaltool/diag_scripts/hydrology/wflow.py
  esmvaltool/recipes/hydrology/recipe_wflow.yml
Labels: diagnostic, enhancement, in technical review

#1851 Add PASSIVE and ACTIVE sensor versions to cds-sat-sm cmorizer
  esmvaltool/cmorizers/obs/cmor_config/CDS-SATELLITE-SOIL-MOISTURE.ncl
  esmvaltool/cmorizers/obs/cmorize_obs_cds_satellite_soil_moisture.ncl
  esmvaltool/recipes/examples/recipe_check_obs.yml
Labels: approved by technical reviewer, looking for scientific reviewer, observations

#2045 Update the version number of the ESACCI-SST dataset
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/recipes/recipe_perfmetrics_CMIP5.yml
  esmvaltool/recipes/recipe_perfmetrics_CMIP5_4cds.yml
Labels: approved by technical reviewer, bug, release

#1958 Adding bock20jgr Figure 1-4
  doc/sphinx/source/input.rst
  doc/sphinx/source/recipes/figures/bock20jgr/model_bias_tas_annual_CMIP6.png
  doc/sphinx/source/recipes/figures/bock20jgr/tas_Global_CMIP6_historical_anom_1850-2014.png
  doc/sphinx/source/recipes/figures/bock20jgr/tas_Global_multimodel_anom_1850-2017.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_bock20jgr.rst
  esmvaltool/cmorizers/obs/cmorize_obs_hadcrut4.ncl
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/bock20jgr/model_bias.ncl
  esmvaltool/diag_scripts/bock20jgr/tsline.ncl
  esmvaltool/diag_scripts/bock20jgr/tsline_collect.ncl
  esmvaltool/diag_scripts/shared/plot/rgb/cmip_line.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/cmip_shading.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_misc_div.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_misc_seq_1.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_precipitation_div.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_precipitation_seq.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_temperature_div.rgb
  esmvaltool/diag_scripts/shared/plot/styles/cmip3.style
  esmvaltool/diag_scripts/shared/plot/xy_line.ncl
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/recipes/recipe_bock20jgr.yml
  esmvaltool/references/bock20jgr.bibtex
Labels: approved by scientific reviewer, approved by technical reviewer, diagnostic

#2047 Disable and remove calls to deprecated iris FUTURE module
  esmvaltool/diag_scripts/autoassess/plot_autoassess_metrics.py
  esmvaltool/diag_scripts/autoassess/stratosphere/age_of_air.py
  esmvaltool/diag_scripts/autoassess/stratosphere/strat_metrics_1.py
Labels: approved by technical reviewer, bug, deprecated feature, iris, release

#2048 fix flake fail from last commit to master
  esmvaltool/diag_scripts/autoassess/plot_autoassess_metrics.py
Labels: bug, testing

#2054 Fix extract_seasons in validation recipe
  esmvaltool/diag_scripts/validation.py
Labels: bug

#2043 Update changelog and changelog tool for v2.2.0
  doc/sphinx/source/changelog.rst
  doc/sphinx/source/utils.rst
  esmvaltool/utils/draft_release_notes.py
  tests/unit/test_docs.py
Labels: documentation

#2056 Final update to the changelog for v2.2.0
  doc/sphinx/source/changelog.rst
Labels: documentation

#2058 Fix conda build by skipping documentation test
  .circleci/config.yml
  package/meta.yaml
Labels: installation
