Repository ESMValGroup/ESMValTool, pull requests merged in 2022-03, with the labels that each got.

#2565 added stand with Ukraine badge
  README.md
Labels: community

#2567 Updated CREM docu (recipe_williams09climdyn.yml)
  doc/sphinx/source/recipes/recipe_crem.rst
Labels: documentation, release

#2554 First draft for v2.5.0 changelog
  doc/sphinx/source/changelog.rst
  doc/sphinx/source/input.rst
  tests/unit/documentation/test_changelog.py
Labels: documentation, release

#2577 Fix `recipe_wenzel14jgr`
  esmvaltool/recipes/recipe_wenzel14jgr.yml
Labels: bug, release

#2579 Remove missing CMIP5 data from 2 recipes
  esmvaltool/recipes/recipe_collins13ipcc.yml
  esmvaltool/recipes/recipe_perfmetrics_land_CMIP5.yml
Labels: bug, release

#2578 Fix `recipe_seaice`
  esmvaltool/recipes/recipe_impact.yml
  esmvaltool/recipes/recipe_seaice.yml
Labels: bug, release

#2581 Fix `recipe_climwip_brunner20esd`
  esmvaltool/recipes/recipe_climwip_brunner20esd.yml
Labels: bug

#2582 replace nonfunctional Github Actions badge with cool one in README
  README.md
Labels: documentation

#2583 Restored original versions of `recipe_schlund20esd.yml` and `recipe_meehl20sciadv.yml`
  esmvaltool/recipes/recipe_meehl20sciadv.yml
  esmvaltool/recipes/recipe_schlund20esd.yml
Labels: enhancement

#2589 Updated changelog
  .github/workflows/install-from-conda.yml
  .github/workflows/install-from-condalock-file.yml
  .github/workflows/install-from-source.yml
  doc/sphinx/source/changelog.rst
Labels: documentation, release

#2597 Updated release strategy with current release and upcoming release
  doc/sphinx/source/community/release_strategy.rst
Labels: documentation, release

#2600 Increased ESMValTool version to 2.5.0
  CITATION.cff
  esmvaltool/__init__.py
  package/meta.yaml
Labels: documentation, release

#2599 Updated dependencies with new ESMValCore version
  environment.yml
  environment_osx.yml
  package/meta.yaml
Labels: release

#2604 Cache natural earth mask cube in MLR diagnostics
  esmvaltool/diag_scripts/mlr/__init__.py
Labels: enhancement

#2612 Removed `package/meta.yaml` and all references to it
  doc/sphinx/source/community/code_documentation.rst
  doc/sphinx/source/community/release_strategy.rst
  package/install-julia-deps.sh
  package/install-r-deps.sh
  package/install.sh
  package/meta.yaml
Labels: installation

#2580 Documentation Improvements
  doc/sphinx/source/functionalities.rst
  doc/sphinx/source/gensidebar.py
  doc/sphinx/source/introduction.rst
  doc/sphinx/source/quickstart/installation.rst
Labels: documentation

#2616 Fixed broken label in the documentation
  doc/sphinx/source/community/release_strategy.rst
Labels: documentation

#2509 Extending the HadCRUT5 cmorizer
  doc/sphinx/source/input.rst
  esmvaltool/cmorizers/data/cmor_config/HadCRUT5.yml
  esmvaltool/cmorizers/data/datasets.yml
  esmvaltool/cmorizers/data/downloaders/datasets/hadcrut5.py
  esmvaltool/cmorizers/data/formatters/datasets/hadcrut5.py
  esmvaltool/recipes/examples/recipe_check_obs.yml
Labels: observations, IPCC
