Repository ESMValGroup/ESMValTool, pull requests merged in 2022-06, with the labels that each got.

#2657 Extend monitor diagnostics with multi-dataset plots
  doc/sphinx/source/api/esmvaltool.diag_scripts.monitor.rst
  doc/sphinx/source/api/esmvaltool.diag_scripts.monitor/compute_eofs.rst
  doc/sphinx/source/api/esmvaltool.diag_scripts.monitor/monitor.rst
  doc/sphinx/source/api/esmvaltool.diag_scripts.monitor/monitor_base.rst
  doc/sphinx/source/api/esmvaltool.diag_scripts.monitor/multi_datasets.rst
  doc/sphinx/source/api/esmvaltool.rst
  doc/sphinx/source/conf.py
  doc/sphinx/source/recipes/figures/monitor/map_with_ref.png
  doc/sphinx/source/recipes/figures/monitor/profile_with_ref.png
  doc/sphinx/source/recipes/figures/monitor/timeseries_with_ref.png
  doc/sphinx/source/recipes/recipe_monitor.rst
  esmvaltool/diag_scripts/mlr/plot.py
  esmvaltool/diag_scripts/monitor/compute_eofs.py
  esmvaltool/diag_scripts/monitor/monitor.py
  esmvaltool/diag_scripts/monitor/monitor_base.py
  esmvaltool/diag_scripts/monitor/multi_datasets.py
  esmvaltool/diag_scripts/mpqb/mpqb_lineplot.py
  esmvaltool/diag_scripts/mpqb/mpqb_lineplot_growthrate.py
  esmvaltool/diag_scripts/shared/iris_helpers.py
  esmvaltool/recipes/monitor/recipe_monitor.yml
  esmvaltool/recipes/monitor/recipe_monitor_with_refs.yml
  tests/unit/diag_scripts/shared/test_iris_helpers.py
Labels: diagnostic

#2613 Add a tool for comparing recipe runs to previous runs
  doc/sphinx/source/community/release_strategy.rst
  doc/sphinx/source/utils.rst
  esmvaltool/utils/testing/regression/compare.py
Labels: testing

#2673 Ignore NCL interface files when comparing recipe runs
  esmvaltool/utils/testing/regression/compare.py
Labels: testing

#2683 Restore accidentally deleted text from input data docs
  doc/sphinx/source/input.rst
Labels: documentation

#2692 Add running settings note in `recipe_wenzel16nat.yml` documentation
  doc/sphinx/source/recipes/recipe_wenzel16nat.rst
Labels: documentation

#2515 Cmorize NOAAGlobalTemp dataset
  doc/sphinx/source/input.rst
  esmvaltool/cmorizers/data/cmor_config/NOAAGlobalTemp.yml
  esmvaltool/cmorizers/data/datasets.yml
  esmvaltool/cmorizers/data/downloaders/datasets/noaaglobaltemp.py
  esmvaltool/cmorizers/data/formatters/datasets/noaaglobaltemp.py
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/noaaglobaltemp.bibtex
Labels: observations, IPCC

#2696 Update documentation on ESMValTool module at DKRZ
  doc/sphinx/source/quickstart/installation.rst
Labels: documentation
