Repository ESMValGroup/ESMValTool, pull requests merged in 2022-02, with the labels that each got.

#2507 Unify user configuration file
  config-user-example.yml
Labels: documentation

#2487 Renamed vertical regridding schemes in affected recipes
  esmvaltool/recipes/recipe_collins13ipcc.yml
  esmvaltool/recipes/recipe_ocean_bgc.yml
  esmvaltool/recipes/recipe_ocean_example.yml
Labels: requires new ESMValCore release, deprecated feature

#2492 Pin `flake8<4` to have actual FLAKE8 error printed if tests fail and not garbage
  package/meta.yaml
  setup.py
Labels: enhancement, testing

#2516 Synchronized `config-user.yml` with version from ESMValCore
  config-user-example.yml
Labels: documentation

#2517 CITATION.cff fix and automatic validation of your citation metadata
  .github/workflows/citation_file_validator.yml
  CITATION.cff
Labels: enhancement, documentation

#2431 Add backwards incompatible changes at the top of the release notes draft
  esmvaltool/utils/draft_release_notes.py
Labels: documentation

#2523 Fixed intersphinx mapping of `scipy`
  doc/sphinx/source/conf.py
Labels: documentation

#2525 Add authors to citation cff
  .zenodo.json
  CITATION.cff
Labels: documentation

#2530 [Docker] Update Docker container builds with correct installations of Julia
  docker/Dockerfile
  docker/Dockerfile.dev
  docker/Dockerfile.exp
Labels: enhancement, installation, testing, deployment

#2531 Update intersphinx mapping
  doc/sphinx/source/conf.py
Labels: bug, documentation

#2432 Update documentation on running a recipe
  doc/sphinx/source/quickstart/running.rst
  doc/sphinx/source/utils.rst
Labels: documentation

#2519 Expanded `recipe_preprocessor_test.yml` to account for new `multi_model_statistics` features
  esmvaltool/recipes/examples/recipe_preprocessor_test.yml
Labels: enhancement, requires new ESMValCore release

#2441 Add recipe and diagnostic scripts to compute figures of D9.4 of ISENES3
  doc/sphinx/source/recipes/figures/examples/decadal_first_example.png
  doc/sphinx/source/recipes/recipe_examples.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/examples/decadal_example.py
  esmvaltool/recipes/examples/recipe_decadal.yml
  tests/integration/test_recipes_loading.py
Labels: diagnostic, is-enes, requires new ESMValCore release

#2536 [condalock] force condalock file creation and initialize automatic PR while Core is RC
  .github/workflows/create-condalock-file.yml
  conda-linux-64.lock
Labels: testing, condalock

#2540 Fixed `KeyError` in `recipe_ocean_bgc.yml`
  esmvaltool/diag_scripts/ocean/diagnostic_model_vs_obs.py
Labels: bug

#2541 Fixed `recipe_kcs.yml`
  esmvaltool/diag_scripts/kcs/global_matching.py
Labels: bug

#2223 Use years from KCS recipe
  doc/sphinx/source/recipes/recipe_kcs.rst
  esmvaltool/diag_scripts/kcs/global_matching.py
  esmvaltool/diag_scripts/kcs/local_resampling.py
Labels: diagnostic, approved by technical reviewer

#2545 Fix MDER diagnostic regression_stepwise
  esmvaltool/diag_scripts/mder/regression_stepwise.ncl
Labels: bug

#2547 Fix for recipe_wenzel16nat
  esmvaltool/recipes/recipe_wenzel16nat.yml
Labels: bug

#2548 Reduced time range in `recipe_globwat.yml`
  esmvaltool/recipes/hydrology/recipe_globwat.yml
Labels: enhancement

#2549 Fix recipe `hydrology/recipe_wflow.yml`
  doc/sphinx/source/recipes/recipe_hydrology.rst
  esmvaltool/recipes/hydrology/recipe_wflow.yml
Labels: documentation, release

#2553 Update `draft_release_notes.py` for new release
  esmvaltool/utils/draft_release_notes.py
Labels: documentation, release

#2558 Fixed `recipe_carvalhais14nat` and removed deprecated use of np.float
  esmvaltool/diag_scripts/land_carbon_cycle/diag_global_turnover.py
  esmvaltool/diag_scripts/mlr/__init__.py
Labels: bug, release

#2184 Recipe to plot generic output from the preprocessor
  .gitignore
  doc/sphinx/source/faq.rst
  doc/sphinx/source/recipes/figures/monitor/annualcycle.png
  doc/sphinx/source/recipes/figures/monitor/clim.png
  doc/sphinx/source/recipes/figures/monitor/monclim.png
  doc/sphinx/source/recipes/figures/monitor/seasonclim.png
  doc/sphinx/source/recipes/figures/monitor/timeseries.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_monitor.rst
  esmvaltool/diag_scripts/monitor/__init__.py
  esmvaltool/diag_scripts/monitor/compute_eofs.py
  esmvaltool/diag_scripts/monitor/monitor.py
  esmvaltool/diag_scripts/monitor/monitor_base.py
  esmvaltool/diag_scripts/monitor/monitor_config.yml
  esmvaltool/recipes/recipe_monitor.yml
  setup.py
Labels: diagnostic, is-enes, in technical review, in scientific review
