Repository ESMValGroup/ESMValTool, pull requests merged in 2022-09, with the labels that each got.

#2788 Fixed small bug that could lead to wrong pr units in `monitor/multi_datasets.py`
  esmvaltool/diag_scripts/monitor/multi_datasets.py
Labels: bug

#2790 Added option to show basic statistics in plots of `monitor/multi_datasets.py`
  esmvaltool/diag_scripts/monitor/multi_datasets.py
Labels: enhancement

#2780 Pin `xgboost>1.6.1` so we avert documentation failing to build with `1.6.1`
  environment.yml
  environment_osx.yml
  setup.py
Labels: bug, documentation, deployment

#2784 add MO-paths to config file
  config-user-example.yml
Labels: documentation, community

#2791 use command with current command line opts for `cffconvert` in documentation
  doc/sphinx/source/community/code_documentation.rst
Labels: documentation

#2795 Update CMORizer documentation with command options
  doc/sphinx/source/develop/dataset.rst
  doc/sphinx/source/input.rst
Labels: documentation

#2796 Pin `netcdf4 != 1.6.1` since that is spitting large numbers of SegFaults
  environment.yml
  environment_osx.yml
  setup.py
Labels: installation, testing
