Repository ESMValGroup/ESMValTool, pull requests merged in 2022-05, with the labels that each got.

#2642 Compute bias instead of correlation in `compare_salinity.py`
  doc/sphinx/source/recipes/figures/sea_surface_salinity/radar.png
  doc/sphinx/source/recipes/figures/sea_surface_salinity/radar_bias.png
  doc/sphinx/source/recipes/figures/sea_surface_salinity/radar_std.png
  doc/sphinx/source/recipes/recipe_sea_surface_salinity.rst
  esmvaltool/diag_scripts/sea_surface_salinity/compare_salinity.py
  esmvaltool/recipes/recipe_sea_surface_salinity.yml
Labels: in scientific review, approved by technical reviewer

#2608 Update monitor diagnostics
  doc/sphinx/source/recipes/recipe_monitor.rst
  esmvaltool/diag_scripts/monitor/compute_eofs.py
  esmvaltool/diag_scripts/monitor/monitor.py
  esmvaltool/diag_scripts/monitor/monitor_base.py
  esmvaltool/diag_scripts/monitor/monitor_config.yml
Labels: diagnostic

#2513 Cmorize Kadow2020 dataset
  doc/sphinx/source/input.rst
  esmvaltool/cmorizers/data/cmor_config/Kadow2020.yml
  esmvaltool/cmorizers/data/datasets.yml
  esmvaltool/cmorizers/data/downloaders/datasets/kadow2020.py
  esmvaltool/cmorizers/data/formatters/datasets/kadow2020.py
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/kadow20natgeosc.bibtex
Labels: observations, IPCC

#2653 Add new Psyplot diagnostic
  doc/sphinx/source/api/esmvaltool.diag_scripts.psyplot_diag.rst
  doc/sphinx/source/api/esmvaltool.diag_scripts.rst
  doc/sphinx/source/api/esmvaltool.rst
  doc/sphinx/source/conf.py
  doc/sphinx/source/faq.rst
  doc/sphinx/source/recipes/figures/psyplot/psyplot_CanESM5.jpg
  doc/sphinx/source/recipes/figures/psyplot/psyplot_ICON-ESM-LR.jpg
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_psyplot.rst
  environment.yml
  environment_osx.yml
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/psyplot_diag.py
  esmvaltool/recipes/recipe_psyplot.yml
  esmvaltool/references/sommer17joss.bibtex
  setup.py
Labels: diagnostic

#2651 Provenance in ocean diagnostics
  esmvaltool/diag_scripts/ocean/diagnostic_maps.py
  esmvaltool/diag_scripts/ocean/diagnostic_maps_multimodel.py
  esmvaltool/diag_scripts/ocean/diagnostic_maps_quad.py
  esmvaltool/diag_scripts/ocean/diagnostic_model_vs_obs.py
  esmvaltool/diag_scripts/ocean/diagnostic_profiles.py
  esmvaltool/diag_scripts/ocean/diagnostic_seaice.py
  esmvaltool/diag_scripts/ocean/diagnostic_timeseries.py
  esmvaltool/diag_scripts/ocean/diagnostic_tools.py
  esmvaltool/diag_scripts/ocean/diagnostic_transects.py
Labels: diagnostic

#2655 Deprecate the function `esmvaltool.diag_scripts.shared.var_name_constraint`
  doc/sphinx/source/api/esmvaltool.diag_scripts.shared.rst
  esmvaltool/cmorizers/data/formatters/datasets/aphro_ma.py
  esmvaltool/cmorizers/data/formatters/datasets/berkeleyearth.py
  esmvaltool/cmorizers/data/formatters/datasets/cds_satellite_albedo.py
  esmvaltool/cmorizers/data/formatters/datasets/cds_satellite_lai_fapar.py
  esmvaltool/cmorizers/data/formatters/datasets/cds_uerra.py
  esmvaltool/cmorizers/data/formatters/datasets/ceres_ebaf.py
  esmvaltool/cmorizers/data/formatters/datasets/cowtanway.py
  esmvaltool/cmorizers/data/formatters/datasets/cru.py
  esmvaltool/cmorizers/data/formatters/datasets/e_obs.py
  esmvaltool/cmorizers/data/formatters/datasets/era_interim.py
  esmvaltool/cmorizers/data/formatters/datasets/ghcn_cams.py
  esmvaltool/cmorizers/data/formatters/datasets/gistemp.py
  esmvaltool/cmorizers/data/formatters/datasets/gpcc.py
  esmvaltool/cmorizers/data/formatters/datasets/grace.py
  esmvaltool/cmorizers/data/formatters/datasets/hadcrut5.py
  esmvaltool/cmorizers/data/formatters/datasets/hwsd.py
  esmvaltool/cmorizers/data/formatters/datasets/kadow2020.py
  esmvaltool/cmorizers/data/formatters/datasets/landflux_eval.py
  esmvaltool/cmorizers/data/formatters/datasets/mte.py
  esmvaltool/cmorizers/data/formatters/datasets/regen.py
  esmvaltool/cmorizers/data/utilities.py
  esmvaltool/diag_scripts/emergent_constraints/ecs_scatter.py
  esmvaltool/diag_scripts/land_carbon_cycle/diag_global_turnover.py
  esmvaltool/diag_scripts/land_carbon_cycle/shared.py
  esmvaltool/diag_scripts/radiation_budget/radiation_budget.py
  esmvaltool/diag_scripts/shared/iris_helpers.py
  tests/unit/diag_scripts/shared/test_iris_helpers.py
Labels: deprecated feature

#2662 Add documentation on building and uploading Docker images
  doc/sphinx/source/community/release_strategy.rst
Labels: documentation
