Repository ESMValGroup/ESMValTool, pull requests merged in 2022-07, with the labels that each got.

#2707 Adapt test_fix_coords to new version of cf-units
  .circleci/install_triggers
  tests/unit/cmorizers/test_utilities.py
Labels: bug

#2706 Fixed order of variables in perfemetrics plot of Anav13jclim recipe
  esmvaltool/recipes/recipe_anav13jclim.yml
Labels: enhancement

#2710 Added input file sorting to many diagnostic to make output exactly reproducible
  esmvaltool/diag_scripts/climate_metrics/ecs.py
  esmvaltool/diag_scripts/climate_metrics/feedback_parameters.py
  esmvaltool/diag_scripts/climate_metrics/psi.py
  esmvaltool/diag_scripts/climate_metrics/tcr.py
  esmvaltool/diag_scripts/emergent_constraints/cox18nature.py
  esmvaltool/diag_scripts/emergent_constraints/ecs_scatter.py
  esmvaltool/diag_scripts/ipcc_ar5/ch09_fig09_42a.py
  esmvaltool/diag_scripts/mlr/__init__.py
  esmvaltool/diag_scripts/shared/io.py
  tests/unit/diag_scripts/mlr/test_helpers.py
  tests/unit/diag_scripts/shared/test_io.py
Labels: enhancement

#2713 Removed 'ancestors' attributes before saving netcdf files in diagnostics
  esmvaltool/diag_scripts/emergent_constraints/ecs_scatter.py
Labels: enhancement

#2709 Expanded recipe output comparison tool to better handle absolute paths in output
  esmvaltool/utils/testing/regression/compare.py
Labels: enhancement, testing

#2677 collecting github user names for config-references
  esmvaltool/config-references.yml
Labels: approved by technical reviewer

#2717 Add note on how to run recipe_wenzel14jgr.yml
  doc/sphinx/source/recipes/recipe_wenzel14jgr.rst
Labels: documentation, release

#2679 Fix the format of ids in Hype forcing files
  esmvaltool/diag_scripts/hydrology/hype.py
Labels: approved by technical reviewer

#2555 added conda forge feedstock repo link in README
  README.md
Labels: documentation

#2731 Add option to CMORize ts as tos in ESACCI data
  esmvaltool/cmorizers/data/cmor_config/ESACCI-SST.yml
Labels: observations

#2663 Update development infrastructure
  .circleci/config.yml
  .dockerignore
  .github/workflows/citation_file_validator.yml
  .github/workflows/create-condalock-file.yml
  .github/workflows/install-from-conda.yml
  .github/workflows/install-from-condalock-file.yml
  .github/workflows/install-from-source.yml
  .github/workflows/pypi-build-and-deploy.yml
  .github/workflows/run-tests-monitor.yml
  .github/workflows/test-development.yml
  .github/workflows/test.yml
  .readthedocs.yaml
  .stickler.yml
  doc/sphinx/source/api/esmvaltool.diag_scripts.mlr/custom_sklearn.rst
  doc/sphinx/source/community/code_documentation.rst
  doc/sphinx/source/community/release_strategy.rst
  doc/sphinx/source/conf.py
  doc/sphinx/source/quickstart/installation.rst
  doc/sphinx/source/requirements.txt
  docker/Dockerfile
  docker/Dockerfile.dev
  docker/Dockerfile.exp
  environment.yml
  environment_osx.yml
  esmvaltool/__init__.py
  esmvaltool/install/R/r_requirements.yml
  esmvaltool/install/R/setup.R
  pyproject.toml
  setup.py
Labels: installation, testing

#2727 Update common_climdex_preprocessing_for_plots.R
  esmvaltool/diag_scripts/extreme_events/common_climdex_preprocessing_for_plots.R
Labels: bug

#2740 Update changelog and dependencies for version 2.6
  doc/sphinx/source/changelog.rst
  environment.yml
  environment_osx.yml
  esmvaltool/utils/draft_release_notes.py
Labels: release

#2738 Increase ESMValTool version to 2.6.0
  CITATION.cff
Labels: documentation, release

#2747 Update release schedule for v2.7
  doc/sphinx/source/community/release_strategy.rst
Labels: documentation
