Repository ESMValGroup/ESMValTool, pull requests merged in 2022-12, with the labels that each got.

#2954 Updated ICON dataset entry in documentation
  doc/sphinx/source/input.rst
Labels: documentation

#2952 Update documentation and recipe_check_obs (ERA5)
  doc/sphinx/source/input.rst
  esmvaltool/recipes/examples/recipe_check_obs.yml
Labels: documentation, observations, looking for technical reviewer, looking for scientific reviewer

#2961 Fix failing tests that use deprecated feature of sklearn
  tests/integration/diag_scripts/mlr/test_custom_sklearn_functions.py
Labels: testing

#2970 Pin shapely<2.0.0 for linux64
  environment.yml
  setup.py
Labels: installation

#2958 Update data finder imports
  environment.yml
  environment_osx.yml
  esmvaltool/diag_scripts/monitor/monitor_base.py
  setup.py
  tests/integration/test_recipes_loading.py
Labels: enhancement
