Repository ESMValGroup/ESMValTool, pull requests merged in 2022-08, with the labels that each got.

#2752 Update CERES-EBAF to Ed4.1
  esmvaltool/cmorizers/data/cmor_config/CERES-EBAF.yml
  esmvaltool/cmorizers/data/datasets.yml
  esmvaltool/cmorizers/data/formatters/datasets/ceres_ebaf.py
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/ceres-ebaf-ed41.bibtex
Labels: observations, Data

#2761 Remove installation of R dependencies from the help message
  esmvaltool/install/__init__.py
Labels: bug, backwards incompatible change

#2751 Add Met Office installation method
  doc/sphinx/source/quickstart/installation.rst
Labels: documentation

#2753 New CMORizer for CALIPSO-ICECLOUD
  doc/sphinx/source/input.rst
  esmvaltool/cmorizers/data/datasets.yml
  esmvaltool/cmorizers/data/downloaders/datasets/calipso_icecloud.py
  esmvaltool/cmorizers/data/formatters/datasets/calipso_icecloud.ncl
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/calipso-icecloud.bibtex
Labels: observations, Data

#2052 Recipe and diagnostics for : Tebaldi et al.,ESD, 2021
  doc/sphinx/source/recipes/figures/tebaldi21esd/pr_pattern.png
  doc/sphinx/source/recipes/figures/tebaldi21esd/tas_timeseries.png
  doc/sphinx/source/recipes/figures/tebaldi21esd/warming_level_table.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_tebaldi21esd.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/shared/plot/rgb/categorical_fig5.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc_color_ssp_tseries.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc_prec_div_14.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc_prec_seq_14.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc_prec_seq_7.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc_temp_div_10.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc_temp_div_18.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc_temp_seq_14.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc_temp_seq_9.rgb
  esmvaltool/diag_scripts/tebaldi21esd/calc_IAV_hatching.ncl
  esmvaltool/diag_scripts/tebaldi21esd/calc_cmip6_and_cmip5_pattern_diff_scaleT.ncl
  esmvaltool/diag_scripts/tebaldi21esd/calc_pattern_comparison.ncl
  esmvaltool/diag_scripts/tebaldi21esd/calc_pattern_diff_scaleT.ncl
  esmvaltool/diag_scripts/tebaldi21esd/calc_pattern_intermodel_stddev_scaleT.ncl
  esmvaltool/diag_scripts/tebaldi21esd/calc_pattern_interscenario_stddev_scaleT.ncl
  esmvaltool/diag_scripts/tebaldi21esd/calc_pattern_stddev_scaleT.ncl
  esmvaltool/diag_scripts/tebaldi21esd/calc_pattern_stippling_hatching.ncl
  esmvaltool/diag_scripts/tebaldi21esd/calc_table_changes.ncl
  esmvaltool/diag_scripts/tebaldi21esd/calc_table_warming_level.ncl
  esmvaltool/diag_scripts/tebaldi21esd/calc_timeseries_across_realization_stddev_runave.ncl
  esmvaltool/diag_scripts/tebaldi21esd/calc_timeseries_mean_spread_runave.ncl
  esmvaltool/diag_scripts/tebaldi21esd/calc_timeseries_mean_spread_ssp4.ncl
  esmvaltool/diag_scripts/tebaldi21esd/calc_timeseries_mean_spread_ssp5.ncl
  esmvaltool/diag_scripts/tebaldi21esd/plot_pattern.ncl
  esmvaltool/diag_scripts/tebaldi21esd/plot_table_changes.ncl
  esmvaltool/diag_scripts/tebaldi21esd/plot_table_warming_level.ncl
  esmvaltool/diag_scripts/tebaldi21esd/plot_timeseries_across_realization_stddev_runave.ncl
  esmvaltool/diag_scripts/tebaldi21esd/plot_timeseries_mean_spread.ncl
  esmvaltool/diag_scripts/tebaldi21esd/plot_timeseries_mean_spread_3scenarios.ncl
  esmvaltool/diag_scripts/tebaldi21esd/plot_timeseries_mean_spread_constrained_projections.ncl
  esmvaltool/diag_scripts/tebaldi21esd/plot_timeseries_mean_spread_rightaxis_5scen.ncl
  esmvaltool/diag_scripts/tebaldi21esd/plot_timeseries_mean_spread_ssp4.ncl
  esmvaltool/diag_scripts/tebaldi21esd/plot_timeseries_mean_spread_ssp5.ncl
  esmvaltool/recipes/recipe_tebaldi21esd.yml
  esmvaltool/references/tebaldi21esd.bibtex
Labels: diagnostic, approved by technical reviewer, approved by scientific reviewer

#2754 New CMORizer for CLOUDSAT-L2
  doc/sphinx/source/input.rst
  esmvaltool/cmorizers/data/datasets.yml
  esmvaltool/cmorizers/data/formatters/datasets/cloudsat_l2.ncl
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/stephens17bams.bibtex
Labels: observations, Data

#2758 Fix misplaced provenance records from IPCC AR5 Ch.12 diags
  esmvaltool/diag_scripts/ipcc_ar5/ch12_calc_IAV_for_stippandhatch.ncl
  esmvaltool/diag_scripts/ipcc_ar5/ch12_plot_ts_line_mean_spread.ncl
Labels: bug, diagnostic

#2769 Add release dates for 2023
  doc/sphinx/source/community/release_strategy.rst
Labels: documentation, release

#2703 Made `maintainer` entry mandatory for published recipes
  doc/sphinx/source/community/diagnostic.rst
  doc/sphinx/source/community/review.rst
  esmvaltool/config-references.yml
  esmvaltool/recipes/cmorizers/recipe_daily_era5.yml
  esmvaltool/recipes/cmorizers/recipe_era5-land.yml
  esmvaltool/recipes/examples/recipe_decadal.yml
  esmvaltool/recipes/hydrology/recipe_hydro_forcing.yml
  esmvaltool/recipes/hydrology/recipe_hype.yml
  esmvaltool/recipes/hydrology/recipe_lisflood.yml
  esmvaltool/recipes/hydrology/recipe_marrmot.yml
  esmvaltool/recipes/hydrology/recipe_pcrglobwb.yml
  esmvaltool/recipes/hydrology/recipe_wflow.yml
  esmvaltool/recipes/monitor/recipe_monitor.yml
  esmvaltool/recipes/monitor/recipe_monitor_with_refs.yml
  esmvaltool/recipes/mpqb/recipe_mpqb_xch4.yml
  esmvaltool/recipes/recipe_albedolandcover.yml
  esmvaltool/recipes/recipe_anav13jclim.yml
  esmvaltool/recipes/recipe_capacity_factor.yml
  esmvaltool/recipes/recipe_climate_change_hotspot.yml
  esmvaltool/recipes/recipe_cmug_h2o.yml
  esmvaltool/recipes/recipe_combined_indices.yml
  esmvaltool/recipes/recipe_consecdrydays.yml
  esmvaltool/recipes/recipe_diurnal_temperature_index.yml
  esmvaltool/recipes/recipe_ecs.yml
  esmvaltool/recipes/recipe_extreme_index.yml
  esmvaltool/recipes/recipe_heatwaves_coldwaves.yml
  esmvaltool/recipes/recipe_kcs.yml
  esmvaltool/recipes/recipe_li17natcc.yml
  esmvaltool/recipes/recipe_martin18grl.yml
  esmvaltool/recipes/recipe_miles_block.yml
  esmvaltool/recipes/recipe_miles_eof.yml
  esmvaltool/recipes/recipe_miles_regimes.yml
  esmvaltool/recipes/recipe_modes_of_variability.yml
  esmvaltool/recipes/recipe_multimodel_products.yml
  esmvaltool/recipes/recipe_radiation_budget.yml
  esmvaltool/recipes/recipe_rainfarm.yml
  esmvaltool/recipes/recipe_shapeselect.yml
  esmvaltool/recipes/recipe_spei.yml
  esmvaltool/recipes/recipe_tcr.yml
  esmvaltool/recipes/recipe_thermodyn_diagtool.yml
  esmvaltool/recipes/recipe_toymodel.yml
  esmvaltool/recipes/recipe_wenzel14jgr.yml
  esmvaltool/recipes/recipe_wenzel16jclim.yml
  esmvaltool/recipes/recipe_wenzel16nat.yml
  tests/unit/test_recipes.py
Labels: documentation

#2533 Figures for IPCC AR6 WG1 Chapter 3 (Atmosphere)
  doc/sphinx/source/recipes/figures/ipccwg1ar6ch3/gsat_Global_CMIP6_historical-ssp245_anom_1850-2020.png
  doc/sphinx/source/recipes/figures/ipccwg1ar6ch3/gsat_Global_multimodel_anom_1850-2020.png
  doc/sphinx/source/recipes/figures/ipccwg1ar6ch3/model_bias_pr_annualclim_CMIP6.png
  doc/sphinx/source/recipes/figures/ipccwg1ar6ch3/model_bias_tas_annualclim_CMIP6.png
  doc/sphinx/source/recipes/figures/ipccwg1ar6ch3/precip_anom_1950-2014.png
  doc/sphinx/source/recipes/figures/ipccwg1ar6ch3/tas_std_dev_zonmean.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_collins13ipcc.rst
  doc/sphinx/source/recipes/recipe_ipccwg1ar6ch3.rst
  esmvaltool/diag_scripts/ipcc_ar5/ch12_calc_IAV_for_stippandhatch.ncl
  esmvaltool/diag_scripts/ipcc_ar6/model_bias.ncl
  esmvaltool/diag_scripts/ipcc_ar6/percentiles.ncl
  esmvaltool/diag_scripts/ipcc_ar6/precip_anom.ncl
  esmvaltool/diag_scripts/ipcc_ar6/tas_anom.ncl
  esmvaltool/diag_scripts/ipcc_ar6/tsline_collect.ncl
  esmvaltool/diag_scripts/ipcc_ar6/zonal_st_dev.ncl
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_cmip_line.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_cmip_shading.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_damip_line.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_damip_shading.rgb
  esmvaltool/diag_scripts/shared/plot/rgb/ipcc-ar6_temperature_seq.rgb
  esmvaltool/diag_scripts/shared/plot/styles/cmip6_ipcc.style
  esmvaltool/diag_scripts/shared/plot/xy_line.ncl
  esmvaltool/diag_scripts/shared/statistics.ncl
  esmvaltool/recipes/ipccwg1ar6ch3/recipe_ipccwg1ar6ch3_atmosphere.yml
  esmvaltool/references/eyring21ipcc.bibtex
Labels: diagnostic, approved by technical reviewer, approved by scientific reviewer, IPCC

#2778 Fix `esmvaltool.utils.testing.regression.compare` module to run with Python<3.10 too
  esmvaltool/utils/testing/regression/compare.py
  tests/unit/utils/test_compare.py
Labels: bug, deployment
