Repository ESMValGroup/ESMValTool, pull requests merged in 2023-01, with the labels that each got.

#2957 Bugfix: masking of non-significant differences in zonal.ncl (perfmetrics)
  esmvaltool/diag_scripts/perfmetrics/zonal.ncl
Labels: bug, diagnostic, approved by technical reviewer, approved by scientific reviewer

#2997 recipe_ocean_Landschuetzer2016: Fix typo in filename to run model vs OBS diagnostics
  esmvaltool/recipes/recipe_ocean_Landschuetzer2016.yml
Labels: bug

#2964 Set the version number on the development branches to one minor version more than the last release
  pyproject.toml
Labels: installation

#2976 Fix .png bug in wenzel16nat diagnostics
  esmvaltool/diag_scripts/carbon_ec/carbon_beta.ncl
  esmvaltool/diag_scripts/carbon_ec/carbon_co2_cycle.ncl
Labels: bug, diagnostic, approved by technical reviewer, approved by scientific reviewer

#2955 fix in validation.py for resolving datasets with identical names by using distinct alias
  esmvaltool/diag_scripts/shared/_validation.py
  esmvaltool/diag_scripts/validation.py
Labels: bug, diagnostic, EMAC

#3001 add Franziska Winterstein as collaborator in CITATION file
  CITATION.cff
  esmvaltool/config-references.yml
Labels: documentation

#2856 Adding IPCC AR6 Chapter 3 Fig. 3.42 - Perfmetrics
  doc/sphinx/source/recipes/figures/ipccwg1ar6ch3/fig_3_42_a.png
  doc/sphinx/source/recipes/recipe_ipccwg1ar6ch3.rst
  esmvaltool/diag_scripts/perfmetrics/collect.ncl
  esmvaltool/diag_scripts/perfmetrics/cycle_latlon.ncl
  esmvaltool/diag_scripts/perfmetrics/main.ncl
  esmvaltool/diag_scripts/shared/plot/portrait_plot.ncl
  esmvaltool/recipes/ipccwg1ar6ch3/recipe_ipccwg1ar6ch3_fig_3_42_a.yml
  esmvaltool/recipes/ipccwg1ar6ch3/recipe_ipccwg1ar6ch3_fig_3_42_b.yml
  esmvaltool/references/eyring21ipcc.bibtex
Labels: diagnostic, approved by technical reviewer, approved by scientific reviewer, IPCC

#3007 Fix read_cmor in NCL utilities
  esmvaltool/cmorizers/data/formatters/utilities.ncl
Labels: bug, observations, approved by technical reviewer

#3002 obs4mips CERES-EBAF: update version to latest available through esgf in recipe_validation.yml
  esmvaltool/recipes/recipe_validation.yml
Labels: diagnostic, Data

#3009 Removed usages of deprecated features that cause diagnostic crashes
  esmvaltool/cmorizers/data/formatters/datasets/berkeleyearth.py
  esmvaltool/cmorizers/data/formatters/datasets/ndp.py
  esmvaltool/diag_scripts/autoassess/land_surface_permafrost/permafrost.py
  esmvaltool/diag_scripts/deangelis15nat/deangelisf1b.py
  esmvaltool/diag_scripts/deangelis15nat/deangelisf3f4.py
  esmvaltool/diag_scripts/emergent_constraints/__init__.py
  esmvaltool/diag_scripts/ensclus/ens_plots.py
  esmvaltool/diag_scripts/kcs/local_resampling.py
  esmvaltool/diag_scripts/land_carbon_cycle/diag_zonal_correlation.py
  esmvaltool/diag_scripts/land_carbon_cycle/diag_zonal_turnover.py
  esmvaltool/diag_scripts/land_carbon_cycle/shared.py
  esmvaltool/diag_scripts/mlr/custom_sklearn.py
  esmvaltool/diag_scripts/mlr/models/__init__.py
  esmvaltool/diag_scripts/runoff_et/catchment_analysis.py
Labels: bug

#2951 Update documentation for recipe_extreme_index
  doc/sphinx/source/recipes/figures/recipe_extreme_index/t90p_IPSL-CM5A-LR_rcp85_2020_2040.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_extreme_index.rst
Labels: documentation

#3010 Update release schedule for v2.7.0 and v2.8.0
  doc/sphinx/source/community/release_strategy.rst
Labels: documentation

#3016 Improve flexibility of cloud diagnostics
  doc/sphinx/source/recipes/recipe_clouds.rst
  esmvaltool/diag_scripts/clouds/clouds.ncl
  esmvaltool/diag_scripts/clouds/clouds_bias.ncl
  esmvaltool/diag_scripts/clouds/clouds_dyn_matrix.ncl
  esmvaltool/diag_scripts/clouds/clouds_interannual.ncl
  esmvaltool/diag_scripts/clouds/clouds_ipcc.ncl
  esmvaltool/diag_scripts/clouds/clouds_lifrac_scatter.ncl
  esmvaltool/diag_scripts/clouds/clouds_pdf.ncl
  esmvaltool/diag_scripts/clouds/clouds_scatter.ncl
  esmvaltool/diag_scripts/clouds/clouds_seasonal_cycle.ncl
  esmvaltool/diag_scripts/clouds/clouds_taylor.ncl
  esmvaltool/diag_scripts/clouds/clouds_zonal.ncl
Labels: enhancement, diagnostic, approved by technical reviewer, approved by scientific reviewer

#3028 add ESMValCore Bugfix release v2.7.1 to the release overview table
  doc/sphinx/source/community/release_strategy.rst
Labels: documentation

#3027 Update HadISST cmorizer with recent years
  esmvaltool/cmorizers/data/formatters/datasets/hadisst.ncl
  esmvaltool/recipes/examples/recipe_check_obs.yml
Labels: observations, approved by technical reviewer, approved by scientific reviewer

#3020 Fix recipe loading tests for esmvalcore before and after version 2.8
  tests/integration/test_recipes_loading.py
  tests/system/data_simulator.py
Labels: testing

#3029 Updated monitoring diagnostics with netCDF output and additional logging
  esmvaltool/diag_scripts/monitor/multi_datasets.py
Labels: enhancement, diagnostic, approved by technical reviewer, approved by scientific reviewer

#2931 New CMORizers for datasets from the NCEP family
  doc/sphinx/source/input.rst
  esmvaltool/cmorizers/data/cmor_config/NCEP-DOE-R2.yml
  esmvaltool/cmorizers/data/cmor_config/NCEP-NCAR-R1.yml
  esmvaltool/cmorizers/data/cmor_config/NOAA-CIRES-20CR.yml
  esmvaltool/cmorizers/data/datasets.yml
  esmvaltool/cmorizers/data/downloaders/datasets/ncep_doe_r2.py
  esmvaltool/cmorizers/data/downloaders/datasets/ncep_ncar_r1.py
  esmvaltool/cmorizers/data/downloaders/datasets/noaa_cires_20cr.py
  esmvaltool/cmorizers/data/formatters/datasets/ncep.ncl
  esmvaltool/cmorizers/data/formatters/datasets/ncep_doe_r2.py
  esmvaltool/cmorizers/data/formatters/datasets/ncep_ncar_r1.py
  esmvaltool/cmorizers/data/formatters/datasets/noaa_cires_20cr.py
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/ncep-doe-r2.bibtex
  esmvaltool/references/ncep-ncar-r1.bibtex
  esmvaltool/references/noaa-cires-20cr.bibtex
Labels: observations, approved by technical reviewer, approved by scientific reviewer, Data

#2932 Updates to the recipes that use the NCEP reanalysis dataset
  doc/sphinx/source/recipes/recipe_bock20jgr.rst
  doc/sphinx/source/recipes/recipe_ipccwg1ar6ch3.rst
  doc/sphinx/source/recipes/recipe_perfmetrics.rst
  doc/sphinx/source/recipes/recipe_wenzel14jgr.rst
  esmvaltool/recipes/bock20jgr/recipe_bock20jgr_fig_6-7.yml
  esmvaltool/recipes/ipccwg1ar6ch3/recipe_ipccwg1ar6ch3_fig_3_42_a.yml
  esmvaltool/recipes/recipe_flato13ipcc.yml
  esmvaltool/recipes/recipe_perfmetrics_CMIP5.yml
  esmvaltool/recipes/recipe_perfmetrics_CMIP5_4cds.yml
  esmvaltool/recipes/recipe_wenzel14jgr.yml
Labels: observations

#2986 Adding IPCC AR6 Chapter 3 Fig. 3.9 - Attribution
  doc/sphinx/source/recipes/figures/ipccwg1ar6ch3/tas_anom_damip_global_1850-2020.png
  doc/sphinx/source/recipes/recipe_ipccwg1ar6ch3.rst
  esmvaltool/diag_scripts/ipcc_ar6/tas_anom_damip.ncl
  esmvaltool/recipes/ipccwg1ar6ch3/recipe_ipccwg1ar6ch3_fig_3_9.yml
  esmvaltool/references/iturbide20essd.bibtex
Labels: diagnostic, approved by technical reviewer, approved by scientific reviewer, IPCC
