Repository ESMValGroup/ESMValTool, pull requests merged in 2023-10, with the labels that each got.

#3367 Remove deprecated option `offline` from CI configuration
  .circleci/config.yml
Labels: testing

#3375 replace Anaconda badge with dynamicl shield on README entry page
  README.md
Labels: documentation

#3394 Simplify configure task in recipe test workflow
  esmvaltool/utils/recipe_test_workflow/doc/source/user_guide/workflow.rst
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/app/configure/bin/configure.py
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/flow.cylc
Labels: Recipe Test Workflow (RTW)

#3397 Fix documentation build
  doc/sphinx/source/conf.py
Labels: documentation

#3356 Add a realistic example recipe
  doc/sphinx/source/recipes/figures/examples/IPCC_AR6_figure_9.3a_1850-2100.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_examples.rst
  esmvaltool/diag_scripts/examples/make_plot.py
  esmvaltool/recipes/examples/recipe_easy_ipcc.yml
  esmvaltool/references/fox-kemper21ipcc.bibtex
Labels: new recipe
