Repository ESMValGroup/ESMValTool, pull requests merged in 2023-03, with the labels that each got.

#3049 Removed automatic conversion of precipitation units from monitoring diagnostic
  esmvaltool/diag_scripts/monitor/multi_datasets.py
Labels: backwards incompatible change

#3068 Unpin matplotlib
  environment.yml
  environment_osx.yml
  setup.py
Labels: documentation, installation

#3070 Update script to draft release notes
  esmvaltool/utils/draft_release_notes.py
Labels: documentation, release

#3066 Update release instructions
  doc/sphinx/source/community/release_strategy.rst
Labels: documentation, release

#3073 Synchronize documentation table of contents with ESMValCore
  doc/sphinx/source/gensidebar.py
Labels: documentation

#3078 Added missing comma to `sommer17joss.bibtex`
  esmvaltool/references/sommer17joss.bibtex
Labels: bug

#3072 Test running recipes with the development version of ESMValCore
  .circleci/config.yml
  doc/sphinx/source/community/backward_compatibility.rst
  esmvaltool/recipes/testing/recipe_deangelis15nat_fig1_fast.yml
  tests/integration/test_recipes_loading.py
Labels: testing

#3075 Replace removed `matplotlib.pyplot.savefig` option `additional_artists`
  esmvaltool/diag_scripts/climate_metrics/create_scatterplot.py
  esmvaltool/diag_scripts/climate_metrics/ecs.py
  esmvaltool/diag_scripts/climate_metrics/feedback_parameters.py
  esmvaltool/diag_scripts/emergent_constraints/cox18nature.py
  esmvaltool/diag_scripts/ipcc_ar5/ch09_fig09_42b.py
  esmvaltool/diag_scripts/shared/plot/_plot.py
Labels: bug

#3083 Fix call of output_type in aux_plotting.ncl
  esmvaltool/diag_scripts/shared/plot/aux_plotting.ncl
Labels: bug

#3087 Remove colorbar from `bbox_extra_artists`
  esmvaltool/diag_scripts/climate_metrics/feedback_parameters.py
Labels: bug

#3064 Updated recipes for ESMValCore v2.8
  esmvaltool/recipes/monitor/recipe_monitor.yml
  esmvaltool/recipes/monitor/recipe_monitor_with_refs.yml
  esmvaltool/recipes/recipe_anav13jclim.yml
  esmvaltool/recipes/recipe_cox18nature.yml
  esmvaltool/recipes/recipe_ecs.yml
  esmvaltool/recipes/recipe_ecs_constraints.yml
  esmvaltool/recipes/recipe_meehl20sciadv.yml
  esmvaltool/recipes/recipe_russell18jgr.yml
  esmvaltool/recipes/recipe_schlund20esd.yml
  esmvaltool/recipes/recipe_tcr.yml
  esmvaltool/recipes/recipe_wenzel16jclim.yml
  esmvaltool/recipes/schlund20jgr/recipe_schlund20jgr_gpp_abs_rcp85.yml
  esmvaltool/recipes/schlund20jgr/recipe_schlund20jgr_gpp_change_rcp85.yml
Labels: diagnostic, requires new ESMValCore release

#3090 Conda environment files for interim use of `esmvalcore=2.8.0rc1`
  environment.yml
  environment_osx.yml
Labels: testing, release

#3093 Fix `MPI-ESM1-2-HR` entries in `recipe_tebaldi21esd`
  esmvaltool/recipes/recipe_tebaldi21esd.yml
Labels: bug

#2156 Splitting of flato13ipcc.yml into separate recipes and adding recipes for regional Figures
  doc/sphinx/source/recipes/figures/ipccwg1ar5ch9/fig-9-14.png
  doc/sphinx/source/recipes/figures/ipccwg1ar5ch9/fig-9-2.png
  doc/sphinx/source/recipes/figures/ipccwg1ar5ch9/fig-9-26.png
  doc/sphinx/source/recipes/figures/ipccwg1ar5ch9/fig-9-27.png
  doc/sphinx/source/recipes/figures/ipccwg1ar5ch9/fig-9-3.png
  doc/sphinx/source/recipes/figures/ipccwg1ar5ch9/fig-9-38-pr.png
  doc/sphinx/source/recipes/figures/ipccwg1ar5ch9/fig-9-38.png
  doc/sphinx/source/recipes/figures/ipccwg1ar5ch9/fig-9-38_regions.png
  doc/sphinx/source/recipes/figures/ipccwg1ar5ch9/fig-9-39-pr.png
  doc/sphinx/source/recipes/figures/ipccwg1ar5ch9/fig-9-39.png
  doc/sphinx/source/recipes/figures/ipccwg1ar5ch9/fig-9-39_regions.png
  doc/sphinx/source/recipes/figures/ipccwg1ar5ch9/fig-9-4.png
  doc/sphinx/source/recipes/figures/ipccwg1ar5ch9/fig-9-40-pr.png
  doc/sphinx/source/recipes/figures/ipccwg1ar5ch9/fig-9-40.png
  doc/sphinx/source/recipes/figures/ipccwg1ar5ch9/fig-9-40_regions.png
  doc/sphinx/source/recipes/figures/ipccwg1ar5ch9/fig-9-41b.png
  doc/sphinx/source/recipes/figures/ipccwg1ar5ch9/fig-9-42a.png
  doc/sphinx/source/recipes/figures/ipccwg1ar5ch9/fig-9-42b.png
  doc/sphinx/source/recipes/figures/ipccwg1ar5ch9/fig-9-45a.png
  doc/sphinx/source/recipes/figures/ipccwg1ar5ch9/fig-9-5.png
  doc/sphinx/source/recipes/figures/ipccwg1ar5ch9/fig-9-6.png
  doc/sphinx/source/recipes/figures/ipccwg1ar5ch9/fig-9-8.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_ipccwg1ar5ch9.rst
  doc/sphinx/source/recipes/recipe_snowalbedo.rst
  esmvaltool/diag_scripts/regional_downscaling/Figure9.38.ncl
  esmvaltool/diag_scripts/regional_downscaling/Figure9.39.ncl
  esmvaltool/diag_scripts/regional_downscaling/Figure9.40.ncl
  esmvaltool/diag_scripts/regional_downscaling/Figure9.41.ncl
  esmvaltool/diag_scripts/regional_downscaling/regional_function.ncl
  esmvaltool/diag_scripts/shared/plot/styles/cmip356.style
  esmvaltool/recipes/ipccwg1ar5ch9/recipe_flato13ipcc_figure_914.yml
  esmvaltool/recipes/ipccwg1ar5ch9/recipe_flato13ipcc_figure_924.yml
  esmvaltool/recipes/ipccwg1ar5ch9/recipe_flato13ipcc_figure_942.yml
  esmvaltool/recipes/ipccwg1ar5ch9/recipe_flato13ipcc_figure_945a.yml
  esmvaltool/recipes/ipccwg1ar5ch9/recipe_flato13ipcc_figure_96.yml
  esmvaltool/recipes/ipccwg1ar5ch9/recipe_flato13ipcc_figure_98.yml
  esmvaltool/recipes/ipccwg1ar5ch9/recipe_flato13ipcc_figures_926_927.yml
  esmvaltool/recipes/ipccwg1ar5ch9/recipe_flato13ipcc_figures_92_95.yml
  esmvaltool/recipes/ipccwg1ar5ch9/recipe_flato13ipcc_figures_938_941_cmip3.yml
  esmvaltool/recipes/ipccwg1ar5ch9/recipe_flato13ipcc_figures_938_941_cmip6.yml
  esmvaltool/recipes/ipccwg1ar5ch9/recipe_weigel21gmd_figures_13_16.yml
  esmvaltool/recipes/recipe_flato13ipcc.yml
  esmvaltool/references/seneviratne12ipcc.bibtex
Labels: diagnostic, approved by technical reviewer, approved by scientific reviewer

#3097 Fix cos22esd for release of 2.8
  esmvaltool/diag_scripts/cos22esd/climate_change_hotspot.py
  esmvaltool/recipes/recipe_climate_change_hotspot.yml
Labels: diagnostic, approved by technical reviewer, approved by scientific reviewer

#3099 Add `packaging` as direct dependency to ESMValTool
  environment.yml
  environment_osx.yml
  setup.py
Labels: installation

#3101 Fix numpy deprecation in hype diagnostic
  esmvaltool/diag_scripts/hydrology/hype.py
Labels: diagnostic, release

#3098 Fix perfmetrics v2.8.0
  esmvaltool/interface_scripts/auxiliary.ncl
Labels: bug, diagnostic

#3104 Fix the ESACCI-LST CMORizer
  esmvaltool/cmorizers/data/cmor_config/ESACCI-LST.yml
  esmvaltool/cmorizers/data/formatters/datasets/esacci_lst.py
Labels: bug, observations

#3103 Clarify use (or not) of Jasmin climatology files by soil moisture & permafrost recipes
  doc/sphinx/source/recipes/recipe_autoassess_landsurface_permafrost.rst
  doc/sphinx/source/recipes/recipe_autoassess_landsurface_soilmoisture.rst
  esmvaltool/recipes/recipe_autoassess_landsurface_permafrost.yml
Labels: documentation

#3069 Updated docs and tests regarding new `search_esgf` option
  config-user-example.yml
  doc/sphinx/source/input.rst
  doc/sphinx/source/quickstart/running.rst
  tests/integration/test_recipes_loading.py
Labels: documentation, requires new ESMValCore release

#2736 Read config-user.yml using `esmvalcore.config` module
  esmvaltool/cmorizers/data/cmorizer.py
Labels: enhancement

#2883 Add DKRZ/Levante batch scripts for release recipe running
  doc/sphinx/source/utils.rst
  esmvaltool/utils/batch-jobs/generate.py
  esmvaltool/utils/batch-jobs/job_DKRZ-MISTRAL.sh
  esmvaltool/utils/batch-jobs/parse_recipes_output.py
Labels: documentation, testing

#3111 Fix recipe_carvalhais14: replace outline patch with splines
  esmvaltool/diag_scripts/land_carbon_cycle/diag_global_turnover.py
Labels: bug, diagnostic

#3102 Fix recipe_sea_surface_salinity for v2.8
  esmvaltool/diag_scripts/sea_surface_salinity/compare_salinity.py
  esmvaltool/recipes/recipe_sea_surface_salinity.yml
Labels: bug, diagnostic, release

#3114 Improve stratosphere documentation
  doc/sphinx/source/recipes/recipe_autoassess_stratosphere.rst
Labels: documentation

#3117 Removed `fx_variables` in recipe_mpqb_xch4 and recipe_lauer22jclim_fig8
  esmvaltool/recipes/clouds/recipe_lauer22jclim_fig8_dyn.yml
  esmvaltool/recipes/mpqb/recipe_mpqb_xch4.yml
Labels: diagnostic, release

#3096 Update environment handling in release documentation
  doc/sphinx/source/community/release_strategy.rst
Labels: documentation

#3120 Conda environment files for esmvalcore=2.8.0rc2
  environment.yml
  environment_osx.yml
Labels: installation, release

#3058 Use aliases in perfmetrics
  doc/sphinx/source/recipes/recipe_perfmetrics.rst
  esmvaltool/diag_scripts/perfmetrics/cycle_zonal.ncl
  esmvaltool/diag_scripts/perfmetrics/zonal.ncl
Labels: enhancement

#3121 Added note to documentation that not all datasets used in schlund20jgr recipes are available on ESGF
  doc/sphinx/source/recipes/recipe_schlund20jgr.rst
  esmvaltool/recipes/schlund20jgr/recipe_schlund20jgr_gpp_abs_rcp85.yml
  esmvaltool/recipes/schlund20jgr/recipe_schlund20jgr_gpp_change_1pct.yml
  esmvaltool/recipes/schlund20jgr/recipe_schlund20jgr_gpp_change_rcp85.yml
Labels: documentation

#3119 Update Python example recipe
  doc/sphinx/source/recipes/recipe_examples.rst
  esmvaltool/diag_scripts/examples/diagnostic.py
  esmvaltool/recipes/examples/recipe_python.yml
Labels: documentation, diagnostic

#3113 Add link to recipe portal in the gallery page
  doc/sphinx/source/generate_gallery.py
  doc/sphinx/source/recipes/index.rst
Labels: documentation

#3131 Remove rc (release candidates) conda channel and re-pin esmvalcore to new stable 2.8
  environment.yml
  environment_osx.yml
Labels: installation

#3129 Documenting broken recipes after recipe testing for releases
  doc/sphinx/source/community/broken_recipe_policy.rst
  doc/sphinx/source/community/release_strategy/release_strategy.rst
  doc/sphinx/source/recipes/broken_recipe_list.rst
  doc/sphinx/source/recipes/index.rst
Labels: documentation, release

#3133 Updated figure settings to account for newer matplotlib version.
  esmvaltool/diag_scripts/cmug_h2o/diag_tropopause.py
  esmvaltool/diag_scripts/cmug_h2o/diag_tropopause_zonalmean.py
  esmvaltool/diag_scripts/deangelis15nat/deangelisf2ext.py
  esmvaltool/diag_scripts/deangelis15nat/deangelisf3f4.py
Labels: diagnostic, approved by technical reviewer, approved by scientific reviewer

#3130 Update batch script generation to run all recipes in one command
  doc/sphinx/source/community/release_strategy/detailed_release_procedure.rst
  doc/sphinx/source/utils.rst
  esmvaltool/utils/batch-jobs/generate.py
Labels: testing, release

#3136 Increase ESMValTool version to 2.8.0 and update release dates
  CITATION.cff
  doc/sphinx/source/community/release_strategy/release_strategy.rst
Labels: documentation, release

#3144 add jquery sphinx extension to documentation can run Java queries (needed for Search etc)
  doc/sphinx/source/conf.py
Labels: documentation
