Repository ESMValGroup/ESMValTool, pull requests merged in 2023-12, with the labels that each got.

#3447 Adding download_dir to recipe filler.
  esmvaltool/utils/recipe_filler.py
Labels: enhancement

#3417 Add note about not removing communities and grants from .zenodo.json
  doc/sphinx/source/community/code_documentation.rst
Labels: documentation

#3453 regenerate Anconda shield/badge not to have ESMValTool version hardcoded in image name
  README.md
Labels: documentation

#3450 clean up a bit CircleCI configuration
  .circleci/config.yml
Labels: testing

#3457 Add note for the NSDIC cmoriser (requires PROJ9.3)
  doc/sphinx/source/input.rst
Labels: documentation

#3459 [CircleCI] allow for medium (vs small, previously) resources for build documentation test
  .circleci/config.yml
Labels: testing

#3473 Fix obs4MIPs frequency in recipe_bock20jgr_fig_1-4.yml
  esmvaltool/recipes/bock20jgr/recipe_bock20jgr_fig_1-4.yml
Labels: bug

#3475 Adapt to changed style scheme name in matplotlib
  esmvaltool/recipes/recipe_landcover.yml
Labels: diagnostic

#2385 added obs and obs6 locations and access instructions for JASMIN in documentation
  doc/sphinx/source/input.rst
Labels: documentation

#3477 Fix NCL provenance tracking
  esmvaltool/interface_scripts/logging.ncl
Labels: diagnostic

#3342 Extension of CLARA-AVHRR, CLOUDSAT-L2 and ESACCI-CLOUD CMORizers
  doc/sphinx/source/input.rst
  esmvaltool/cmorizers/data/formatters/datasets/clara_avhrr.ncl
  esmvaltool/cmorizers/data/formatters/datasets/cloudsat_l2.ncl
  esmvaltool/cmorizers/data/formatters/datasets/esacci_cloud.ncl
  esmvaltool/recipes/examples/recipe_check_obs.yml
Labels: enhancement, observations

#3479 Fix plots and provenance in Russell diagnostics
  esmvaltool/diag_scripts/russell18jgr/russell18jgr-fig2.ncl
  esmvaltool/diag_scripts/russell18jgr/russell18jgr-fig3b-2.ncl
  esmvaltool/diag_scripts/russell18jgr/russell18jgr-fig3b.ncl
  esmvaltool/diag_scripts/russell18jgr/russell18jgr-fig4.ncl
  esmvaltool/diag_scripts/russell18jgr/russell18jgr-fig5.ncl
  esmvaltool/diag_scripts/russell18jgr/russell18jgr-fig5g.ncl
  esmvaltool/diag_scripts/russell18jgr/russell18jgr-fig6a.ncl
  esmvaltool/diag_scripts/russell18jgr/russell18jgr-fig6b.ncl
  esmvaltool/diag_scripts/russell18jgr/russell18jgr-fig7h.ncl
  esmvaltool/diag_scripts/russell18jgr/russell18jgr-fig7i.ncl
  esmvaltool/diag_scripts/russell18jgr/russell18jgr-fig9a.ncl
  esmvaltool/diag_scripts/russell18jgr/russell18jgr-fig9b.ncl
  esmvaltool/diag_scripts/russell18jgr/russell18jgr-fig9c.ncl
  esmvaltool/diag_scripts/russell18jgr/russell18jgr-polar.ncl
Labels: bug

#3485 Add v2.10 release notes
  CITATION.cff
  doc/sphinx/source/changelog.rst
  doc/sphinx/source/recipes/broken_recipe_list.rst
Labels: documentation

#3486 Use ESMValCore v2.10
  doc/sphinx/source/changelog.rst
  environment.yml
  environment_osx.yml
Labels: installation

#3487 Update dependencies
  environment.yml
  environment_osx.yml
  setup.py
Labels: installation

#3489 Merge v2.10.x into main
  CITATION.cff
  esmvaltool/recipes/bock20jgr/recipe_bock20jgr_fig_1-4.yml
Labels: installation

#3491 Move code into function in batch job generation script
  esmvaltool/utils/batch-jobs/generate.py
Labels: testing
