Repository ESMValGroup/ESMValTool, pull requests merged in 2023-08, with the labels that each got.

#3307 [condalock] update conda lock creation Github Action workflow and ship updated (bot-generated) conda-lock file
  .github/workflows/create-condalock-file.yml
  conda-linux-64.lock
Labels: testing, condalock

#3315 [Github Actions] Compress all bash shell setters into one default option per workflow
  .github/workflows/install-from-conda.yml
  .github/workflows/install-from-condalock-file.yml
  .github/workflows/install-from-source.yml
  .github/workflows/run-tests-monitor.yml
  .github/workflows/test-development.yml
  .github/workflows/test.yml
Labels: testing

#3310 update `mamba` version in readthedocs configuration docs builds
  .readthedocs.yaml
Labels: documentation

#3318 add Romain Beucher to CITATION as contributor
  CITATION.cff
Labels: documentation

#3319 Removed recipe_carvalhais14nat from list of broken recipes
  doc/sphinx/source/recipes/broken_recipe_list.rst
Labels: documentation

#3298 Slight refactoring of diag `galytska23/select_variables_for_tigramite.py` for generality and portability (for Changelog v2.10: authors: @valeriupredoi and @egalytska)
  esmvaltool/diag_scripts/galytska23/select_variables_for_tigramite.py
Labels: enhancement, diagnostic

#3332 Fixed provenance tracking for NCL multipanel PNGs
  esmvaltool/diag_scripts/clouds/clouds.ncl
  esmvaltool/diag_scripts/clouds/clouds_dyn_matrix.ncl
  esmvaltool/diag_scripts/clouds/clouds_interannual.ncl
  esmvaltool/diag_scripts/clouds/clouds_lifrac_scatter.ncl
  esmvaltool/diag_scripts/clouds/clouds_pdf.ncl
  esmvaltool/diag_scripts/clouds/clouds_scatter.ncl
  esmvaltool/diag_scripts/clouds/clouds_seasonal_cycle.ncl
  esmvaltool/diag_scripts/clouds/clouds_zonal.ncl
  esmvaltool/interface_scripts/logging.ncl
Labels: enhancement

#3335 Add `OBS-maintainers` team to documentation on OBS data maintenance and CMORizer reviews
  .github/CODEOWNERS
  .github/pull_request_template.md
  doc/sphinx/source/community/dataset.rst
  doc/sphinx/source/community/review.rst
Labels: documentation, observations

#3039 CMORizer for NASA MERRA reanalysis
  doc/sphinx/source/input.rst
  esmvaltool/cmorizers/data/datasets.yml
  esmvaltool/cmorizers/data/downloaders/datasets/merra.py
  esmvaltool/cmorizers/data/downloaders/wget.py
  esmvaltool/cmorizers/data/formatters/datasets/merra.ncl
  esmvaltool/cmorizers/data/formatters/utilities.ncl
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/merra.bibtex
Labels: observations, approved by technical reviewer, approved by scientific reviewer, Data

#3322 Add version to dataset in python example recipe to avoid "Unknown file format" issue on JASMIN
  esmvaltool/recipes/examples/recipe_python.yml
Labels: Data
