Repository ESMValGroup/ESMValTool, pull requests merged in 2023-02, with the labels that each got.

#2799 Earth System Data Cube (ESDC) cmorizer
  doc/sphinx/source/input.rst
  environment.yml
  environment_osx.yml
  esmvaltool/cmorizers/data/cmor_config/ESDC.yml
  esmvaltool/cmorizers/data/datasets.yml
  esmvaltool/cmorizers/data/formatters/datasets/esdc.py
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/esdc.bibtex
  setup.py
Labels: observations

#3006 Merra2 cmorizer set UNLIMITED time coordinate
  esmvaltool/cmorizers/data/formatters/datasets/merra2.py
  tests/unit/cmorizers/obs/test_merra2.py
Labels: bug, observations

#3041 Fix version numbers of native6 datasets in recipes
  doc/sphinx/source/input.rst
  esmvaltool/recipes/clouds/recipe_lauer22jclim_fig1_clim.yml
  esmvaltool/recipes/clouds/recipe_lauer22jclim_fig1_clim_amip.yml
  esmvaltool/recipes/clouds/recipe_lauer22jclim_fig2_taylor.yml
  esmvaltool/recipes/clouds/recipe_lauer22jclim_fig2_taylor_amip.yml
  esmvaltool/recipes/clouds/recipe_lauer22jclim_fig3-4_zonal.yml
  esmvaltool/recipes/clouds/recipe_lauer22jclim_fig5_lifrac.yml
  esmvaltool/recipes/clouds/recipe_lauer22jclim_fig7_seas.yml
  esmvaltool/recipes/clouds/recipe_lauer22jclim_fig8_dyn.yml
  esmvaltool/recipes/cmorizers/recipe_daily_era5.yml
  esmvaltool/recipes/cmorizers/recipe_era5-land.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/recipes/hydrology/recipe_globwat.yml
  esmvaltool/recipes/hydrology/recipe_hydro_forcing.yml
  esmvaltool/recipes/ipccwg1ar6ch3/recipe_ipccwg1ar6ch3_atmosphere.yml
  esmvaltool/recipes/ipccwg1ar6ch3/recipe_ipccwg1ar6ch3_fig_3_19.yml
  esmvaltool/recipes/ipccwg1ar6ch3/recipe_ipccwg1ar6ch3_fig_3_42_a.yml
  esmvaltool/recipes/recipe_climwip_brunner2019_med.yml
  esmvaltool/recipes/recipe_climwip_brunner20esd.yml
  esmvaltool/recipes/recipe_climwip_test_basic.yml
  esmvaltool/recipes/recipe_climwip_test_performance_sigma.yml
  esmvaltool/recipes/recipe_impact.yml
Labels: bug, backwards incompatible change

#2879 Backward compatibility policy
  doc/sphinx/source/community/backward_compatibility.rst
  doc/sphinx/source/community/code_documentation.rst
  doc/sphinx/source/community/index.rst
  doc/sphinx/source/community/release_strategy.rst
  doc/sphinx/source/community/review.rst
  doc/sphinx/source/introduction.rst
Labels: documentation

#2772 Adding IPCC AR6 Chapter 3 Figure 3.43 - Pattern Correlation
  doc/sphinx/source/recipes/figures/ipccwg1ar6ch3/patterncor.png
  doc/sphinx/source/recipes/recipe_ipccwg1ar6ch3.rst
  esmvaltool/diag_scripts/ipcc_ar6/corr_pattern.ncl
  esmvaltool/diag_scripts/ipcc_ar6/corr_pattern_collect.ncl
  esmvaltool/recipes/ipccwg1ar6ch3/recipe_ipccwg1ar6ch3_fig_3_43.yml
Labels: diagnostic, approved by technical reviewer, approved by scientific reviewer, IPCC

#3052 Link backward compatibility policy to top level of ESMValCore changelog
  doc/sphinx/source/community/backward_compatibility.rst
Labels: documentation

#3040 Update recipe load test for v2.8
  tests/integration/test_recipes_loading.py
Labels: testing
