Repository ESMValGroup/ESMValTool, pull requests merged in 2024-04, with the labels that each got.

#3558 Fix Codacy badge
  README.md
Labels: documentation

#3048 Add support for aerosol optical depth climatology metrics to the AutoAssess replacement
  .github/workflows/test.yml
  CITATION.cff
  doc/sphinx/source/recipes/figures/aod_aeronet_assess/UKESM1-0-LL_CMIP_AERmon_historical_od440aer_gn_1988_2008_DJF.png
  doc/sphinx/source/recipes/figures/aod_aeronet_assess/UKESM1-0-LL_CMIP_AERmon_historical_od440aer_gn_1988_2008_JJA.png
  doc/sphinx/source/recipes/figures/aod_aeronet_assess/UKESM1-0-LL_CMIP_AERmon_historical_od440aer_gn_1988_2008_MAM.png
  doc/sphinx/source/recipes/figures/aod_aeronet_assess/UKESM1-0-LL_CMIP_AERmon_historical_od440aer_gn_1988_2008_SON.png
  doc/sphinx/source/recipes/figures/aod_aeronet_assess/UKESM1-0-LL_CMIP_AERmon_historical_od440aer_gn_1988_2008_scatter.png
  doc/sphinx/source/recipes/figures/aod_aeronet_assess/UKESM1-0-LL_CMIP_AERmon_historical_od440aer_gn_1994_2014_DJF.png
  doc/sphinx/source/recipes/figures/aod_aeronet_assess/UKESM1-0-LL_CMIP_AERmon_historical_od440aer_gn_1994_2014_JJA.png
  doc/sphinx/source/recipes/figures/aod_aeronet_assess/UKESM1-0-LL_CMIP_AERmon_historical_od440aer_gn_1994_2014_MAM.png
  doc/sphinx/source/recipes/figures/aod_aeronet_assess/UKESM1-0-LL_CMIP_AERmon_historical_od440aer_gn_1994_2014_SON.png
  doc/sphinx/source/recipes/figures/aod_aeronet_assess/UKESM1-0-LL_CMIP_AERmon_historical_od440aer_gn_1994_2014_scatter.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_aod_aeronet_assess.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/aerosols/aero_utils.py
  esmvaltool/diag_scripts/aerosols/aod_aeronet_assess.py
  esmvaltool/recipes/recipe_aod_aeronet_assess.yml
Labels: diagnostic, approved by technical reviewer, approved by scientific reviewer, AutoAssess

#3573 Update the release schedule for v2.11.0
  doc/sphinx/source/community/release_strategy/release_strategy.rst
Labels: documentation, release

#3577 Adding pys2index dependency
  environment.yml
  environment_osx.yml
  setup.py
Labels: installation
