Repository ESMValGroup/ESMValTool, pull requests merged in 2024-10, with the labels that each got.

#3141 CMORizer for JRA-55
  doc/sphinx/source/input.rst
  environment.yml
  environment_osx.yml
  esmvaltool/cmorizers/data/cmor_config/JRA-55.yml
  esmvaltool/cmorizers/data/datasets.yml
  esmvaltool/cmorizers/data/downloaders/datasets/jra_55.py
  esmvaltool/cmorizers/data/downloaders/wget.py
  esmvaltool/cmorizers/data/formatters/datasets/jra_55.py
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/jra_55.bibtex
  setup.py
Labels: observations, in technical review, in scientific review, Data

#3759 Remove obsolete utility `esmvt_rose_wrapper` and its documentation and very obsolete `mip_convert` cmorizer
  doc/sphinx/source/utils.rst
  esmvaltool/cmorizers/mip_convert/config-mipconv-user.yml
  esmvaltool/cmorizers/mip_convert/esmvt_mipconv_setup.py
  esmvaltool/cmorizers/mip_convert/recipe_mip_convert.yml
  esmvaltool/cmorizers/mip_convert/rose-suite-template.conf
  esmvaltool/utils/rose-cylc/esmvt_rose_wrapper.py
  setup.py
Labels: testing

#3760 remove obsolete and inactive `tests/system` tests
  tests/system/__init__.py
  tests/system/config-test.yml
  tests/system/data_simulator.py
  tests/system/esmvaltool_testlib.py
  tests/system/test_recipes.py
Labels: testing

#3768 Pin cartopy to `cartopy<0.24`
  environment.yml
  environment_osx.yml
  setup.py
Labels: installation

#3770 Pin cartopy<0.24 on v2.11.x release branch
  environment.yml
  environment_osx.yml
  esmvaltool/diag_scripts/climate_metrics/feedback_parameters.py
  setup.py
Labels: installation, release

#3774 retire Mambaforge
  .github/workflows/create-condalock-file.yml
  .github/workflows/install-from-conda.yml
  .github/workflows/install-from-source.yml
  .github/workflows/run-tests-monitor.yml
  .github/workflows/test-development.yml
  .github/workflows/test.yml
  doc/sphinx/source/quickstart/installation.rst
Labels: testing

#3778 Retire mambaforge - addendum to 3774
  .circleci/config.yml
  doc/sphinx/source/quickstart/installation.rst
  doc/sphinx/source/utils.rst
  docker/Dockerfile
  docker/Dockerfile.dev
  docker/Dockerfile.exp
  esmvaltool/utils/batch-jobs/generate.py
Labels: documentation, installation

#3771 Pin mamba<2 for conda-lock: solution by Ben Mares @maresb
  .github/workflows/create-condalock-file.yml
Labels: testing

#3783 update Docker builds badge in README
  README.md
Labels: documentation

#3788 update comment in conda lock creation Github action
  .github/workflows/create-condalock-file.yml
Labels: testing

#3761 Adapt ESMValTool to new configuration
  .circleci/config.yml
  config-user-example.yml
  doc/sphinx/source/community/dataset.rst
  doc/sphinx/source/community/diagnostic.rst
  doc/sphinx/source/community/release_strategy/detailed_release_procedure.rst
  doc/sphinx/source/community/upgrading.rst
  doc/sphinx/source/develop/dataset.rst
  doc/sphinx/source/faq.rst
  doc/sphinx/source/functionalities.rst
  doc/sphinx/source/input.rst
  doc/sphinx/source/quickstart/configuration.rst
  doc/sphinx/source/quickstart/output.rst
  doc/sphinx/source/quickstart/running.rst
  doc/sphinx/source/recipes/recipe_carvalhais14nat.rst
  doc/sphinx/source/recipes/recipe_climwip.rst
  doc/sphinx/source/recipes/recipe_gier20bg.rst
  doc/sphinx/source/recipes/recipe_hydrology.rst
  doc/sphinx/source/recipes/recipe_ipccwg1ar6ch3.rst
  doc/sphinx/source/recipes/recipe_kcs.rst
  doc/sphinx/source/recipes/recipe_model_evaluation.rst
  doc/sphinx/source/recipes/recipe_monitor.rst
  doc/sphinx/source/recipes/recipe_oceans.rst
  doc/sphinx/source/recipes/recipe_rainfarm.rst
  doc/sphinx/source/recipes/recipe_shapeselect.rst
  doc/sphinx/source/recipes/recipe_wenzel14jgr.rst
  doc/sphinx/source/recipes/recipe_wenzel16nat.rst
  doc/sphinx/source/utils.rst
  esmvaltool/cmorizers/data/cmorizer.py
  esmvaltool/cmorizers/data/datasets.yml
  esmvaltool/cmorizers/data/download_scripts/download_era_interim.py
  esmvaltool/cmorizers/data/downloaders/datasets/jra_55.py
  esmvaltool/cmorizers/data/downloaders/datasets/noaa_ersstv3b.py
  esmvaltool/cmorizers/data/downloaders/datasets/noaa_ersstv5.py
  esmvaltool/cmorizers/data/downloaders/datasets/nsidc_g02202_sh.py
  esmvaltool/cmorizers/data/formatters/datasets/ct2019.py
  esmvaltool/cmorizers/data/formatters/datasets/merra.ncl
  esmvaltool/cmorizers/data/formatters/datasets/mls_aura.py
  esmvaltool/diag_scripts/kcs/local_resampling.py
  esmvaltool/diag_scripts/monitor/compute_eofs.py
  esmvaltool/diag_scripts/monitor/monitor.py
  esmvaltool/diag_scripts/monitor/multi_datasets.py
  esmvaltool/diag_scripts/russell18jgr/russell18jgr-fig6a.ncl
  esmvaltool/diag_scripts/russell18jgr/russell18jgr-fig6b.ncl
  esmvaltool/diag_scripts/russell18jgr/russell18jgr-fig7i.ncl
  esmvaltool/diag_scripts/russell18jgr/russell18jgr-fig9c.ncl
  esmvaltool/interface_scripts/logging.ncl
  esmvaltool/recipes/examples/recipe_extract_shape.yml
  esmvaltool/recipes/hydrology/recipe_hydro_forcing.yml
  esmvaltool/recipes/hydrology/recipe_lisflood.yml
  esmvaltool/recipes/hydrology/recipe_marrmot.yml
  esmvaltool/recipes/ipccwg1ar6ch3/recipe_ipccwg1ar6ch3_fig_3_42_a.yml
  esmvaltool/recipes/recipe_carvalhais14nat.yml
  esmvaltool/recipes/recipe_runoff_et.yml
  esmvaltool/recipes/recipe_sea_surface_salinity.yml
  esmvaltool/recipes/recipe_shapeselect.yml
  esmvaltool/utils/batch-jobs/generate.py
  tests/integration/test_cmorizer.py
  tests/integration/test_diagnostic_run.py
Labels: deprecated feature

#3785 Readthedocs configuration/builds: revert to miniconda before miniforge is available
  .readthedocs.yaml
Labels: documentation

#3792 Pin pys2index >=0.1.5 in osx environment
  environment_osx.yml
Labels: installation

#3789 Use `transform_first=True` for contourf plots with Robinson projection to avoid cartopy bug
  esmvaltool/cmorizers/data/formatters/datasets/cmap.py
  esmvaltool/diag_scripts/monitor/multi_datasets.py
  esmvaltool/diag_scripts/shared/plot/_plot.py
Labels: diagnostic

#3797 Fix contourf plots for masked data
  esmvaltool/diag_scripts/monitor/multi_datasets.py
  esmvaltool/diag_scripts/shared/plot/_plot.py
Labels: diagnostic
