Repository ESMValGroup/ESMValTool, pull requests merged in 2024-05, with the labels that each got.

#3581 [Github Actions] install git in OSX and add environment inspection
  .github/workflows/run-tests-monitor.yml
  .github/workflows/test.yml
Labels: testing

#3567 Recipe test workflow support recipes in subdirectories
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/app/compare/bin/compare_task_runner.sh
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/app/compare/rose-app.conf
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/app/process/rose-app.conf
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/flow.cylc
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/site/jasmin.cylc
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/site/metoffice.cylc
Labels: Recipe Test Workflow (RTW)

#3585 Pin esmpy <8.6.0
  environment.yml
  environment_osx.yml
  setup.py
Labels: installation

#3596 Update cylc version in rtw.lock file for recipe_test_workflow
  .github/workflows/rtw-env/rtw-env.lock
  .github/workflows/rtw-env/rtw-env.yml
  .github/workflows/rtw-tests.yml
  .github/workflows/rtw.lock
  esmvaltool/utils/recipe_test_workflow/doc/source/common.txt
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/flow.cylc
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/site/jasmin.cylc
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/site/metoffice.cylc
Labels: Recipe Test Workflow (RTW)

#3600 Store RTW files in share directory in installed workflow
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/app/install_env_file/bin/install_env_file.sh
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/flow.cylc
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/site/metoffice.cylc
Labels: Recipe Test Workflow (RTW)

#3605 Fixed attribute handling in emergent constraint diagnostic for iris>=3.8
  esmvaltool/diag_scripts/emergent_constraints/__init__.py
Labels: diagnostic

#3603 Fixed attribute handling in austral_jet/main.ncl for iris>=3.8
  esmvaltool/diag_scripts/austral_jet/main.ncl
Labels: diagnostic

#3609 Add recipe `recipe_consecdrydays` to RTW
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/flow.cylc
Labels: Recipe Test Workflow (RTW)

#3611 Update the name of the remapcon2 operator in R recipes
  environment.yml
  environment_osx.yml
  esmvaltool/diag_scripts/hyint/hyint_etccdi_preproc.R
  esmvaltool/diag_scripts/hyint/hyint_functions.R
  esmvaltool/diag_scripts/hyint/hyint_preproc.R
  esmvaltool/diag_scripts/miles/basis_functions.R
  esmvaltool/diag_scripts/quantilebias/quantilebias_functions.R
Labels: bug

#3586 [CI Github Actions] Update (outdated) actions versions that produce Node.js warnings
  .github/workflows/citation_file_validator.yml
  .github/workflows/create-condalock-file.yml
  .github/workflows/install-from-conda.yml
  .github/workflows/install-from-condalock-file.yml
  .github/workflows/install-from-source.yml
  .github/workflows/pypi-build-and-deploy.yml
  .github/workflows/run-tests-monitor.yml
  .github/workflows/test-development.yml
  .github/workflows/test.yml
Labels: testing

#3615 Validate RTW user config file
  .codacy.yml
  esmvaltool/utils/recipe_test_workflow/doc/source/user_guide/workflow.rst
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/app/configure/bin/__init__.py
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/app/configure/bin/configure.py
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/app/configure/bin/test_configure.py
Labels: enhancement, Recipe Test Workflow (RTW)

#3622 #3621 Remove `imagehash` install from `RTW`
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/app/get_esmval/opt/rose-app-jasmin.conf
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/site/jasmin.cylc
Labels: Recipe Test Workflow (RTW)

#3634 Fix `flake8==7` linting issues
  .github/workflows/test-development.yml
  esmvaltool/diag_scripts/autoassess/stratosphere/strat_metrics_1.py
  tests/unit/test_lint.py
Labels: testing

#3625 Add Rose and Cylc to testing dependencies for RTW
  .github/workflows/check-rtw.yml
  .github/workflows/rtw-env/rtw-env.lock
  .github/workflows/rtw-env/rtw-env.yml
  environment.yml
  esmvaltool/utils/recipe_test_workflow/doc/source/conf.py
  setup.py
Labels: Recipe Test Workflow (RTW)

#3381 Update CRU CMORizer
  doc/sphinx/source/input.rst
  esmvaltool/cmorizers/data/cmor_config/CRU.yml
  esmvaltool/cmorizers/data/datasets.yml
  esmvaltool/cmorizers/data/downloaders/datasets/cru.py
  esmvaltool/cmorizers/data/formatters/datasets/cru.py
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/cru.bibtex
Labels: observations, approved by technical reviewer, approved by scientific reviewer
