Repository ESMValGroup/ESMValTool, pull requests merged in 2024-06, with the labels that each got.

#3627 Add `recipe_ocean_multimap` to RTW
  esmvaltool/utils/recipe_test_workflow/doc/source/common.txt
  esmvaltool/utils/recipe_test_workflow/doc/source/tested_recipes.rst
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/flow.cylc
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/site/metoffice.cylc
Labels: Recipe Test Workflow (RTW)

#3651 Use `iris.FUTURE.save_split_attrs = True` to remove iris warning in many diagnostics
  esmvaltool/diag_scripts/shared/_base.py
  esmvaltool/diag_scripts/shared/io.py
Labels: diagnostic

#3645 Avoid concatenation error in recipe_pcrglobwb.yml
  esmvaltool/diag_scripts/hydrology/pcrglobwb.py
Labels: diagnostic

#2785 CMIP6 climate patterns
  .zenodo.json
  CITATION.cff
  doc/sphinx/source/recipes/figures/climate_patterns/patterns.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_climate_patterns.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/climate_patterns/climate_patterns.py
  esmvaltool/diag_scripts/climate_patterns/plotting.py
  esmvaltool/diag_scripts/climate_patterns/sub_functions.py
  esmvaltool/recipes/recipe_climate_patterns.yml
  esmvaltool/references/huntingford2000climdyn.bibtex
  esmvaltool/references/mathison2024gmd.bibtex
Labels: in technical review, approved by scientific reviewer, new recipe

#3652 Improve the formatting of the recipe documentation template
  doc/sphinx/source/recipes/recipe_seaborn.rst
  doc/sphinx/source/recipes/recipe_template.rst.template
Labels: documentation

#3671 Include verbose output from `compare.py` in RTW
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/app/compare/bin/compare_task_runner.sh
Labels: Recipe Test Workflow (RTW)

#3668 Add code owners for the RTW
  .github/CODEOWNERS
Labels: Recipe Test Workflow (RTW)

#3628 Add introduction material on the main documentation page
  doc/sphinx/source/index.rst
Labels: documentation

#3675 Avoid warning in documentation build
  doc/sphinx/source/index.rst
Labels: documentation

#3649 Add `rose macro -V` command to `rtw-tests.yml` Github Workflow
  .github/workflows/check-rtw.yml
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/meta/rose-meta.conf
Labels: Recipe Test Workflow (RTW)

#3672 Use `importlib` as the import mode for `pytest`
  esmvaltool/diag_scripts/aerosols/aod_aeronet_assess.py
  esmvaltool/diag_scripts/climate_patterns/climate_patterns.py
  esmvaltool/diag_scripts/ensclus/ens_anom.py
  esmvaltool/diag_scripts/ensclus/ens_eof_kmeans.py
  esmvaltool/diag_scripts/ensclus/ens_plots.py
  esmvaltool/diag_scripts/ensclus/ensclus.py
  esmvaltool/diag_scripts/examples/correlate.py
  esmvaltool/diag_scripts/iht_toa/single_model_diagnostics.py
  esmvaltool/diag_scripts/mpqb/mpqb_lineplot.py
  esmvaltool/diag_scripts/mpqb/mpqb_lineplot_anncyc.py
  esmvaltool/diag_scripts/mpqb/mpqb_lineplot_growthrate.py
  esmvaltool/diag_scripts/weighting/climwip/calibrate_sigmas.py
  esmvaltool/diag_scripts/weighting/climwip/main.py
  esmvaltool/diag_scripts/weighting/plot_utilities.py
  esmvaltool/diag_scripts/weighting/weighted_temperature_graph.py
  esmvaltool/diag_scripts/weighting/weighted_temperature_map.py
  esmvaltool/diag_scripts/zmnam/zmnam.py
  setup.cfg
Labels: testing

#3682 Prevent overlapping time axis tick labels in monitoring recipe
  esmvaltool/diag_scripts/monitor/multi_datasets.py
  esmvaltool/recipes/monitor/recipe_monitor_with_refs.yml
Labels: diagnostic

#3614 Add how to add a recipe documentation
  esmvaltool/utils/recipe_test_workflow/doc/source/add_a_recipe.rst
  esmvaltool/utils/recipe_test_workflow/doc/source/common.txt
  esmvaltool/utils/recipe_test_workflow/doc/source/conf.py
  esmvaltool/utils/recipe_test_workflow/doc/source/glossary.rst
  esmvaltool/utils/recipe_test_workflow/doc/source/index.rst
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/flow.cylc
Labels: Recipe Test Workflow (RTW)

#3664 Add the `recipe_ocean_amoc.yml` recipe to the RTW
  esmvaltool/utils/recipe_test_workflow/doc/source/common.txt
  esmvaltool/utils/recipe_test_workflow/doc/source/tested_recipes.rst
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/flow.cylc
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/site/metoffice.cylc
Labels: Recipe Test Workflow (RTW)

#3601 Review `rose-app.conf` files in recipe test workflow
  .github/workflows/check-rtw.yml
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/app/compare/bin/compare_task_runner.sh
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/app/compare/rose-app.conf
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/app/install_env_file/bin/install_env_file.sh
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/app/install_env_file/rose-app.conf
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/flow.cylc
Labels: Recipe Test Workflow (RTW)

#3684 Merge the RTW documentation with the ESMValTool documentation
  .github/workflows/check-rtw.yml
  doc/sphinx/source/gensidebar.py
  doc/sphinx/source/utils/RTW/about.rst
  doc/sphinx/source/utils/RTW/add_a_recipe.rst
  doc/sphinx/source/utils/RTW/common.txt
  doc/sphinx/source/utils/RTW/glossary.rst
  doc/sphinx/source/utils/RTW/index.rst
  doc/sphinx/source/utils/RTW/tested_recipes.rst
  doc/sphinx/source/utils/RTW/user_guide/index.rst
  doc/sphinx/source/utils/RTW/user_guide/quick_start.rst
  doc/sphinx/source/utils/RTW/user_guide/workflow.rst
  doc/sphinx/source/utils/utils.rst
  esmvaltool/utils/recipe_test_workflow/doc/Makefile
  esmvaltool/utils/recipe_test_workflow/doc/make.bat
  esmvaltool/utils/recipe_test_workflow/doc/source/_static/README
  esmvaltool/utils/recipe_test_workflow/doc/source/_templates/footer.html
  esmvaltool/utils/recipe_test_workflow/doc/source/conf.py
  esmvaltool/utils/recipe_test_workflow/doc/source/index.rst
Labels: Recipe Test Workflow (RTW)

#3689 Pin R <4.3.0
  environment.yml
Labels: installation
