Repository ESMValGroup/ESMValTool, pull requests merged in 2024-03, with the labels that each got.

#3282 Updating ESACCI-WATERVAPOUR cmorizer
  esmvaltool/cmorizers/data/cmor_config/ESACCI-WATERVAPOUR.yml
  esmvaltool/cmorizers/data/datasets.yml
  esmvaltool/cmorizers/data/formatters/datasets/esacci_watervapour.py
  esmvaltool/recipes/clouds/recipe_lauer22jclim_fig1_clim.yml
  esmvaltool/recipes/clouds/recipe_lauer22jclim_fig1_clim_amip.yml
  esmvaltool/recipes/clouds/recipe_lauer22jclim_fig2_taylor.yml
  esmvaltool/recipes/clouds/recipe_lauer22jclim_fig2_taylor_amip.yml
  esmvaltool/recipes/clouds/recipe_lauer22jclim_fig6_interannual.yml
  esmvaltool/recipes/clouds/recipe_lauer22jclim_fig7_seas.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/recipes/model_evaluation/recipe_model_evaluation_basics.yml
  esmvaltool/recipes/model_evaluation/recipe_model_evaluation_clouds_clim.yml
  esmvaltool/recipes/recipe_cmug_h2o.yml
Labels: enhancement, observations, looking for technical reviewer, in scientific review

#3552 Allow datasets without `project` in multi_datasets.py
  esmvaltool/diag_scripts/monitor/multi_datasets.py
Labels: diagnostic

#3556 Run RTW prototype daily with local KGO
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/flow.cylc
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/meta/rose-meta.conf
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/opt/rose-suite-metoffice.conf
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/rose-suite.conf
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/site/jasmin.cylc
  esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/site/metoffice.cylc
Labels: Recipe Test Workflow (RTW)
