Repository ESMValGroup/ESMValTool, pull requests merged in 2024-07, with the labels that each got.

#3700 Pin importlib_metadata <8
  environment.yml
  environment_osx.yml
  setup.py
Labels: installation

#3704 Update `scipy.integrate.simps` import
  esmvaltool/diag_scripts/emergent_constraints/__init__.py
Labels: enhancement, installation, diagnostic

#3707 Final sanity check and reorganisation of RTW
  .github/workflows/check-rtw.yml
  .zenodo.json
  CITATION.cff
  doc/sphinx/source/utils/RTW/add_a_recipe.rst
  doc/sphinx/source/utils/RTW/common.txt
  doc/sphinx/source/utils/RTW/tested_recipes.rst
  doc/sphinx/source/utils/RTW/user_guide/quick_start.rst
  doc/sphinx/source/utils/RTW/user_guide/workflow.rst
  doc/sphinx/source/utils/utils.rst
  environment_osx.yml
  esmvaltool/utils/recipe_test_workflow/app/compare/rose-app.conf
  esmvaltool/utils/recipe_test_workflow/app/configure/bin/__init__.py
  esmvaltool/utils/recipe_test_workflow/app/configure/bin/configure.py
  esmvaltool/utils/recipe_test_workflow/app/configure/bin/test_configure.py
  esmvaltool/utils/recipe_test_workflow/app/configure/rose-app.conf
  esmvaltool/utils/recipe_test_workflow/app/get_esmval/bin/clone_latest_esmval.sh
  esmvaltool/utils/recipe_test_workflow/app/get_esmval/opt/rose-app-jasmin.conf
  esmvaltool/utils/recipe_test_workflow/app/get_esmval/opt/rose-app-metoffice.conf
  esmvaltool/utils/recipe_test_workflow/app/get_esmval/rose-app.conf
  esmvaltool/utils/recipe_test_workflow/app/install_env_file/rose-app.conf
  esmvaltool/utils/recipe_test_workflow/app/process/rose-app.conf
  esmvaltool/utils/recipe_test_workflow/flow.cylc
  esmvaltool/utils/recipe_test_workflow/meta/rose-meta.conf
  esmvaltool/utils/recipe_test_workflow/opt/rose-suite-jasmin.conf
  esmvaltool/utils/recipe_test_workflow/opt/rose-suite-metoffice.conf
  esmvaltool/utils/recipe_test_workflow/rose-suite.conf
  esmvaltool/utils/recipe_test_workflow/rose-suite.info
  esmvaltool/utils/recipe_test_workflow/site/jasmin-env
  esmvaltool/utils/recipe_test_workflow/site/jasmin.cylc
  esmvaltool/utils/recipe_test_workflow/site/metoffice-env
  esmvaltool/utils/recipe_test_workflow/site/metoffice.cylc
  setup.cfg
Labels: Recipe Test Workflow (RTW)

#3678 Update all pre-commit versions
  .pre-commit-config.yaml
  environment.yml
  environment_osx.yml
Labels: installation

#3692 Update AERONET data version
  esmvaltool/cmorizers/data/cmor_config/AERONET.yml
  esmvaltool/cmorizers/data/datasets.yml
  esmvaltool/cmorizers/data/formatters/datasets/aeronet.py
  esmvaltool/recipes/recipe_aod_aeronet_assess.yml
Labels: observations

#3706 Update the list of broken recipes for `v2.11.0`
  doc/sphinx/source/recipes/broken_recipe_list.rst
  doc/sphinx/source/recipes/recipe_wenzel14jgr.rst
Labels: documentation

#3712 Pin matplotlib <3.9.0 on ESMValTool release branch
  environment.yml
  environment_osx.yml
  setup.py
Labels: installation, release

#3695 Update the version number and release notes for v2.11.0
  .zenodo.json
  CITATION.cff
  doc/sphinx/source/changelog.rst
  doc/sphinx/source/community/release_strategy/release_strategy.rst
  environment.yml
  environment_osx.yml
Labels: documentation, release

#3676 Update esacci-soilmoisture(v08.1) downloader and CMORizer (Python version)
  doc/sphinx/source/input.rst
  esmvaltool/cmorizers/data/cmor_config/ESACCI-SOILMOISTURE.yml
  esmvaltool/cmorizers/data/datasets.yml
  esmvaltool/cmorizers/data/downloaders/datasets/esacci_soilmoisture.py
  esmvaltool/cmorizers/data/formatters/datasets/esacci_soilmoisture.ncl
  esmvaltool/cmorizers/data/formatters/datasets/esacci_soilmoisture.py
  esmvaltool/cmorizers/data/utilities.py
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/esacci-soilmoisture.bibtex
Labels: observations

#3683 [Merge after v2.11.0 Release] Retire support for Python 3.9
  .github/workflows/install-from-conda.yml
  .github/workflows/install-from-condalock-file.yml
  .github/workflows/install-from-source.yml
  .github/workflows/run-tests-monitor.yml
  .github/workflows/test-development.yml
  .github/workflows/test.yml
  doc/sphinx/source/quickstart/installation.rst
  environment.yml
  environment_osx.yml
  setup.py
Labels: installation

#3718 Ignore autosummary warning in documentation build
  doc/sphinx/source/conf.py
Labels: documentation

#3728 More flexible file loading in `monitor/multi_datasets.py`
  esmvaltool/diag_scripts/monitor/multi_datasets.py
Labels: diagnostic
