Repository ESMValGroup/ESMValTool, pull requests merged in 2024-02, with the labels that each got.

#3517 Update sklearn tests to be compatible with current pytest version (pytest >=8.0.0)
  tests/integration/diag_scripts/mlr/test_custom_sklearn_functions.py
Labels: testing

#3518 Update sklearn tests to be compatible with current pytest version (pytest >=8.0.0) Part 2
  tests/integration/diag_scripts/mlr/test_custom_sklearn_classes.py
Labels: testing

#3530 [CI/Github Actions/non-critical] remove teams from auto PR creation invocation for condalock action
  .github/workflows/create-condalock-file.yml
Labels: testing, automatedPR

#3512 Add CMORizer script for NSIDC-G02202-sh sea ice fraction
  doc/sphinx/source/input.rst
  esmvaltool/cmorizers/data/cmor_config/NSIDC-G02202-sh.yml
  esmvaltool/cmorizers/data/datasets.yml
  esmvaltool/cmorizers/data/downloaders/datasets/nsidc_g02202_sh.py
  esmvaltool/cmorizers/data/formatters/datasets/nsidc_g02202_sh.py
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/nsidc-g02202.bibtex
Labels: observations, Data

#3445 CMORizer Australian Gridded Climate Data(AGCD) precipitation
  doc/sphinx/source/input.rst
  esmvaltool/cmorizers/data/cmor_config/AGCD.yml
  esmvaltool/cmorizers/data/datasets.yml
  esmvaltool/cmorizers/data/formatters/datasets/agcd.py
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/agcd-v201.bibtex
  tests/unit/cmorizers/test_cmorization_interface.py
Labels: observations

#3469 Extend CMORizer NCEP-DOE-R2
  doc/sphinx/source/input.rst
  esmvaltool/cmorizers/data/cmor_config/NCEP-DOE-R2.yml
  esmvaltool/cmorizers/data/downloaders/datasets/ncep_doe_r2.py
  esmvaltool/recipes/examples/recipe_check_obs.yml
Labels: enhancement, observations, looking for technical reviewer, approved by scientific reviewer

#3528 `monitor/multi_dataset.py` improvements: allow data w/o `timerange` and improve text formatting
  esmvaltool/diag_scripts/monitor/multi_datasets.py
Labels: diagnostic

#3538 [Circle/CI]Fix `test_installation_from_conda` Circle CI tests
  .circleci/config.yml
Labels: testing

#3537 Add comment to recipe_lauer13jclim regarding UWisc being superseded by MAC-LWP
  doc/sphinx/source/recipes/recipe_clouds.rst
  esmvaltool/recipes/clouds/recipe_lauer13jclim.yml
Labels: approved by technical reviewer, approved by scientific reviewer

#3541 Improved description of model evaluation recipes
  esmvaltool/recipes/model_evaluation/recipe_model_evaluation_clouds_clim.yml
  esmvaltool/recipes/model_evaluation/recipe_model_evaluation_clouds_cycles.yml
  esmvaltool/recipes/model_evaluation/recipe_model_evaluation_precip_zonal.yml
Labels: documentation
