Repository ESMValGroup/ESMValTool, pull requests merged in 2024-11, with the labels that each got.

#3777 Remove recipe filler utility
  doc/sphinx/source/utils.rst
  esmvaltool/utils/recipe_filler.py
  setup.py
  tests/integration/test_recipe_filler.py
Labels: backwards incompatible change

#3811 Update environment: pin `iris>=3.11`, unpin `cartopy` and allow for `numpy >=2`
  environment.yml
  environment_osx.yml
  setup.py
Labels: installation

#3210 Recipe Test Workflow (RTW) prototype
  .codacy.yml
  .github/CODEOWNERS
  .github/workflows/check-rtw.yml
  .zenodo.json
  CITATION.cff
  doc/sphinx/source/gensidebar.py
  doc/sphinx/source/utils/RTW/about.rst
  doc/sphinx/source/utils/RTW/add_a_recipe.rst
  doc/sphinx/source/utils/RTW/common.txt
  doc/sphinx/source/utils/RTW/glossary.rst
  doc/sphinx/source/utils/RTW/index.rst
  doc/sphinx/source/utils/RTW/tested_recipes.rst
  doc/sphinx/source/utils/RTW/user_guide/index.rst
  doc/sphinx/source/utils/RTW/user_guide/quick_start.rst
  doc/sphinx/source/utils/RTW/user_guide/workflow.rst
  doc/sphinx/source/utils/utils.rst
  esmvaltool/utils/recipe_test_workflow/app/compare/rose-app.conf
  esmvaltool/utils/recipe_test_workflow/app/configure/bin/__init__.py
  esmvaltool/utils/recipe_test_workflow/app/configure/bin/configure.py
  esmvaltool/utils/recipe_test_workflow/app/configure/bin/test_configure.py
  esmvaltool/utils/recipe_test_workflow/app/configure/rose-app.conf
  esmvaltool/utils/recipe_test_workflow/app/get_esmval/bin/clone_latest_esmval.sh
  esmvaltool/utils/recipe_test_workflow/app/get_esmval/opt/rose-app-jasmin.conf
  esmvaltool/utils/recipe_test_workflow/app/get_esmval/opt/rose-app-metoffice.conf
  esmvaltool/utils/recipe_test_workflow/app/get_esmval/rose-app.conf
  esmvaltool/utils/recipe_test_workflow/app/install_env_file/rose-app.conf
  esmvaltool/utils/recipe_test_workflow/app/process/rose-app.conf
  esmvaltool/utils/recipe_test_workflow/flow.cylc
  esmvaltool/utils/recipe_test_workflow/meta/rose-meta.conf
  esmvaltool/utils/recipe_test_workflow/opt/rose-suite-jasmin.conf
  esmvaltool/utils/recipe_test_workflow/opt/rose-suite-metoffice.conf
  esmvaltool/utils/recipe_test_workflow/rose-suite.conf
  esmvaltool/utils/recipe_test_workflow/rose-suite.info
  esmvaltool/utils/recipe_test_workflow/site/jasmin-env
  esmvaltool/utils/recipe_test_workflow/site/jasmin.cylc
  esmvaltool/utils/recipe_test_workflow/site/metoffice-env
  esmvaltool/utils/recipe_test_workflow/site/metoffice.cylc
  setup.cfg
Labels: Recipe Test Workflow (RTW)

#3815 Fix wrong version in title in Readthedocs documentation
  .readthedocs.yaml
Labels: documentation

#3456 Add a security policy
  SECURITY.md
Labels: enhancement, documentation, community

#3823 Update RTW checks
  .github/workflows/check-rtw.yml
Labels: Recipe Test Workflow (RTW)

#3465 Run a periodic esmvalbot test via automated PR
  .github/workflows/cron_esmvalbot_test.yml
Labels: testing
