Repository ESMValGroup/ESMValTool, pull requests merged in 2025-08, with the labels that each got.

#4131 Aeronet format updates and diagnostic changes
  doc/sphinx/source/recipes/recipe_aod_aeronet_assess.rst
  esmvaltool/cmorizers/data/cmor_config/AERONET.yml
  esmvaltool/cmorizers/data/datasets.yml
  esmvaltool/cmorizers/data/formatters/datasets/aeronet.py
  esmvaltool/diag_scripts/aerosols/aod_aeronet_assess.py
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/recipes/recipe_aod_aeronet_assess.yml
Labels: diagnostic, approved by technical reviewer, approved by scientific reviewer

#4143 Automatically open pull requests to update GitHub Actions
  .github/workflows/dependabot.yml
Labels: testing

#4150 use trusted publisher routine for PyPI and retire token-based type
  .github/workflows/pypi-build-and-deploy.yml
Labels: release

#4151 fix pypa Github Action version
  .github/workflows/pypi-build-and-deploy.yml
Labels: release

#4161 Add missing method in `seaice_drift.py`
  esmvaltool/diag_scripts/seaice_drift/seaice_drift.py
Labels: diagnostic
