Repository ESMValGroup/ESMValTool, pull requests merged in 2025-07, with the labels that each got.

#3507 New CH4 lifetime diagnostic
  doc/sphinx/source/api/esmvaltool.diag_scripts.lifetime.rst
  doc/sphinx/source/api/esmvaltool.rst
  doc/sphinx/source/recipes/figures/lifetime/timeseries_ambiguous_dataset_ch4_TROP.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_lifetime.rst
  esmvaltool/diag_scripts/lifetime/lifetime.py
  esmvaltool/diag_scripts/lifetime/lifetime_func.py
  esmvaltool/recipes/recipe_ch4_lifetime.yml
Labels: diagnostic, new recipe

#4101 Aeronet-header-fix to handle V3 data
  esmvaltool/cmorizers/data/formatters/datasets/aeronet.py
Labels: observations

#4085 Add extra Ruff rules and switch to `requires-python = ">=3.11"` in pyproject.toml
  .pre-commit-config.yaml
  esmvaltool/cmorizers/data/formatters/datasets/aeronet.py
  esmvaltool/cmorizers/data/formatters/datasets/berkeleyearth.py
  esmvaltool/cmorizers/data/formatters/datasets/era_interim.py
  esmvaltool/cmorizers/data/formatters/datasets/merra2.py
  esmvaltool/diag_scripts/arctic_ocean/utils.py
  esmvaltool/diag_scripts/autoassess/_plot_mo_metrics.py
  esmvaltool/diag_scripts/autoassess/autoassess_area_base.py
  esmvaltool/diag_scripts/autoassess/land_surface_soilmoisture/soilmoisture.py
  esmvaltool/diag_scripts/climate_patterns/sub_functions.py
  esmvaltool/diag_scripts/cos22esd/climate_change_hotspot.py
  esmvaltool/diag_scripts/cos22esd/hotspot_plotter.py
  esmvaltool/diag_scripts/droughts/utils.py
  esmvaltool/diag_scripts/emergent_constraints/ecs_scatter.py
  esmvaltool/diag_scripts/kcs/global_matching.py
  esmvaltool/diag_scripts/kcs/local_resampling.py
  esmvaltool/diag_scripts/lifetime/lifetime.py
  esmvaltool/diag_scripts/monitor/monitor_base.py
  esmvaltool/diag_scripts/ocean/diagnostic_maps_quad.py
  esmvaltool/diag_scripts/portrait_plot.py
  esmvaltool/diag_scripts/runoff_et/catchment_analysis.py
  esmvaltool/diag_scripts/sea_surface_salinity/compare_salinity.py
  esmvaltool/diag_scripts/seaice_drift/seaice_drift.py
  esmvaltool/diag_scripts/thermodyn_diagtool/fluxogram.py
  esmvaltool/diag_scripts/validation.py
  esmvaltool/diag_scripts/weighting/climwip/calibrate_sigmas.py
  esmvaltool/diag_scripts/weighting/climwip/core_functions.py
  esmvaltool/diag_scripts/weighting/weighted_temperature_graph.py
  esmvaltool/utils/testing/regression/summarize.py
  pyproject.toml
  tests/unit/diag_scripts/shared/test_io.py
Labels: installation

#3983 New recipe: rate of sea ice area loss per degree warming
  .zenodo.json
  CITATION.cff
  doc/sphinx/source/recipes/figures/seaice/Annual_Antarctic_sea_ice_trends.png
  doc/sphinx/source/recipes/figures/seaice/September_Arctic_sea_ice_sensitivity.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_seaice_sensitivity.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/seaice/seaice_sensitivity.py
  esmvaltool/recipes/recipe_seaice_sensitivity.yml
Labels: diagnostic, approved by technical reviewer, new recipe, REF

#3756 Update ESACCI Cloud CMORizer (daily and monthly data)
  doc/sphinx/source/input.rst
  esmvaltool/cmorizers/data/cmor_config/ESACCI-CLOUD.yml
  esmvaltool/cmorizers/data/downloaders/datasets/esacci_cloud.py
  esmvaltool/cmorizers/data/formatters/datasets/esacci_cloud.ncl
  esmvaltool/cmorizers/data/formatters/datasets/esacci_cloud.py
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/esacci_cloud.bibtex
Labels: observations, approved by technical reviewer, approved by scientific reviewer

#4129 Fix coords in ESACCI-CLOUD cmorizer
  esmvaltool/cmorizers/data/formatters/datasets/esacci_cloud.py
Labels: observations

#4133 Remove unused option `annual_mean_kwargs` from all recipes
  esmvaltool/recipes/ref/recipe_ref_annual_cycle_region.yml
  esmvaltool/recipes/ref/recipe_ref_timeseries_region.yml
Labels: diagnostic
