Repository ESMValGroup/ESMValTool, pull requests merged in 2025-02, with the labels that each got.

#3840 Replace underscores in facets of observational datasets with minuses
  doc/sphinx/source/input.rst
  esmvaltool/cmorizers/data/cmor_config/CowtanWay.yml
  esmvaltool/cmorizers/data/cmor_config/GPCC.yml
  esmvaltool/cmorizers/data/cmor_config/LAI3g.yml
  esmvaltool/cmorizers/data/cmor_config/MOBO-DIC-MPIM.yml
  esmvaltool/cmorizers/data/datasets.yml
  esmvaltool/cmorizers/data/downloaders/datasets/mobo_dic_mpim.py
  esmvaltool/cmorizers/data/formatters/datasets/clara_avhrr.ncl
  esmvaltool/cmorizers/data/formatters/datasets/gpcc.py
  esmvaltool/cmorizers/data/formatters/datasets/mobo_dic_mpim.py
  esmvaltool/recipes/clouds/recipe_lauer22jclim_fig1_clim.yml
  esmvaltool/recipes/clouds/recipe_lauer22jclim_fig1_clim_amip.yml
  esmvaltool/recipes/clouds/recipe_lauer22jclim_fig2_taylor.yml
  esmvaltool/recipes/clouds/recipe_lauer22jclim_fig2_taylor_amip.yml
  esmvaltool/recipes/clouds/recipe_lauer22jclim_fig6_interannual.yml
  esmvaltool/recipes/clouds/recipe_lauer22jclim_fig7_seas.yml
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/recipes/ipccwg1ar6ch3/recipe_ipccwg1ar6ch3_fig_3_42_b.yml
  esmvaltool/recipes/recipe_anav13jclim.yml
  esmvaltool/recipes/recipe_perfmetrics_land_CMIP5.yml
  esmvaltool/recipes/schlund20jgr/recipe_schlund20jgr_gpp_abs_rcp85.yml
  esmvaltool/recipes/schlund20jgr/recipe_schlund20jgr_gpp_change_rcp85.yml
Labels: observations

#3866 Add links to summary page that are required for hosting at DKRZ
  esmvaltool/utils/testing/regression/summarize.py
Labels: enhancement, approved by technical reviewer, approved by scientific reviewer

#3903 Add Cloud Radiative Effects recipe for REF
  doc/sphinx/source/recipes/figures/ref/map_lwcre_MPI-ESM1-2-LR_Amon.png
  doc/sphinx/source/recipes/figures/ref/variable_vs_lat_lwcre_ambiguous_dataset_Amon.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_ref.rst
  esmvaltool/recipes/ref/recipe_ref_cre.yml
Labels: approved by technical reviewer, approved by scientific reviewer, REF

#3863 Add TropFlux CMORiser
  doc/sphinx/source/input.rst
  esmvaltool/cmorizers/data/cmor_config/TROPFLUX.yml
  esmvaltool/cmorizers/data/datasets.yml
  esmvaltool/cmorizers/data/formatters/datasets/tropflux.py
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/tropflux.bibtex
Labels: observations

#3908 Removed wrong description of option in portrait plot docstring
  esmvaltool/diag_scripts/portrait_plot.py
Labels: documentation, diagnostic

#3894 Restrict cron Github Actions tests to run from forks
  .github/workflows/check-rtw.yml
  .github/workflows/citation_file_validator.yml
  .github/workflows/create-condalock-file.yml
  .github/workflows/cron_esmvalbot_test.yml
  .github/workflows/install-from-conda.yml
  .github/workflows/install-from-condalock-file.yml
  .github/workflows/install-from-source.yml
  .github/workflows/run-tests-monitor.yml
  .github/workflows/test-development.yml
  .github/workflows/test.yml
Labels: testing

#3917 fix Autoassess diagnostic for new matplotlib 3.10 api change
  esmvaltool/diag_scripts/autoassess/stratosphere/strat_metrics_1.py
Labels: diagnostic

#3918 Fix diagnostic mpqb
  esmvaltool/diag_scripts/mpqb/mpqb_lineplot.py
  esmvaltool/diag_scripts/mpqb/mpqb_lineplot_growthrate.py
Labels: diagnostic, release

#3919 Add `filename` to list of ignored attributes in `compare.py`
  esmvaltool/utils/testing/regression/compare.py
Labels: release

#3929 force mamba 2 in Github Actions that solve environment
  .github/workflows/install-from-source.yml
  .github/workflows/run-tests-monitor.yml
  .github/workflows/test-development.yml
  .github/workflows/test.yml
Labels: testing

#3784 Add unit conversion to `DU` to recipes that use `toz`
  esmvaltool/recipes/recipe_eyring06jgr.yml
  esmvaltool/recipes/recipe_perfmetrics_CMIP5.yml
  esmvaltool/recipes/recipe_perfmetrics_CMIP5_4cds.yml
Labels: requires new ESMValCore release

#3937 Update esmvalcore pins in environment files
  environment.yml
  environment_osx.yml
Labels: release

#3598 Benchmarking recipes (Lauer et al.)
  doc/sphinx/source/recipes/figures/benchmarking/annual_cycle.png
  doc/sphinx/source/recipes/figures/benchmarking/boxplots.png
  doc/sphinx/source/recipes/figures/benchmarking/diurnal_cycle.png
  doc/sphinx/source/recipes/figures/benchmarking/map.png
  doc/sphinx/source/recipes/figures/benchmarking/timeseries.png
  doc/sphinx/source/recipes/figures/benchmarking/zonal.png
  doc/sphinx/source/recipes/figures/model_evaluation/diurnal_cycle_clt_sepacific_3hr.png
  doc/sphinx/source/recipes/figures/monitor/diurnal_cycle_clt_tropics_3hr.png
  doc/sphinx/source/recipes/figures/monitor/diurnalcycle_pr_tropics_EC-Earth3_3hr_historical_r1i1p1f1.png
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/recipe_benchmarking.rst
  doc/sphinx/source/recipes/recipe_model_evaluation.rst
  doc/sphinx/source/recipes/recipe_monitor.rst
  doc/sphinx/source/recipes/recipe_thermodyn_diagtool.rst
  esmvaltool/config-references.yml
  esmvaltool/diag_scripts/clouds/clouds.ncl
  esmvaltool/diag_scripts/monitor/monitor.py
  esmvaltool/diag_scripts/monitor/multi_datasets.py
  esmvaltool/recipes/model_evaluation/recipe_model_benchmarking_annual_cycle.yml
  esmvaltool/recipes/model_evaluation/recipe_model_benchmarking_boxplots.yml
  esmvaltool/recipes/model_evaluation/recipe_model_benchmarking_diurnal_cycle.yml
  esmvaltool/recipes/model_evaluation/recipe_model_benchmarking_maps.yml
  esmvaltool/recipes/model_evaluation/recipe_model_benchmarking_timeseries.yml
  esmvaltool/recipes/model_evaluation/recipe_model_benchmarking_zonal.yml
  esmvaltool/recipes/model_evaluation/recipe_model_evaluation_clouds_cycles.yml
  esmvaltool/recipes/monitor/recipe_monitor.yml
  esmvaltool/recipes/monitor/recipe_monitor_with_refs.yml
  esmvaltool/references/lauer25gmd.bibtex
Labels: metric, requires new ESMValCore release, new recipe

#3821 CMORizer for ESACCI-SEAICE
  doc/sphinx/source/input.rst
  esmvaltool/cmorizers/data/cmor_config/ESACCI-SEAICE.yml
  esmvaltool/cmorizers/data/datasets.yml
  esmvaltool/cmorizers/data/downloaders/datasets/esacci_seaice.py
  esmvaltool/cmorizers/data/formatters/datasets/esacci_seaice.py
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/esacci-seaice.bibtex
Labels: approved by technical reviewer, approved by scientific reviewer, REF

#3697 Update ESACCI-SST cmorizer to v3.0
  doc/sphinx/source/input.rst
  esmvaltool/cmorizers/data/cmor_config/ESACCI-SST.yml
  esmvaltool/cmorizers/data/datasets.yml
  esmvaltool/cmorizers/data/downloaders/datasets/esacci_sst.py
  esmvaltool/cmorizers/data/downloaders/ftp.py
  esmvaltool/cmorizers/data/formatters/datasets/esacci_sst.py
  esmvaltool/recipes/examples/recipe_check_obs.yml
  esmvaltool/references/esacci-sst.bibtex
Labels: requires new ESMValCore release, approved by scientific reviewer, Data
