Repository ESMValGroup/ESMValTool, pull requests merged in 2025-06, with the labels that each got.

#4072 Add footer with legal info
  doc/sphinx/source/_templates/layout.html
Labels: documentation

#4081 Replace deprecated horizontal regridding scheme `linear_extrapolate` with generic scheme
  archive/legacy_recipes/recipe_rainfarm.yml
  esmvaltool/recipes/recipe_ensclus.yml
  esmvaltool/recipes/recipe_miles_block.yml
  esmvaltool/recipes/recipe_miles_eof.yml
  esmvaltool/recipes/recipe_miles_regimes.yml
Labels: enhancement

#4086 Fix Cicle CI tests (prepend Julia to PATH for the containerized run tests)
  .circleci/config.yml
Labels: testing

#4054 Add compare command, via new develop command group
  .circleci/config.yml
  doc/sphinx/source/community/release_strategy/detailed_release_procedure.rst
  doc/sphinx/source/utils/utils.rst
  esmvaltool/utils/develop/__init__.py
  esmvaltool/utils/develop/compare.py
  esmvaltool/utils/recipe_test_workflow/flow.cylc
  setup.py
  tests/unit/utils/test_compare.py
Labels: Recipe Test Workflow (RTW)

#4088 Use `pyproject.toml` and retire `setup.py` with NO Ruff configuration changes
  doc/sphinx/source/community/code_documentation.rst
  pyproject.toml
  setup.cfg
  setup.py
Labels: enhancement, installation

#4087 Use compare command in recipe test workflow
  doc/sphinx/source/utils/RTW/user_guide/workflow.rst
  esmvaltool/utils/recipe_test_workflow/app/compare/rose-app.conf
  esmvaltool/utils/recipe_test_workflow/flow.cylc
  esmvaltool/utils/recipe_test_workflow/site/dkrz/runtime.cylc
  esmvaltool/utils/recipe_test_workflow/site/jasmin/runtime.cylc
Labels: Recipe Test Workflow (RTW)

#4070 Separate `BRANCH` variable for recipe_test_workflow cloning Core and Tool
  esmvaltool/utils/recipe_test_workflow/app/get_esmval/bin/clone_latest_esmval.sh
  esmvaltool/utils/recipe_test_workflow/app/get_esmval/opt/rose-app-metoffice.conf
Labels: Recipe Test Workflow (RTW)

#4060 Update figure selection and layout of the gallery
  doc/sphinx/source/_static/custom.css
  doc/sphinx/source/community/diagnostic.rst
  doc/sphinx/source/conf.py
  doc/sphinx/source/generate_gallery.py
  doc/sphinx/source/recipes/index.rst
  doc/sphinx/source/recipes/legacy/recipe_psyplot.rst
  doc/sphinx/source/recipes/legacy/recipe_rainfarm.rst
  doc/sphinx/source/recipes/legacy/recipe_schlund20jgr.rst
  doc/sphinx/source/recipes/legacy/recipe_spei.rst
  doc/sphinx/source/recipes/legacy_recipe_list.rst
  doc/sphinx/source/recipes/recipe_capacity_factor.rst
  doc/sphinx/source/recipes/recipe_climate_change_hotspot.rst
  doc/sphinx/source/recipes/recipe_combined_indices.rst
  doc/sphinx/source/recipes/recipe_diurnal_temperature_index.rst
  doc/sphinx/source/recipes/recipe_extreme_index.rst
  doc/sphinx/source/recipes/recipe_gier20bg.rst
  doc/sphinx/source/recipes/recipe_heatwaves_coldwaves.rst
  doc/sphinx/source/recipes/recipe_impact.rst
  doc/sphinx/source/recipes/recipe_kcs.rst
  doc/sphinx/source/recipes/recipe_modes_of_variability.rst
  doc/sphinx/source/recipes/recipe_multimodel_products.rst
  doc/sphinx/source/recipes/recipe_pv_capacity_factor.rst
  doc/sphinx/source/recipes/recipe_seaice_drift.rst
  doc/sphinx/source/recipes/recipe_thermodyn_diagtool.rst
  doc/sphinx/source/recipes/recipe_toymodel.rst
Labels: documentation, approved by technical reviewer, approved by scientific reviewer

#4099 Portrait plot example: remove sea surface temperature
  doc/sphinx/source/recipes/figures/portrait/portrait_plot.png
  doc/sphinx/source/recipes/recipe_portrait.rst
  esmvaltool/recipes/recipe_portrait_CMIP.yml
Labels: approved by technical reviewer
